StrConfig:Add(
{
-- Vật phẩm trang bị
['tips1'] = 'Cần chờ cấp: %s',
['tips2'] = 'Nghề nghiệp hạn chế: %s',
['tips3'] = 'Ctrl chuột trái đem vật phẩm gửi đi đến khung chát',
['tips4'] = 'Bán ra vật phẩm',
['tips5'] = '(%s Cái )%s Ngân lượng',
['tips6'] = 'Không thể bán ra',
['tips7'] = 'Thời gian cooldown: %s Giây',
['tips8'] = 'Phương thức thu hoạch: ',
['tips11'] = 'Thuộc tính cơ sở: ', --adder: houxudong date: 2016/7/18 reason: Trang bị tips Cấp hai nhãn hiệu
['tips12'] = 'Thuộc tính thần đúc: ',
['tips13'] = 'Thuộc tính tẩy luyện: ',
['tips14'] = 'Thí khảo ID: ',
['tips15'] = 'Thuộc tính bảo thạch: ',
['tips16'] = 'Thuộc tính Sáo trang: ',
['tips17'] = 'Thuộc tính thần võ: ',
['tips18'] = 'Tân thần đúc thuộc tính: ',
['tips19'] = 'Thuộc tính nhẫn',
['tips20'] = "Thuộc tính sáo trang",
['tips9'] = "Hôm nay đã sử dụng <font color='#65c47e'> %s/%s</font>",
['tips10'] = "Trọn đời đã sử dụng <font color='#65c47e'> %s/%s</font>",
['tips50'] = "<font color='#e59607' size='16'>  Ngân lượng thu hoạch được đường tắt </font><br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/><p><font size='14'> Từ thường ngày hoạt động, nhiệm vụ bên trong thu hoạch được </font></p><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/><p><font size='14'> Từ phó bản bên trong thu hoạch được </font></p>",
-- Cơ sở vật phẩm ban thưởng tips
['tips100'] = 'Kinh nghiệm: %s',
['tips101'] = 'Ngân lượng: %s',
['tips102'] = 'Ngân lượng: %s',
['tips103'] = 'Nguyên bảo: %s',
['tips104'] = 'Nguyên bảo khóa: %s',
['tips105'] = 'Tu vi: %s',
['tips106'] = 'Vinh dự: %s',
['tips107'] = 'Cống hiến bang phái: %s',
['tips108'] = 'Mức độ hoạt động Bang: %s',
['tips109'] = 'Cảnh giới kinh nghiệm: %s',
['tips110'] = 'Đệ tử kinh nghiệm: %s',
['tips111'] = 'Linh trị: %s',
['tips112'] = 'Điểm cống hiến Bang : %s',
['tips113'] = 'Công huân: %s',
['tips114'] = 'Điểm tích lũy: %s',
['tips115'] = 'Tinh nguyên: %s',
-- Thế giới địa đồ địa vực tips
['tips200'] = 'Cấp Quái Vật: %s',
['tips201'] = 'Phổ thông tiểu quái',
['tips202'] = '%s Cấp',
['tips203'] = '%s (%s Cấp )',
['tips204'] = ' ( Nhưng PK Khu vực )',
['tips205'] = ' ( Khu vực an toàn )',
['tips206'] = 'Tiến tới đẳng cấp: %s Cấp',
['tips207'] = '%s[%s]',
--buffTips
['tips300'] = "Lúc",
["tips301"] = 'Phân',
['tips302'] = 'Giây',
['tips303'] = 'Vĩnh cửu hữu hiệu',
['tips304'] = "<font color='#dcdcdc'> Còn thừa thời gian: %s</font>",
-- Đồng đội ảnh chân dung tips
['tips401'] = [[<font color='#d89743'>%s</font>
Đẳng cấp: <font color='#ffffff'>%s</font>
Nghề nghiệp: <font color='#ffffff'>%s</font>
Bang phái: <font color='#ffffff'>%s</font>
Vị trí: <font color='#ffffff'>%s Tuyến %s</font>]],
-- Quái vật ảnh chân dung xem xét nút bấm tips
['tips601'] = "Không thuộc",
['tips602'] = "Cuối cùng một đao thuộc về",
['tips603'] = "Xếp hạng sát thương",
['tips604'] = "Đao thứ nhất thuộc về",
-- Kỹ năng Tips
['tips701'] = "Điều kiện thăng cấp kỹ năng",
['tips702'] = "Điều kiện mở ra kỹ năng",
['tips703'] = "%s:%s( Đã đạt )",
['tips704'] = "%s:%s( Chưa đạt )",
['tips705'] = "Điểm kích kỹ năng đồ tiêu có thể mở ra kỹ năng thăng cấp giao diện",
-- Thời trang
['tips801'] = "Thời trang vũ khí",
['tips802'] = "Thời trang quần áo",
['tips803'] = "Thời trang đầu",
['tips804'] = "Nhu cầu đẳng cấp: Không hạn chế",
['tips805'] = "Nghề nghiệp hạn chế: Không hạn chế",
['tips806'] = "Thuộc tính ",
['tips807'] = "%s(%s/%s)",
['tips808'] = "3 Kiện: %s",
['tips809'] = "Còn thừa thời gian: %s Giờ %s Phút %s Giây",
-- Bang phái nhà kho
['tips901'] = "Tồn nhập thu hoạch được cống hiến: ",
['tips902'] = "Đổi ra điểm cống hiến: ",
-- Linh thú ấn ký
['tips1101'] = "Linh Bảo đã đủ cấp",
['tips1102'] = "Linh Bảo kinh nghiệm: ",
['tips1103'] = "Bản cấp thuộc tính: ",
['tips1104'] = "Hạ cấp thuộc tính: ",
['tips1105'] = "Max cấp thuộc tính: ",
['tips1106'] = "Ctrl chuột trái khóa gửi đi đến khung chat",
['tips1107'] = "Cao cấp Linh Bảo hối đoái vật liệu, có thể thông qua tầm bảo thu hoạch được",
['tips1108'] = "( Max cấp %s)",
-- Mục tiêu khóa chặt nút bấm tips
['tips1201'] = "Nhấp không khóa chặt mục tiêu",
['tips1202'] = "Nhấp khóa chặt mục tiêu",
['tips1301'] = "%s(%s Giai )",
['tips1302'] = "Giai chiến dực",
['tips1303'] = "Còn thừa thời gian:%s Giờ %s Phút %s Giây",
['tips1304'] = "Đã đến kỳ",
['tips1305'] = "Toàn thân thăng tinh tổng đẳng cấp đạt tới",
['tips1306'] = "(%s/%s) Đã kích hoạt",
['tips1307'] = "(%s/%s) Chưa kích hoạt",
['tips1308'] = "Kích hoạt thuộc tính: ",
['tips1309'] = "Toàn thân trang bị thăng cấp đến %s Cấp",
['tips1310'] = "Toàn thân trác tuyệt thuộc tính số lượng",
['tips1311'] = "Song kích trực tiếp sử dụng, đem kèm theo thuộc tính tăng thêm đến tự thân kèm theo thuộc tính trong kho.",
['tips1312'] = "Nhưng tại [ Chế tạo - Kèm theo ] Công năng bên trong tiến hành xem xét.",
['tips1313'] = "<font color='#e59607'> Thời gian cooldown: </font><font color='#00ff00'>%s</font> Giây",
['tips1314'] = "Vật phẩm sử dụng số lần:%s/%s",
['tips1315'] = "Hôm nay sử dụng số lần:%s/%s",
['tips1316'] = "Toàn thân bảo thạch tổng đẳng cấp đến %s Cấp",
['tips1317'] = "<font color='#ff6c00'> Thần đúc </font>",
['tips1318'] = "· Siêu việt",
['tips1319'] = "· Vô song",
['tips1320'] = "· Vô song",
['tips1321'] = "Giai",
['tips1322'] = "Mặc điều kiện:<font color='#cc0000'> Không thể mặc </font>",
['tips1323'] = "Không hạn chế",
['tips1324'] = "Cần %s: %s",
['tips1325'] = "Linh thú cấp bậc: %s",
['tips1326'] = "Linh thú tọa kỵ cấp bậc: %s",
['tips1327'] = "Tọa kỵ cấp bậc: %s",
['tips1328'] = "Cường hóa",
['tips1329'] = "Thăng tinh",
['tips1330'] = "Chưa khóa lại",
['tips1331'] = "Đã khóa lại",
['tips1332'] = "( Truy %s)",
['tips1333'] = "Ngẫu nhiên thu hoạch được thần đúc thuộc tính",
['tips1334'] = "Ngẫu nhiên thu hoạch được %s Đầu kèm theo thuộc tính",
['tips1335'] = "[ Không rãnh ] Nhưng kèm theo ( Thông qua chế tạo - Kèm theo tiến hành thao tác )",
['tips1336'] = "Chưa kích hoạt",
['tips1337'] = "%s(%s/%s)      Tường tình xem xét trác tuyệt sáo trang giao diện",
['tips1338'] = "%s Kiện hiệu quả: ",
['tips1339'] = "%s(%s/%s)  Hi hữu sáo trang",
['tips1340'] = "Trang bị sau thuộc tính so sánh: ",
['tips1341'] = "[ Thần ]",
['tips1342'] = "Thăng cấp sáo trang ",
['tips1343'] = " %s",
['tips1344'] = "<font color='#00ff00'> Cường hóa  %s</font>",
['tips1345'] = "Cấp Linh Trận: %s",
['tips1346'] = "Kỵ chiến cấp bậc: %s",
['tips1347'] = "Thần linh cấp bậc: %s",
['tips1348'] = "Cần %s: %s",
['tips1349'] = "Toàn thân tẩy luyện tổng đẳng cấp đến %s Cấp",
['tips1350'] = "", -- Mặc bên trong
['tips1351'] = "", -- Chưa mặc
['tips1352'] = "Trang bị cho điểm: %s",
['tips1353'] = "Mặc hạn chế: %s",
['tips1370'] = "Trang bị %s",
['tips1380'] = "Đạt tới %s Cấp sau kích hoạt",
['tips1381'] = "%s Cấp tăng thêm",
['tips1382'] = "Không hạn chế",
['tips1383'] = "Nhất chuyển",
['tips1384'] = "Nhị chuyển",
['tips1385'] = "Tam chuyển",
['tips1386'] = "Tứ chuyển",
['tips1387'] = "Ngũ chuyển",
['tips1401'] = "%s Kiện hiệu quả: Gia tăng thuộc tính cơ sở %s%%",
['tips1501'] = "Nhất giai",
['tips1502'] = "Nhị giai",
['tips1503'] = "Tam giai",
['tips1504'] = "Tứ giai",
['tips1505'] = "Ngũ giai",
['tips1506'] = "Lục giai",
['tips1507'] = "Thất giai",
['tips1508'] = "Bát giai",
['tips1509'] = "Cửu giai",
['tips1510'] = "Thập giai",
['tips1511'] = "Thập nhất giai",
['tips1512'] = "Thập nhị giai",
['tips1513'] = "Thập tam giai",
['tips1514'] = "Cấp mười bốn",
['tips1515'] = "Thập ngũ giai",
--1600~1799 Dự lưu Từ 1600 Một vài được đến
['tips1603'] = "Cấp Tọa Kỵ",
['tips1608'] = "Cấp Ngọc Bội",
['tips1609'] = "Cấp Bảo Giáp",
['tips1610'] = "Cấp Thần Binh",
['tips1611'] = "Cấp Pháp Bảo",
}
)
