StrConfig:Add(
{
['vip1'] = "Hoa Phí:",
['vip2'] = "Nguyên bảo",
['vip3'] = "Thời hạn có hiệu lực:",
['vip4'] = "Ngày",
['vip5'] = "Nhỏ hơn 1 Ngày",
['vip6'] = "Nguyên bảo không đủ, phải chăng tiến về nạp tiền thu hoạch được đại lượng Nguyên bảo?",
['vip7'] = "Phải chăng tốn hao",
['vip8'] = "Nguyên bảo, kích hoạt",
['vip9'] = "VIP",
['vip10'] = "Nguyên bảo, tục phí",
['vip11'] = "Trước mắt VIP Đẳng cấp: ",
['vip12'] = "Hệ thống này toàn thuộc tính vĩnh cửu: ",
['vip13'] = "Hạ cấp vip Thuộc tính đề cao: ",
['vip14'] = "Điểm kích xem xét toàn bộ vip Đặc quyền",
['vip15'] = "Kích hoạt kim cương vip, hệ thống này toàn thuộc tính vĩnh cửu đề cao: ",
['vip16'] = "Điểm kích kích hoạt vip",
['vip17'] = "Ngài còn không phải hoàng kim vip, mua sắm hoàng kim vip Sau nhưng nhận lấy.",
['vip18'] = "",
['vip19'] = "",
['vip20'] = "Nạp tiền",
['vip100'] = "Kim cương VIP Ngoài định mức %s",
['vip101'] = "Thành công thăng giai sau nhưng nhận lấy",
['vip102'] = "Khỏa",
['vip103'] = "Trước mắt nhưng nhận lấy %s",
['vip104'] = "( Thăng giai sau khi thành công nhưng nhận lấy còn lại %s)",
['vip105'] = "Vạn",
['vip106'] = "<font color='#b4b4b4'> Nhiều nhất trả về %s Khỏa </font>",
['vip107'] = "Mời kịp thời click nhận lấy",
['vip108'] = "<font size='18'>%s</font><font size='18'> Nguyên bảo </font>",
['vip109'] = "Thành công thăng giai sau nhưng nhận lấy",
['vip110'] = "Bạch ngân",
['vip111'] = "Hoàng kim",
['vip112'] = "Kim cương",
['vip113'] = "Vĩnh cửu",
['vip114'] = "Đã đến kỳ",
['vip115'] = "Hữu hiệu thời gian",
['vip116'] = "Hữu hiệu thời gian: Vĩnh cửu",
['vip117'] = "Ngày",
['vip118'] = "Vĩnh cửu",
['vip119'] = "Phải chăng tốn hao %s Nguyên bảo, kích hoạt hoàng kim VIP",
['vip120'] = "Phải chăng tốn hao %s Nguyên bảo, kích hoạt kim cương VIP",
['vip121'] = "Phải chăng tốn hao %s Nguyên bảo, kích hoạt bạch ngân VIP",
['vip122'] = "Phải chăng tốn hao %s Nguyên bảo, tục phí hoàng kim VIP",
['vip123'] = "Phải chăng tốn hao %s Nguyên bảo, tục phí kim cương VIP",
['vip124'] = "Phải chăng tốn hao %s Nguyên bảo, tục phí bạch ngân VIP",
['vip125'] = "Kéo dài",
['vip126'] = "Lễ bao đã lĩnh",
['vip127'] = "Ngài có cao cấp hơn gói quà nhưng lĩnh",
['vip128'] = "Tăng lên VIP Đẳng cấp sau nhưng nhận lấy",
['vip129'] = "VIP Lễ bao",
['vip130'] = "VIP Gói quà",
['vip131'] = "Mỗi tiêu phí 1 Nguyên bảo gia tăng 1 Điểm vip Kinh nghiệm",
['vip132'] = "Lại tiêu hao %s Nguyên bảo liền có thể nhắc nhở đến VIP%s, mỗi tiêu hao 1 Nguyên bảo thu hoạch được 1 Điểm kinh nghiệm",
['vip133'] = "Thăng đến hạ giai có thể gia tăng %s Khỏa",
['vip134'] = "Tốn hao %s Mua sắm đạo cụ, kích hoạt hoàng kim VIP",
['vip135'] = "Tốn hao %s Mua sắm đạo cụ, kích hoạt kim cương VIP",
['vip136'] = "Tiêu hao:<font color='#00FF00'>%s</font>",-- Lục sắc
['vip137'] = "Tiêu hao:<font color='#FF0000'>%s</font>",-- Màu đỏ
}
);
