StrConfig:Add(
{
['role1'] = 'Cấp bậc chưa đủ %s',
['role2'] = 'Kinh nghiệm không đủ',
['role3'] = 'Đem tất cả tiềm năng điểm phân phối ở đây thuộc tính bên trên',
['role4'] = 'Phân phối 1 Điểm tiềm năng điểm',
['role5'] = 'Hủy bỏ 1 Điểm vừa rồi phân phối tiềm năng điểm',
['role6'] = 'Hủy bỏ tất cả vừa rồi phân phối ở đây thuộc tính tiềm năng điểm',
['role7'] = 'Bảo tồn phân phối tiềm năng điểm, bảo tồn sau không thể đổi càng',
['role8'] = 'Theo hệ thống đề cử phương thức phân phối tất cả tiềm năng điểm',
['role9'] = 'Dùng tay phân phối tất cả tiềm năng điểm',
['role10'] = 'Mỗi lần thăng cấp lúc tự động theo hệ thống đề cử phương thức phân phối tiềm năng điểm',
['role11'] = '',
['role12'] = 'Kinh nghiệm không đủ, không cách nào thăng cấp',
['role13'] = 'Phân phối thành công',
['role14'] = 'Trước mắt kinh nghiệm không đủ để thăng cấp',
['role15'] = 'Người chơi hạ tuyến hoặc là không tại cùng một cái tuyến, không cách nào xem xét tin tức',
['role16'] = 'Nên người chơi không có kích hoạt Linh thú',
['role17'] = "<font color='%s' size='16'>%s</font><font color='#29cc00'>(%s Cấp )</font><br/><p><img height='3'/></p><p><img width='200' height='2' align='baseline' vspace='5' src='%s'/></br></p><font color='#d1c0a5' size='14'> Kỹ năng hiệu quả:</font><br/><font color='#ff8f43' size='14'>%s</font>",
['role18'] = [[ Trước mắt kinh nghiệm: %s/%s
Trước mắt kinh nghiệm đã đủ, có thể đem trước mắt kinh nghiệm dùng cho thăng cấp hoặc là tăng lên cảnh giới.
]],
['role19'] = 'Thăng Cấp',
['role20'] = 'Tăng lên cảnh giới',
['role21'] = 'Ngươi đã đến đạt đẳng cấp hạn mức cao nhất',
-- Thuộc tính tips
['role101'] = "<font color='#dcdcdc'> Sinh mệnh về 0, nhân vật đem tử vong, sau khi chết có thể lựa chọn nguyên điểm phục sinh hoặc về thành phục sinh </font>",
['role102'] = "<font color='#dcdcdc'> Nội lực có thể dùng tại kỹ năng tiêu hao, khi nội lực không đủ lúc, không cách nào phóng thích kỹ năng </font>",
['role103'] = "<font color='#dcdcdc'> Lực công kích trị số lớn nhỏ ảnh hưởng ngài đang đánh quái hoặc PK Lúc tạo thành tổn thương lớn nhỏ </font>",
['role104'] = "<font color='#dcdcdc'> Phòng ngự trị số ảnh hưởng ngài nhận được quái vật hoặc người chơi khác lúc công kích nhận tổn thương lớn nhỏ </font>",
['role105'] = "<font color='#dcdcdc'> Chính xác giá trị lớn nhỏ ảnh hưởng ngài đang đánh quái hoặc PK Lúc, đánh trúng mục tiêu tỉ lệ </font>",
['role106'] = "<font color='#dcdcdc'> Né tránh giá trị lớn nhỏ ảnh hưởng ngài tránh né công kích tỉ lệ </font>",
['role107'] = "<font color='#dcdcdc'> Bạo kích giá trị lớn nhỏ ảnh hưởng ngài đang đánh quái hoặc PK Lúc tạo thành nhiều lần tổn thương tỉ lệ </font>",
['role108'] = "<font color='#dcdcdc'> Sức bền giá trị lớn nhỏ ảnh hưởng ngài nhận bạo kích tỉ lệ </font>",
['role109'] = "<font color='#dcdcdc'> Bạo tổn thương giá trị lớn nhỏ ảnh hưởng ngài tại bạo kích lúc, tạo thành tổn thương bội suất </font>",
['role110'] = "<font color='#dcdcdc'> Miễn bạo giá trị lớn nhỏ ảnh hưởng ngài nhận được bạo kích lúc, giảm miễn đối diện bạo kích tổn thương bội suất </font>",
['role111'] = "<font color='#dcdcdc'> Đâm xuyên giá trị lớn nhỏ ảnh hưởng ngài tại công kích lúc tạo thành không nhìn phòng ngự mức thương tổn lớn nhỏ </font>",
['role112'] = "<font color='#dcdcdc'> Đón đỡ suất lớn nhỏ ảnh hưởng ngài nhận được tổn thương lúc đón đỡ rơi bộ phận tổn thương tỉ lệ </font>",
['role113'] = "<font color='#dcdcdc'> Đón đỡ giá trị lớn nhỏ ảnh hưởng ngài nhận được tổn thương lúc giảm miễn rơi tổn thương lớn nhỏ </font>",
['role114'] = "<font color='#dcdcdc'> Tổn thương tăng cường giá trị lớn nhỏ ảnh hưởng ngài tại tạo thành tổn thương lúc ngoài định mức đề cao tỉ lệ phần trăm </font>",
['role115'] = "<font color='#dcdcdc'> Giảm tổn thương giá trị lớn nhỏ ảnh hưởng ngài nhận được tổn thương lúc giảm miễn rơi tổn thương tỉ lệ phần trăm </font>",
['role116'] = "<font color='#dcdcdc'> Hồn lực giá trị có thể đề cao ngài lực công kích </font>",
['role117'] = "<font color='#dcdcdc'> Thể phách giá trị có thể đề cao ngài sinh mệnh cùng phòng ngự </font>",
['role118'] = "<font color='#dcdcdc'> Thân pháp giá trị có thể đề cao mạng của ngài trung hoà né tránh </font>",
['role119'] = "<font color='#dcdcdc'> Trị số tinh thần có thể đề cao ngài bạo kích cùng Sức bền </font>",
['role120'] = "<font color='#dcdcdc'> Tốc độ công kích ảnh hưởng ngài hai lần công kích khoảng cách </font>",
['role121'] = "<font color='#dcdcdc'> Tốc độ di chuyển ảnh hưởng ngài tại trên địa đồ tốc độ di chuyển </font>",
['role122'] = "<font color='#dcdcdc'> Nhân vật trước %s Cấp tự động thăng cấp <br/>%s Cấp sau cần dùng tay thăng cấp </font>",
['role123'] = "<font color='#dcdcdc'> Ảnh hưởng trác tuyệt một kích mỗi lần phán định lúc, có thể hay không tạo thành trác tuyệt một kích tỉ lệ, phán định số lần tương đương trước mắt trên thân trác tuyệt trang bị số lượng </font>",
['role124'] = "<font color='#dcdcdc'> Ảnh hưởng tạo thành trác tuyệt một kích lúc tổn thương lớn nhỏ </font>",
['role125'] = "<font color='#dcdcdc'> Ảnh hưởng lúc công kích coi nhẹ mục tiêu phòng ngự lớn nhỏ </font>",
['role126'] = "<font color='#dcdcdc'> Ngài có tiềm năng điểm nhưng phân phối <br/> Phân phối tiềm năng có thể dùng ngài càng cường đại </font>",
['role127'] = "<font color='#dcdcdc'> Ác ý giết người đem gia tăng PK Giá trị <br/>PK Giá trị mỗi 30 Phút tự động tiêu trừ 1 Điểm.</font>",
['role128'] = "<font color='#dcdcdc'> Sân thi đấu vinh dự, nhưng tại sân thi đấu trong cửa hàng hối đoái đạo cụ.</font>",
['role129'] = "<font color='#dcdcdc'> Ảnh hưởng thần võ kỹ năng tỉ lệ phát động cùng tự thân chống cự người chơi khác thần võ kỹ năng tỉ lệ.</font>",
['role200'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Quy tắc nhắc nhở:</font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thông qua giết quái cùng giết BOSS Thu hoạch
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Tại ba lô bên trong sử dụng đạo cụ gia tăng đối ứng thuộc tính, khác biệt phẩm cấp đạo cụ gia tăng thuộc tính giá trị khác biệt
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Khác biệt đẳng cấp đan dược mỗi ngày có thể phục dụng hạn mức cao nhất khác biệt
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Tổng sử dụng số lần đạt tới hạn mức cao nhất sau đem không cách nào lại sử dụng nên loại đạo cụ <img height='10'/></textformat>]],
['role251'] = "Vật phẩm số lượng không đủ",
-- Tin tức cặn kẽ
['role301'] = "Không",
['role302'] = "Thuộc tính cơ sở",
['role303'] = "Chiến đấu thuộc tính",
-- Đan dược
['role401'] = "Tiến độ: %s%%",
['role402'] = "Công kích <font color='#E7D6B5'> %s</font>",
['role403'] = "Phòng ngự <font color='#E7D6B5'> %s</font>",
['role404'] = "Sinh mệnh tối đa <font color='#E7D6B5'> %s</font>",
['role406'] = "Thể chất <font color='#E7D6B5'> %s</font>",  --changer: houxudong  range: role406 ---role409
['role407'] = "Thân pháp <font color='#E7D6B5'> %s</font>",
['role408'] = "Lực lượng <font color='#E7D6B5'> %s</font>",
['role409'] = "Tinh thần <font color='#E7D6B5'> %s</font>",
['role405'] = "(%s/%s)",
['role419'] = '<font color= "#00ff00"> Sử dụng thành công </font>',
['role420'] = 'Không có có thể sử dụng đan dược!',
['role421'] = 'Chỉ có VIP Mới có thể sử dụng',
['role422'] = 'Tự động sử dụng bên trong túi đeo lưng có thể dùng phổ thông đan dược',
['role423'] = 'Tự động sử dụng bên trong túi đeo lưng có thể dùng chí tôn đan dược',
['role424'] = "<font color='#ffcc33' size='16'> Đan dược </font><br/><font color='#dcdcdc'> Sử dụng đan dược gia tăng nhân vật thuộc tính </font><br/><font color='#e59607' size='16'> Đan dược kèm theo thuộc tính </font><br/><font color='#00ff00'><font color ='#d5b772'> Công kích </font>  %s <font color ='#d5b772'> Phòng ngự </font>  %s <font color ='#d5b772'> Sinh mệnh </font>  %s</font><p><img height='3'/><p><img width='210' height='1' align='baseline' vspace='3' src='img://resfile/icon/tipsLine.png'/></p><font color='#00ff00'> Điểm kích này nút bấm mở ra [ Đan dược ] Giao diện </font>",
['role425'] = "Cánh",
['role426'] = "Tạm chưa mở ra",
['role427'] = "Tạm thời chưa có trác tuyệt sáo trang thuộc tính",
['role428'] = "<textformat leading='-84'><p>%s Kiện hiệu quả: </p></textformat>",
['role429'] = "Không phối ngẫu",
-- Dung hợp tương quan  changer :houxudong
['role430'] = "Trang bị loại hình không xứng đôi, mời lựa chọn lần nữa!",
['role431'] = "XXX Đạo cụ không đủ, không cách nào dung hợp!",
['role432'] = "Ngân lượng không đủ, không cách nào dung hợp!",
['role433'] = "Chúc mừng ngài, dung hợp thành công!",
['role434'] = "Dung hợp thất bại!",
['role435'] = "Cấp số khác biệt!",
['role436'] = "Trang bị vị khác biệt!",
['role437'] = "Chí ít có một kiện không phải hai trác tuyệt trang bị!",
['role438'] = "Vật liệu không đủ!",
['role439'] = "Nên trang bị không thể dung hợp!",
['role440'] = "Xin liên lạc GM!",
['role441'] = "Mời lựa chọn trang bị!",
['role442'] = "<font color='#2aaefa'>%s</font>",
['role443'] = "<font color='#cc00ff'>%s</font>",
['role444'] = "<font color='#fff000'>%s</font>",
['role445'] = 'Phật châu',
['role446'] = 'Bùa hộ mệnh',
['role447'] = 'Huyền Binh',
}
);
