UIStrConfig:Add(
{
["SuperGlory001"] = "Trước mắt thành chủ",
["SuperGlory002"] = "Đã liên nhiệm    Giới",
["SuperGlory003"] = "Lần sau tranh bá chiến phe tấn công có thể đạt được  tăng thêm: ",
["SuperGlory004"] = "Chiếm lĩnh thủ vệ bang phái",
["SuperGlory005"] = "Tư cách khiêu chiến bang phái",
["SuperGlory006"] = "Truyền tống vào chiến trường",
["SuperGlory007"] = "<u> Bang phái chiến quy tắc </u>",
["SuperGlory008"] = "Bổ nhiệm",
["SuperGlory009"] = "Cúng bái",
["SuperGlory010"] = "Trước mắt đã cúng bái số lần: ",
["SuperGlory011"] = "Vương thành khiêu chiến thời gian:",
["SuperGlory012"] = "  Trước mắt trạng thái",
["SuperGlory013"] = "Lần sau nhưng khiêu chiến thời gian:",
["SuperGlory014"] = "Cấp cho gói quà",
["SuperGlory015"] = "Gói quà số lượng: ",
["SuperGlory016"] = "<font color='#C2793E'> Tại vương thành chiến bên trong thủ hộ vương thành bang phái thành viên tại thủ hộ thành công đồng đều có thể đạt được  thủ hộ gói quà, <br/> Mỗi lần thủ hộ thành công đồng đều thu hoạch được ngoài định mức số lượng gói quà, từ thành chủ tiến hành phân phát.</font><br/><font color='#29cc00'> Gói quà ban thưởng và số lượng theo thành công thủ hộ số lần gia tăng mà gia tăng.</font>",
["SuperGlory017"] = "Số lượng gói quà trước mắt !",
["SuperGlory018"] = "Chia đều",
["SuperGlory019"] = "Phân phối",
["SuperGlory020"] = "Người chơi danh tự",
["SuperGlory031"] = "Đẳng cấp",
["SuperGlory032"] = "Chức vị",
["SuperGlory033"] = "Gói Quà",
["SuperGlory034"] = "Xác nhận",
["SuperGlory035"] = "Chi tiết tin tức",
["SuperGlory036"] = "",
["SuperGlory037"] = "<font color='#6EA2BD'>[ Kèm theo thuộc tính ]</font>",
["SuperGlory038"] = "<font color='#6EA2BD'> Công kích 1000<br/> Phòng ngự 400<br/> Sinh mệnh 5000</font>",
["SuperGlory039"] = "<font color='#6EA2BD'>[ Kèm theo kỹ năng ]</font>",
["SuperGlory040"] = "Sở thuộc bang phái",
["SuperGlory041"] = "Người chơi đẳng cấp",
["SuperGlory042"] = "Người chơi chiến lực",
["SuperGlory043"] = "Phát gói quà",
["SuperGlory044"] = "",
["SuperGlory045"] = "",
["SuperGlory046"] = "",
["SuperGlory047"] = "",
["SuperGlory048"] = "",
["SuperGlory049"] = "",
["SuperGlory05"] = "",
-- Quy tắc bảng
["SuperGlory500"] = "Tham dự ",
["SuperGlory501"] = "Mở ra thời gian",
["SuperGlory502"] = "Quy Tắc Hoạt Động",
["SuperGlory503"] = "Thưởng Thắng Trận",
["SuperGlory504"] = "Thưởng Thua Trận",
["SuperGlory505"] = "Chú ý hạng mục",
["SuperGlory506"] = "1. Vẻn vẹn bang phái thành viên có thể tham gia, không phải bang phái thành viên mời trước sáng tạo hoặc gia nhập bang phái.<br/>2. Thắng được [ Bang phái chiến - Di tích chi chiến ] Điểm tích lũy xếp hạng thứ nhất tên bang phái, thu hoạch tiến công thần điện tư cách.<br/>3. Khai phục sau lần thứ nhất mở ra này hoạt động lúc, [ Bang phái chiến - Di tích chi chiến ] Xếp hạng thứ nhất cùng thứ hai bang phái sẽ tại bang phái chiến kết thúc sau có thể đạt được  vương thành tranh đoạt quyền.<br/>4. Vòng thứ nhất hoạt động sau, chiếm lĩnh vương thành bang phái đem sẽ không tham dự vào [ Bang phái chiến - Di tích chi chiến ] Bên trong.<br/>",
["SuperGlory507"] = "1. Khai phục sau thứ 3, 5, 7 Ngày mỗi đêm <font color='#32961e'> 21:00 - 21:30</font><br/>2. Khai phục một tuần sau, cố định vì mỗi thứ sáu ban đêm <font color='#32961e'> 21:00 - 21:30</font> ",
["SuperGlory508"] = "1. Hoạt động mở ra sau song phương thành viên thông qua bang phái hoạt động bảng bên trong tiến vào nút bấm tiến vào chiến trường tràng cảnh.<br/>2. Song phương ban đầu riêng phần mình có được một cái điểm phục sinh, ở vào chiến trường hai đầu, trong hoạt động có thể sử dụng phục sinh đạo cụ nguyên địa phục sinh.<br/>3. Phe tấn công chiếm lĩnh tràng cảnh bên trong bốn Thần thú pho tượng nhưng vì phe tấn công thành viên mang đến thuộc tính tăng thêm. Phòng thủ phương chiếm lĩnh thích hợp tiêu phe tấn công thuộc tính tăng thêm <br/>4. Phe tấn công chiếm lĩnh tượng thần sau, tượng thần đem làm phe tấn công miễn phí điểm phục sinh, coi như gần phục sinh.<br/>5. Phe tấn công tại hoạt động hạn định thời gian bên trong đánh hạ phòng thủ phương thần điện vì đạt được thắng lợi.<br/>6. Thần điện chỉ có thể tại phụ cận không có phòng thủ bang phái thành viên lúc mới có thể công kích, cần trước thanh tràng.<br/>7. Phòng thủ phương tại hoạt động hạn định thời gian bên trong bảo vệ thần điện thành công vì đạt được thắng lợi.<br/>8. Phe thắng lợi tại hoạt động kết thúc sau thu hoạch được vương thành chiếm lĩnh quyền.<br/>",
["SuperGlory509"] = "1. Tất cả tham gia hoạt động bang phái thành viên đồng đều có thể đạt được  giúp cống <font color='#32961e'> 500</font>.<br/>2. Chiến thắng Phương bang chủ có thể đạt được  chí tôn xưng hào <font color='#d89743'>[ Chúng thần chi vương ]</font>.<br/>3. Tất cả bang phái thành viên được hưởng <font color='#d89743'>[ Chí tôn trời minh ]</font> Đặc biệt vinh hạnh đặc biệt.<br/>4. Chúng thần chi vương người chơi nhưng nhận đuổi tùy ý cùng bang phái thành viên vì <font color='#d89743'>[ Vạn Tượng tôn thần ]</font>, hưởng thụ đặc thù xưng hào cùng thuộc tính tăng thêm.<br/>5. Căn cứ hoạt động kết thúc lúc, bản bang phái chiếm lĩnh Thần thú pho tượng số, bản bang người đánh giết bài danh phía trên mấy tên người chơi đem tự động thu hoạch được Chân Thần chức vị, thu hoạch được đặc thù xưng hào cùng thuộc tính tăng thêm, Chân Thần chức vị không cách nào nhận đuổi.",
["SuperGlory510"] = "1. Tất cả tham gia hoạt động bang phái thành viên đồng đều có thể đạt được  giúp cống <font color='#32961e'> 300</font>.<br/>2. Căn cứ hoạt động kết thúc lúc, bản bang phái chiếm lĩnh Thần thú pho tượng số, bản bang người đánh giết bài danh phía trên mấy tên người chơi đem tự động thu hoạch được Chân Thần chức vị, thu hoạch được đặc thù xưng hào cùng thuộc tính tăng thêm, Chân Thần chức vị không cách nào nhận đuổi.",
["SuperGlory511"] = "1. Hoạt động trong lúc đó không cách nào tiến hành bang chủ chuyển nhượng.<br/>2. Chỉ có cùng ngày không có thay đổi qua bang phái người chơi tham dự hoạt động hậu phương có thể đạt được  ban thưởng.<br/>3. <font color='#d89743'>[ Chí tôn thần long ]</font> Tọa kỵ cùng chúng thần chi vương thân phận khóa lại, chỉ có bang chủ có thể ngồi cưỡi.<br/>4. Chân Thần chức vị cùng chiếm lĩnh pho tượng đối ứng. Thanh Long tượng thần = Thanh Long Chân Thần, Bạch Hổ tượng thần = Bạch Hổ Chân Thần, Chu Tước tượng thần = Chu Tước Chân Thần, Huyền Vũ tượng thần = Huyền Vũ Chân Thần <br/>5. Thu hoạch được chúng thần chi vương danh hiệu người chơi không cách nào lại thu hoạch được Chân Thần chức vị, kết toán lúc đem theo thứ tự hoãn lại.<br/>6. Chân Thần chức vị người chơi không cách nào được bổ nhiệm làm Vạn Tượng tôn thần",
["SuperGlory512"] = "",
["SuperGlory513"] = "",
["SuperGlory514"] = "",
["SuperGlory515"] = "",
["SuperGlory516"] = "",
["SuperGlory517"] = "",
["SuperGlory518"] = "",
["SuperGlory519"] = "",
}
)
