StrConfig:Add(
{
['hecheng1'] = "<font color='#00ff00'>%s</font>",
['hecheng2'] = "<font color='#ff0000'>%s</font>",
['hecheng3'] = "Cần vật liệu",
['hecheng4'] = "Phân giải có thể đạt được  vật liệu",
['hecheng5'] = "Hợp thành số lượng:",
['hecheng6'] = "Phân giải số lượng:",
['hecheng7'] = "<font color ='#00ff00'> Đạo cụ thành công hợp thành </font>",
['hecheng8'] = "Đạo cụ thành công phân giải",
['hecheng9'] = "<font color='#c8c8c8'>%s</font><font color='#00ff00'>(%s)</font>",
['hecheng10'] = "<font color='#c8c8c8'>%s</font>",
['hecheng11'] = "<font color='#c2793e'>%s</font>",
['hecheng12'] = "<font color='#fac41e'>%s</font>",
['hecheng13'] = "Đã đạt hạn mức cao nhất",
['hecheng14'] = "Hiện tại không thể phân giải vật phẩm",
['hecheng15'] = "Hiện tại không thể hợp thành vật phẩm",
['hecheng16'] = "Xin điền vào hợp thành số lượng",
['hecheng17'] = "Xin điền vào phân giải số lượng",
['hecheng18'] = "<font color='#fac41e'>%s</font>",
['hecheng181'] = "<font color='#fac41e'>%s</font><font color='#00ff00'>(%s)</font>",
['hecheng111'] = "<font color='#c2793e'>%s</font><font color='#00ff00'>(%s)</font>",
['hecheng19'] = "Ngân lượng không đủ",
['hecheng20'] = "<font color='#fac41e'>%s</font>",
['hecheng21'] = "<font color='#29cc00'>%s(%s)</font>",
['hecheng22'] = "Gia tăng xác suất thành công",
['hecheng23'] = "Công  Kích:",
['hecheng24'] = "Phòng  Ngự:",
['hecheng25'] = "Sinh  Mệnh:",
['hecheng26'] = "Tổn thương tăng cường",
['hecheng27'] = "Giảm tổn thương",
['hecheng28'] = "<font color ='#00ff00'> Cánh hợp thành thành công!</font>",
['hecheng29'] = "Vật liệu không đủ, không cách nào hợp thành",
['hecheng30'] = "Vật liệu không đủ, không cách nào sử dụng",
['hecheng31'] = "Vận khí không tốt, hợp thành thất bại rồi!",
['hecheng32'] = "Ngân lượng không đủ, không cách nào hợp thành",
['hecheng33'] = "Ba lô đã đủ, không cách nào hợp thành",
['hecheng34'] = "<font color='#7C4FD9'> ( Hợp thành thường có tỉ lệ thu hoạch được này thuộc tính )</font>",
['hecheng35'] = "<font color='#00ff00'><u>%s</u></font>",
['hecheng36'] = "<font color='#ff0000'><u>%s</u></font>",
-- Cánh thăng tinh
['wingstarup001'] = "<u><font color='%s'>%s Khỏa </font></u>",
-- Cánh thăng tinh nhắc nhở
['wingstarup100'] = "Đạo cụ không đủ",
['wingstarup101'] = "Ngân lượng không đủ",
['wingstarup102'] = "Công năng chưa mở ra",
['wingstarup103'] = "Cường hóa hạn mức cao nhất",
['wingstarup105'] = "<font color='#00ff00'> Trưởng thành giá trị %s</font>",
['wingstarup_att'] = 'Công  Kích:',
['wingstarup_def'] = 'Phòng  Ngự:',
['wingstarup_hp'] = 'Sinh  Mệnh:',
['wingstarup_igdef'] = 'Không nhìn một kích:',
}
);
