StrConfig:Add(
{
['fabao01'] = '%s-%s',
['fabao02'] = '%s-%s',
['fabao03'] = '%s-%s',
['fabao04'] = '%s-%s',
['fabao05'] = '%s-%s',
['fabao001'] = 'Sinh mệnh tư chất:%s',
['fabao002'] = 'Công kích tư chất:%s',
['fabao003'] = 'Phòng ngự tư chất:%s',
['fabao004'] = 'Chính xác tư chất:%s',
['fabao005'] = 'Né tránh tư chất:%s',
['fabao1'] = 'LV:%s',
['fabao2'] = 'Lực chiến:%s',
['fabao3'] = 'Kinh nghiệm %s/%s',
['fabao4'] = '%s',
['fabao5'] = '%s',
['fabao6'] = '%s',
['fabao7'] = '%s',
['fabao8'] = '%s',
['fabao18'] = '-%s',
['fabao9'] = '(%s/%s)',
['fabao10'] = 'Mức tiềm lực:%s',
['fabao11'] = "Nghỉ ngơi",
['fabao12'] = "Xuất chiến",
['fabao13'] = "Pháp bảo kinh nghiệm gia tăng %s",
['fabao14'] = 'Phải chăng xác nhận phân giải?',
['fabao15'] = 'Phải chăng xác nhận dung hợp?',
['fabao16'] = 'Phải chăng xác nhận trùng sinh?',
['fabao17'] = 'Phải chăng xác nhận học tập?',
}
);
