StrConfig:Add(
{
['rankstr001'] = 'Cấp bậc chưa đủ 20',
['rankstr002'] = 'Chưa kiểm tra đến tin tức liên quan',
['rankstr003'] = "%s Cấp",
['rankstr004'] = "%s/%s",
['rankstr101'] = '<font color="#ff0000"> Không lên bảng </font>',
-- page Danh tự
['ranktype001'] = "  Xếp hạng        Tên người chơi           Đẳng cấp          Nhân vật",
['ranktype002'] = "  Xếp hạng        Tên người chơi         Đẳng cấp    Nhân vật      Lực chiến",
['ranktype003'] = "  Xếp hạng        Tên người chơi          Tọa kỵ tên        Tọa kỵ cấp số",
['ranktype004'] = "  Xếp hạng        Tên người chơi           Nhân vật         Cảnh giới đẳng cấp",
--['ranktype005'] = "  Xếp hạng     Tên người chơi       Linh thú tên    Linh thú đẳng cấp",
--['ranktype006'] = "  Xếp hạng     Tên người chơi       Linh trận tên    Linh trận đẳng cấp",
['ranktype007'] = "  Xếp hạng     Tên người chơi        Nhân vật       Tổn thương",
['ranktype008'] = "  Xếp hạng     Tên người chơi        Nhân vật       Số lượng",
['ranktype009'] = "  Xếp hạng        Tên người chơi          Thần binh tên        Thần binh đẳng cấp",
['ranktype0010'] = "  Xếp hạng        Tên người chơi          Pháp bảo tên        Đẳng cấp pháp bảo",
['ranktype0011'] = "  Xếp hạng        Tên người chơi          Bảo giáp tên        Bảo giáp đẳng cấp",
['ranktype0012'] = "  Xếp hạng        Tên người chơi          Ngọc bội tên        Ngọc bội đẳng cấp",
['ranktype0013'] = "  Xếp hạng        Tên người chơi          Thiên thần tên        Thiên thần đẳng cấp",
-- Bảng xếp hạng nhãn hiệu trang
["ranktab1"] = "Bảng đẳng cấp",
["ranktab2"] = "Chiến lực bảng",
["ranktab3"] = "Tọa kỵ bảng",
["ranktab4"] = "Cảnh giới bảng",
["ranktab12"] = "Ngọc bội bảng",
--["ranktab5"] = "Linh thú bảng",
--["ranktab6"] = "Linh trận bảng",
--["ranktab7"] = "Cực hạn khiêu chiến tổn thương bảng",
--["ranktab8"] = "Cực hạn khiêu chiến cày quái bảng",
--["ranktab9"] = "Thần binh bảng",
--- Bảng xếp hạng thủ danh tự
['rankfirst1'] = "Bảng đẳng cấp khôi thủ",
['rankfirst2'] = "Chiến lực bảng khôi thủ",
['rankfirst3'] = "Tọa kỵ bảng khôi thủ",
['rankfirst4'] = "Bảng đẳng cấp khôi thủ",
--['rankfirst5'] = "Linh thú bảng khôi thủ",
--['rankfirst6'] = "Linh trận bảng khôi thủ",
--['rankfirst8'] = "Cực hạn khiêu chiến tổn thương bảng khôi thủ",
--['rankfirst9'] = "Cực hạn khiêu chiến cày quái bảng bảng khôi thủ",
['rankstr005'] = "Nhắc nhở: Cấp bậc, sức chiến đấu giống nhau lúc, theo kinh nghiệm cùng tương quan hệ thống thăng giai tiến độ xếp hạng.<br/> Vượt phục bảng xếp hạng số liệu không phải thời gian thực đổi mới",
['rankstr006'] = "Nhắc nhở: Cấp bậc, sức chiến đấu giống nhau lúc, theo kinh nghiệm cùng tương quan hệ thống thăng giai tiến độ xếp hạng.",
['rankstr007'] = "Vượt phục bảng xếp hạng 230 Cấp mở ra",
}
);
