UIStrConfig:Add(
{
['ranklist001'] = "Bảng xếp hạng",
['ranklist002'] = "Chí tôn đường",
['ranklist003'] = "Bản phục xếp hạng",
['ranklist004'] = "Vượt phục xếp hạng",
['ranklist005'] = "Bản phục bảng xếp hạng tin tức mỗi 15 Phút đổi mới một lần, vượt phục xếp hạng mỗi 1 Giờ đổi mới một lần",
['ranklist006'] = "Chí tôn bảng",
['ranklist007'] = "Bảng đẳng cấp",
['ranklist008'] = "Chiến lực bảng",
['ranklist009'] = "Tọa kỵ bảng",
['ranklist011'] = "Thiên Ác bảng",
['ranklist012'] = "  Xếp hạng       Tên người chơi       Đẳng cấp        Nhân vật        Lực chiến",
['ranklist013'] = "Tên người chơi",
['ranklist014'] = "Đẳng cấp",
['ranklist015'] = "Nhân vật",
['ranklist016'] = "Sức chiến đấu",
['ranklist017'] = "Bản Thân",
['ranklist018'] = "Tìm kiếm",
['ranklist019'] = "Tọa kỵ tên",
['ranklist021'] = "Tọa kỵ cấp số",
['ranklist022'] = "Thiên Ác",
['ranklist023'] = "Tìm kiếm",
['ranklist024'] = "Xin điền vào Tìm kiếm nội dung",
['ranklist025'] = "Hoán đổi",
['ranklist026'] = "Nhắc nhở: Cấp bậc, sức chiến đấu giống nhau lúc, theo kinh nghiệm cùng tương quan hệ thống thăng giai tiến độ xếp hạng.",
['ranklist027'] = "Tọa kỵ bảng",
['ranklist028'] = "Tọa kỵ bảng",
['ranklist029'] = "Tọa kỵ bảng",
}
)
