StrConfig:Add(
{
['mount3'] = 'Còn lại %s Ngày %s Giờ %s Phút %s Giây',
['mount4'] = 'Vật liệu không đủ, không cách nào thăng giai',
['mount5'] = "<font color='#29cc00'>5 Giai nhưng nuôi nấng </font>",
['mount6'] = "Đạo cụ không đủ, không cách nào tăng lên",
['mount7'] = "Tăng lên đã đạt hạn mức cao nhất",
['mount8'] = "Điều kiện không đủ, không cách nào học tập này kỹ năng",
['mount9'] = "Điều kiện không đủ, không cách nào thăng cấp này kỹ năng",
['mount10'] = "Kỹ năng đã đạt hạn mức cao nhất",
['mount11'] = "Ngân lượng không đủ, không cách nào tăng lên",
['mount12'] = "%s Cấp",
['mount13'] = "Nhưng tiến giai thành",
['mount14'] = "Trên dưới kỵ thú quá nhanh! Cẩn thận tránh eo",
['mount15'] = "Trước mắt trạng thái không thể ngồi cưỡi",
['mount16'] = "Trước mắt địa đồ không thể ngồi cưỡi",
['mount17'] = "<font color='#29cc00'> Thành công học tập kỹ năng mới </font>",
['mount18'] = "Cấp bậc đạt tới 5 Giai sau có thể sử dụng",
['mount19'] = "<font color='#d89743'> Trước mắt chúc phúc giá trị: %s</font><br/><br/><font color='#DAA520'> Chúc phúc giá trị thanh không tình trạng: </font><font color='#960000'> Chúc phúc giá trị tại mỗi ngày rạng sáng 6 Điểm về không </font><br/><font color='#DAA520'> Chúc phúc giá trị nói rõ: </font><br/> Mỗi lần chưa thể thành công tiến giai, đều đem tăng lên chúc phúc giá trị.<br/> Chúc phúc giá trị càng cao, lần sau thao tác xác suất thành công càng cao.<br/> Chúc phúc giá trị thăng đầy sau, thì lần sau thăng giai thao tác nhất định thành công </font>",
['mount20'] = 'Linh lực không đủ, không cách nào thăng giai',
['mount21'] = "Nuôi nấng thành công",
['mount22'] = "<font color='#505050'><u>%s Khỏa </u></font>",
['mount23'] = "<font color='#B86F11'>%s</font>",
['mount24'] = "Tọa kỵ %s Giai sau, nhưng tiêu hao tọa kỵ tiến giai thạch tiến giai",
['mount25'] = "<font color='#e59607' size='16'>  Linh lực thu hoạch được đường tắt </font><br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/><p><font size='14'> Từ trong tông môn thu hoạch được </font></p><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/><p><font size='14'> Từ thường ngày hoạt động, nhiệm vụ bên trong thu hoạch được </font></p>";
-- ['mount26'] = "Lần này tiến giai cần tiêu hao <br/><font color='#2f801f'>%s<br/> Ngân lượng %s</font>",
['mount26'] = "Lần này tiến giai cần tiêu hao <br/><font color='#2f801f'>%s<br/></font>",
['mount27'] = "<font color='#edbd8a'>%s</font>",
['mount28'] = "<font color='#a97a42'>%s</font>",
['mount29'] = "<font color='#2f801f'> Gấp đôi trưởng thành %s</font>",
['mount30'] = "<font color='%s' size='16'>%s</font><font color='#29cc00'>(%s Cấp )</font><font color='#960000' size='16'>( Chưa tập được )</font><br/><p><img height='3'/></p><p><img width='200' height='2' align='baseline' vspace='5' src='%s'/></br></p><font color='#d1c0a5' size='14'> Kỹ năng hiệu quả:</font><br/><font color='#ff8f43' size='14'>%s</font>",
['mount31'] = "<font color='%s' size='16'>%s</font><font color='#29cc00'>(%s Cấp )</font><font color='#32961e' size='16'>( Đã học tập )</font><br/><p><img height='3'/></p><p><img width='200' height='2' align='baseline' vspace='5' src='%s'/></br></p><font color='#d1c0a5' size='14'> Kỹ năng hiệu quả:</font><br/><font color='#ff8f43' size='14'>%s</font>",
['mount32'] = "Hoàng kim VIP Mới có thể trả về",
['mount33'] = "Ngài trước mắt tính gộp lại VIP Trả về <br/><font color='#2f801f'>%s</font><br/>%s",
['mount34'] = "Sử dụng %s Kích hoạt",
['mount35'] = "Linh thú cấp bậc không đủ, không cách nào tiến giai",
['mount36'] = "Mỗi khỏa vĩnh cửu gia tăng tọa kỵ thuộc tính: ",
['mount37'] = "Mỗi khỏa vĩnh cửu gia tăng Linh thú thuộc tính: ",
['mount38'] = "Mỗi khỏa vĩnh cửu gia tăng thần binh thuộc tính: ",
['mount39'] = "Mỗi khỏa vĩnh cửu gia tăng linh trận thuộc tính: ",
['mount40'] = "Mỗi khỏa vĩnh cửu gia tăng kỵ chiến thuộc tính: ",
['mount41'] = "Mỗi khỏa vĩnh cửu gia tăng pháp bảo thuộc tính: ",
['mount42'] = "Mỗi khỏa vĩnh cửu gia tăng ngọc bội thuộc tính: ",
['mount43'] = "Mỗi khỏa vĩnh cửu gia tăng bảo giáp thuộc tính: ",
['mount44'] = "Mỗi khỏa vĩnh cửu gia tăng cảnh giới thuộc tính: ",
['mount45'] = "Mỗi khỏa vĩnh cửu gia tăng tọa kỵ thuộc tính: ",
['Mount101'] = "<font color='#dcdcdc'> Trưởng thành giá trị đầy 5 Tinh sau, kỵ thú liền có thể thăng giai </font>",
['Mount102'] = "<font color='#00ff00'><u>%s Khỏa </u></font>",
['Mount103'] = "<font color='#cc0000'><u>%s Khỏa </u></font>",
['Mount104'] = "<font color='#2f801f'><u>%s</u></font>",
['Mount105'] = "<font color='#cc0000'><u>%s</u></font>",
['mount106'] = "<font color='#ffae00' size='16'> Trưởng thành giá trị %s</font>",
['mount107'] = "<font color='#00b7ef'>%s</font>  <font color='#2fe00d'>LV.%s</font><br/><br/><font color='#ff0000'> Chưa tập được </font>",
['mount108'] = "<font color='#00b7ef'>%s</font>  <font color='#2fe00d'>LV.%s</font><br/><br/><font color='#00ff00'> Đã học tập </font>",
['mount109'] = "<font color='#be8c44'> Điều kiện học tập: </font><br/><font color='#c8c8c8'>1, giai vị: </font><font color='#ff0000'>%s Giai ( Chưa đạt thành )</font><br/><font color='#c8c8c8'>2, cần tiêu hao đạo cụ:</font>",
['mount110'] = "<font color='#be8c44'> Điều kiện học tập: </font><br/><font color='#c8c8c8'>1, giai vị: </font><font color='#00ff00'>%s Giai ( Đã đạt thành )</font><br/><font color='#c8c8c8'>2, cần tiêu hao đạo cụ:</font>",
['mount111'] = "<font color='#00b7ef'>%s</font><br/><br/><font color='#ff0000'>%s/%s</font>",
['mount112'] = "<font color='#00b7ef'>%s</font><br/><br/><font color='#00ff00'>%s/%s</font>",
['mount113'] = "<font color='#d89743'>%s LV.%s</font>",
['mount114'] = "<font color='#d89743'> Kỹ năng mở ra điều kiện </font><br/><font color='#960000'> Kỵ thú thăng đến: %s Giai ( Chưa đạt thành )</font>",
['mount115'] = "<font color='#d89743'> Kỹ năng mở ra điều kiện </font><br/><font color='#32961e'> Kỵ thú thăng đến: %s Giai ( Đã đạt thành )</font>",
['mount116'] = "<font color='#be8c44'> Thăng cấp điều kiện: </font><br/><font color='#c8c8c8'>1, giai vị: </font><font color='#ff0000'>%s Giai ( Chưa đạt thành )</font><br/><font color='#c8c8c8'>2, cần tiêu hao đạo cụ:</font>",
['mount117'] = "<font color='#be8c44'> Thăng cấp điều kiện: </font><br/><font color='#c8c8c8'>1, giai vị: </font><font color='#00ff00'>%s Giai ( Đã đạt thành )</font><br/><font color='#c8c8c8'>2, cần tiêu hao đạo cụ:</font>",
['mount118'] = "<font color='#e59607' size='16'>%s</font><br/><p><img width='181' height='2' align='baseline' src='%s'/></p><font color='#c8c8c8'> Tọa kỵ đẳng cấp sẽ theo nhân vật chính đẳng cấp tăng lên tự động tăng lên </font><br/><font color='#c8c8c8'> Tọa kỵ đẳng cấp càng cao thì cho nhân vật chính tăng thêm thuộc tính cũng càng nhiều </font>",
['Mount119'] = "<font color='#ffc600'> Tọa kỵ </font><font color='#00ff00'>%s Giai </font><font color='#ffc600'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ffc600'> Tọa kỵ thuộc tính đan </font>",
['Mount120'] = "Linh thú <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Linh thú thuộc tính đan",
['Mount121'] = "Thần binh <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Thần binh thuộc tính đan",
['Mount122'] = "Linh trận <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Linh trận thuộc tính đan",
['Mount123'] = "Kỵ chiến <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Kỵ chiến thuộc tính đan",
['Mount124'] = "Thần linh <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Thần linh thuộc tính đan",
['Mount125'] = "Mỗi khỏa vĩnh cửu gia tăng thần linh thuộc tính: ",
['Mount126'] = "Mỗi khỏa vĩnh cửu gia tăng nguyên linh thuộc tính: ",
['Mount127'] = "Nguyên linh <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Nguyên linh thuộc tính đan",
['Mount128'] = "Mỗi khỏa vĩnh cửu gia tăng Linh thú tọa kỵ thuộc tính: ",
['Mount129'] = "Linh thú tọa kỵ <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Linh thú tọa kỵ tư chất đan",
['Mount130'] = "Tất cả thuộc tính",
['Mount131'] = "Mỗi khỏa vĩnh cửu gia tăng chiến nỏ thuộc tính: ",
['Mount132'] = "Chiến nỏ <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Chiến nỏ thuộc tính đan",
['Mount133'] = "Mỗi khỏa vĩnh cửu gia tăng linh mạch thuộc tính: ",
['Mount134'] = "Linh mạch <font color='#00ff00'>%s Giai </font> Tổng cộng nhưng nuôi nấng <font color='#00ff00'>%s Khỏa </font> Linh mạch thuộc tính đan",
['Mount135'] = '<font color="#a97a42">%s</font>)',
['Mount136'] = '<font color="#ff0000">%s</font>)',
['Mount137'] ="(%s Khỏa tinh )",
['Mount138'] ="( Bản khỏa tinh )",
['Mount139'] = "<font color='#ffc600'> Pháp bảo </font><font color='#00ff00'>%s Giai </font><font color='#ffc600'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ffc600'> Pháp bảo thuộc tính đan </font>",
['Mount140'] = "<font color='#ffc600'> Ngọc bội </font><font color='#00ff00'>%s Giai </font><font color='#ffc600'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ffc600'> Ngọc bội thuộc tính đan </font>",
['Mount141'] = "<font color='#ffc600'> Bảo giáp </font><font color='#00ff00'>%s Giai </font><font color='#ffc600'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ffc600'> Bảo giáp thuộc tính đan </font>",
['Mount142'] = "<font color='#ffc600'> Cảnh giới </font><font color='#00ff00'>%s Giai </font><font color='#ffc600'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ffc600'> Cảnh giới thuộc tính đan </font>",
['Mount200'] = "<font color='#ff9000'> Thần binh </font><font color='#00ff00'>%s Giai </font><font color='#ff9000'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ff9000'> Thần binh tư chất đan </font>",
['Mount201'] = "<font color='#ff9000'> Pháp bảo </font><font color='#00ff00'>%s Giai </font><font color='#ff9000'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ff9000'> Pháp bảo tư chất đan </font>",
['Mount202'] = "<font color='#ff9000'> Ngọc bội </font><font color='#00ff00'>%s Giai </font><font color='#ff9000'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ff9000'> Ngọc bội tư chất đan </font>",
['Mount203'] = "<font color='#ff9000'> Bảo giáp </font><font color='#00ff00'>%s Giai </font><font color='#ff9000'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ff9000'> Bảo giáp tư chất đan </font>",
['Mount204'] = "<font color='#ff9000'> Cảnh giới </font><font color='#00ff00'>%s Giai </font><font color='#ff9000'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ff9000'> Cảnh giới tư chất đan </font>",
['Mount205'] = "<font color='#ff9000'> Tọa kỵ </font><font color='#00ff00'>%s Giai </font><font color='#ff9000'> Tổng cộng nhưng nuôi nấng </font><font color='#00ff00'>%s Khỏa </font><font color='#ff9000'> Tọa kỵ tư chất đan </font>",
['Mount250'] = "Mỗi khỏa tư chất đan có thể gia tăng <font color='#00ff00'>%s%s</font> Thần binh thuộc tính <br> Trước mắt đã gia tăng thần binh thuộc tính:<font color='#00ff00'>%s%s</font>",
['Mount251'] = "Mỗi khỏa tư chất đan có thể gia tăng <font color='#00ff00'>%s%s</font> Pháp bảo thuộc tính <br> Trước mắt đã gia tăng pháp bảo thuộc tính:<font color='#00ff00'>%s%s</font>",
['Mount252'] = "Mỗi khỏa tư chất đan có thể gia tăng <font color='#00ff00'>%s%s</font> Ngọc bội thuộc tính <br> Trước mắt đã gia tăng ngọc bội thuộc tính:<font color='#00ff00'>%s%s</font>",
['Mount253'] = "Mỗi khỏa tư chất đan có thể gia tăng <font color='#00ff00'>%s%s</font> Bảo giáp thuộc tính <br> Trước mắt đã gia tăng bảo giáp thuộc tính:<font color='#00ff00'>%s%s</font>",
['Mount254'] = "Mỗi khỏa tư chất đan có thể gia tăng <font color='#00ff00'>%s%s</font> Cảnh giới thuộc tính <br> Trước mắt đã gia tăng cảnh giới thuộc tính:<font color='#00ff00'>%s%s</font>",
['Mount255'] = "Mỗi khỏa tư chất đan có thể gia tăng <font color='#00ff00'>%s%s</font> Tọa kỵ thuộc tính <br> Trước mắt đã gia tăng tọa kỵ thuộc tính:<font color='#00ff00'>%s%s</font>",
}
);
