StrConfig:Add(
{
-- Thần binh bảng
['magicWeapon001'] = 'Thần binh cấp bậc',
['magicWeapon002'] = '<font color="#e59607"> Trước mắt thần binh độ thuần thục đẳng cấp: %s<br>%s<br><font color="#e56a10"> Mỗi lần phát động <font color="#00b7ef">%s</font> Lúc, độ thuần thục đều sẽ tăng lên </font>',
['magicWeapon003'] = "Đã thăng đến cao giai nhất",
['magicWeapon004'] = "Công  Kích: %s",
['magicWeapon005'] = "Phòng  Ngự: %s",
['magicWeapon006'] = "Bạo  Kích: %s",
['magicWeapon007'] = "Sinh  Mệnh: %s",
['magicWeapon008'] = "Bạo  Tổn thương: %s",
['magicWeapon009'] = "<font color='#29cc00'> Đã đạt tới trước mắt cấp bậc tối cao độ thuần thục đẳng cấp </font>",
-- Thần binh tiến giai bảng
['magicWeapon010'] = "Tiến giai tiêu hao: ",
['magicWeapon011'] = "Ngân lượng: ",
['magicWeapon012'] = "<u><font color='%s'>%s%s Khỏa </font></u>",
-- Thần binh kỹ năng thăng cấp bảng
['magicWeapon013'] = "%s:<br><font color='#c8c8c8'>1, giai vị:<font color='%s'>%s Giai %s</font><br>2, cần tiêu hao đạo cụ:</font>",
['magicWeapon014'] = "Đạo cụ không đủ",
['magicWeapon015'] = "Thần binh cấp bậc không đủ",
['magicWeapon016'] = "Đã tập được",
['magicWeapon017'] = "Chưa tập được",
['magicWeapon018'] = "( Đã đạt thành )",
['magicWeapon019'] = "( Chưa đạt thành )",
-- Nhắc nhở tin tức
['magicWeapon020'] = "Độ thuần thục không đủ",
['magicWeapon021'] = "Ngân lượng không đủ",
['magicWeapon022'] = "Đạo cụ số lượng không đủ",
['magicWeapon023'] = "Độ thuần thục đầy sau mới có thể thăng giai",
['magicWeapon024'] = "<font color='#e59607'> Trước mắt chúc phúc giá trị: <font color='#dcdcdc'>%s</font></font><br/><font color='#e59607'> Chúc phúc giá trị thanh không tình trạng: </font><font color='#e56a10'> Chúc phúc giá trị tại mỗi ngày rạng sáng <font color='#00ff00'>6 Điểm </font> Về không </font><br/><font color='#e59607'> Chúc phúc giá trị nói rõ: </font><br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi lần chưa thể thành công tiến giai, đều đem tăng lên chúc phúc giá trị.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị càng cao, lần sau thao tác xác suất thành công càng cao.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị thăng đầy sau, thì lần sau thăng giai thao tác nhất định thành công </font>",
['magicWeapon025'] = "Trước mắt kỹ năng đã thăng đến đẳng cấp cao nhất",
['magicWeapon026'] = "Độ thuần thục: ",
['magicWeapon027'] = "Thắp sáng hạ khỏa tinh có thể gia tăng như sau thuộc tính: \n%s",
['magicWeapon028'] = "Thần binh kỹ năng",
['magicWeapon029'] = "Thăng cấp điều kiện",
['magicWeapon030'] = "Điều kiện học tập",
['magicWeapon031'] = "Thăng cấp kỹ năng",
['magicWeapon032'] = "Học tập kỹ năng",
['magicWeapon033'] = "Độ thuần thục đầy sau có thể thăng giai",
['magicWeapon034'] = "Đạo cụ không đủ, không cách nào tiến giai",
['magicWeapon035'] = "Ngân lượng không đủ, không cách nào tiến giai",
['magicWeapon036'] = "Công Kích",
['magicWeapon037'] = "Phòng Ngự",
['magicWeapon038'] = "Sinh Mệnh",
['magicWeapon039'] = "Bạo Kích",
['magicWeapon040'] = "Chính  Xác",
['magicWeapon041'] = "Bạo Tổn thương",
['magicWeapon042'] = "Phá Phòng",
['magicWeapon043'] = "Xuyên Đâm",
['magicWeapon044'] = "Kim linh <font color='%s'>%s</font>",
['magicWeapon045'] = "Mộc linh <font color='%s'>%s</font>",
['magicWeapon046'] = "Thủy linh <font color='%s'>%s</font>",
['magicWeapon047'] = "Hỏa linh <font color='%s'>%s</font>",
['magicWeapon048'] = "Thổ Linh <font color='%s'>%s</font>",
['magicWeapon049'] = "Chưa kích hoạt",
['magicWeapon050'] = "<font color='#E59607' size='16'> Thuộc tính tổng tăng thêm </font><br/>%s",
['magicWeapon051'] = "<font color='#D5B772'>%s</font>  <font color='#00ff00'>%s</font>",
['magicWeapon052'] = "Thần binh cấp bậc không đủ, không cách nào kích hoạt",
['magicWeapon053'] = "Binh Linh cấp bậc",
['magicWeapon054'] = "<font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>%s</textformat>",
['magicWeapon055'] = "<font color='%s'> Thần binh đạt tới %s Giai có thể tùy ý kích hoạt Binh Linh: %s</font>",
['magicWeapon056'] = "<font color='%s'> Trước mắt thần binh %s Giai, còn có thể tùy ý kích hoạt Binh Linh số lượng: %s</font>",
['magicWeapon057'] = "<font color='%s'> Thần binh đạt tới %s Giai, nhưng lần nữa kích hoạt Binh Linh: %s</font>",
['magicWeapon058'] = "<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thần binh <font color='#00ff00'>%s Giai </font> Nhưng kích hoạt <font color='#00ff00'>%s Cái </font> Binh Linh",
['magicWeapon059'] = "( Có được:%s)";
['magicWeapon060'] = "%s/%s";
}
)
