StrConfig:Add(
{
['beicangjie001'] = '%s',
['beicangjie002'] = '%s:%s:%s',
['beicangjie003'] = 'Lần này trong hoạt động chung thu hoạch được <font color="#00ff00">%s</font> Điểm tích lũy, xếp hạng thứ <font color="#00ff00">%s</font>, thu hoạch được:',
['beicangjie004'] = 'Tại lần này trong hoạt động chung thu hoạch được <font color="#00ff00">%s</font> Điểm tích lũy, đạt tới 7 Cấp, thu hoạch được phong thần tư cách khiêu chiến,<font color="#00ff00"> Phải chăng tiến về khiêu chiến?</font>',
['beicangjie005'] = 'Thành công chém giết phong thần thủ hộ, đem ngoài định mức thu hoạch được:',
['beicangjie006'] = 'Khiêu chiến phong thần thủ hộ thất bại, mời tăng lên chiến lực tranh thủ tại lần sau trong hoạt động khiêu chiến thành công!',
['beicangjie007'] = '<font color="#ff0000" size = "18">%s Giây </font> Sau tự động nhận lấy',
['beicangjie008'] = '<font color="#ff0000" size = "18">%s Giây </font> Sau tự động rời khỏi',
['beicangjie009'] = 'Tạm thời chưa có',
['beicangjie010'] = 'Tại lần này trong hoạt động chung thu hoạch được <font color="#00ff00">%s</font> Điểm tích lũy, xếp hạng thứ <font color="#00ff00">%s</font>, thu hoạch được:',
['beicangjie011'] = 'Bởi vì ngài điểm tích lũy đạt tới 7 Cấp, thu hoạch được phong thần tư cách khiêu chiến,<br/><font color="#00ff00"> Phải chăng tiến về khiêu chiến?</font>',
['beicangjie050'] = 'Hiện tại đã là đẳng cấp cao nhất',
['beicangjie080'] = 'Hoạt động mở ra <font color="#ff0000">10 Phút </font> Sau đem không cách nào lại tiến vào!<br/> Rời khỏi hoạt động thu hoạch được điểm tích lũy đem giảm bớt <font color="#ff0000">50%</font>.<br/> Phải chăng rời khỏi trước mắt hoạt động tràng cảnh',
['beicangjie101'] = 'LV%s',
['beicangjie102'] = 'Hiện tại điểm tích lũy: ', --adder:houxudong date:2016/7/13
['beicangjie104'] = 'Điểm tích lũy đẳng cấp: ',
['beicangjie105'] = 'Tổng tiêu diệt: ',
['beicangjie106'] = 'Hiện tại tiêu diệt: ',
['beicangjie107'] = 'Điểm tích lũy quán quân bảng: ',
['beicangjie108'] = 'Thời gian còn: ',
['beicangjie103'] = '( Lại thu hoạch được <font color="#00ff00">%s</font> Điểm tích lũy sau có thể tăng lên điểm tích lũy đẳng cấp )',
['beicangjie200'] = 'Đếm ngược: %s:%s',
['beicangjie201'] = 'BOSS Vị trí:  <font color="#d5b772">%s</font>',
['beicangjie202'] = 'BOSS Vị trí:  <font color="#d5b772">%s:%s</font>',
['beicangjie203'] = 'Tiểu quái còn:  <font color="#d5b772">%s</font>',
['beicangjie204'] = 'Tinh anh quái còn: <font color="#d5b772">%s</font>',
['beicangjie300'] = '500 Điểm tích lũy / Cái',
['beicangjie301'] = '50 Điểm tích lũy / Cái',
['beicangjie302'] = '10 Điểm tích lũy / Cái',
['beicangjie500'] = 'Đổi  Đổi',
['beicangjie600'] = 'Xếp hạng',
['beicangjie601'] = 'Tên',
['beicangjie602'] = 'Điểm tích lũy đẳng cấp',
['beicangjie603'] = 'Hiện tại điểm tích lũy',
['beicangjie604'] = 'Tiêu diệt ',
['beicangjie605'] = 'Tử vong ',
['beicangjie606'] = 'Liên trảm',
['beicangjie700'] = 'Ta điểm tích lũy: %s( Xếp hạng:%s)',
['beicangjie701'] = 'Ta điểm tích lũy: %s( Xếp hạng: Không lên bảng )',
['beicangjie800'] = "Thứ %s-%s Tên",
['beicangjie900'] = "Chiến lực tăng lên",
['beicangjie901'] = "( Tử vong phục sinh có thể gia tăng lực công kích )",
['beicangjie902'] = "( Tràng cảnh bên trong ngẫu nhiên đổi mới thu thập )",
['beicangjie903'] = "Chưa thu hoạch được",
['beicangjie904'] = "Đã thu hoạch được",
})
