StrConfig:Add(
{
['fengyao1'] = "<font color='#29cc00'><u>%s</u></font>",
['fengyao2'] = "<font color='#29cc00'><u> Quy tắc nói rõ </u></font>",
['fengyao3'] = "<font color='#29cc00'><u> Từ bỏ nhiệm vụ </u></font>",
['fengyao4'] = "<font color='#29cc00'><u> Thế giới xin giúp đỡ </u></font>",
['fengyao5'] = "Ngân lượng không đủ, không cách nào đổi mới",
['fengyao005'] = "Đã nhận lấy",
['fengyao006'] = "Nhận lấy",
['fengyao007'] = "Đã hoàn thành",
['fengyao008'] = "Từ bỏ",
['fengyao6'] = "Nguyên bảo không đủ, không cách nào thu hoạch",
['fengyao7'] = "Nhiệm vụ trước mặt đã hoàn thành, xin đợi đến lần sau đổi mới sau tiếp tục",
['fengyao8'] = "Hôm nay hoàn thành số lần đã đạt hạn mức cao nhất",
['fengyao9'] = [[<font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Đồ ma nhiệm vụ toàn bộ ngày mở ra, xác nhận nhiệm vụ sau có thể tiến hành đổi mới, trước 10 Lần nhiệm vụ nhưng ngoài định mức thu hoạch được đại lượng kinh nghiệm ban thưởng.<img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Đồ ma nhiệm vụ chia làm <font color='#eeeeee'> Bạch </font>, <font color='#22c50b'> Lục </font>, <font color='#00b7ef'> Lam </font>, <font color='#b400ff'> Tử </font>, <font color='#f9680c'> Cam </font><font size='14'> Năm loại nhan sắc, đối ứng năm loại khác biệt phẩm chất.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Hoàn thành màu trắng đồ ma thu hoạch được 5 Điểm tích lũy, lục sắc thu hoạch được 10 Điểm tích lũy, màu lam thu hoạch được 15 Điểm tích lũy, tử sắc thu hoạch được 20 Điểm tích lũy, màu cam thu hoạch được 30 Điểm tích lũy.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Đạt tới điểm tích lũy yêu cầu nhưng nhận lấy đối ứng điểm tích lũy ban thưởng.
</textformat>]],
['fengyao10'] = "Mời lựa chọn đồ ma độ khó",
['fengyao11'] = "Điểm tích lũy không đủ, không cách nào lĩnh thưởng",
['fengyao12'] = "Vòng sau đồ ma đổi mới còn thừa thời gian:<font color='#00FF00'>%s:%s</font>",
['fengyao13'] = "<font color='#e59607' size='14'> Nhận lấy điều kiện : <font color='#dcdcdc'> Điểm tích lũy đạt tới %s</font></font><br/><p><img height='3'/></p><p><img width='200' height='2' align='baseline' vspace='5' src='%s'/></br></p><font color='#e59607' size='14'> Ban thưởng vật phẩm:</font><br/>%s",
['fengyao14'] = "<font color='#ffcc33' size='16'> Nhiệm vụ tin tức </font><br/><p><img height='2'/></p><p><img width='250' height='2' align='baseline' vspace='5' src='%s'/></p><font color='#e59607' size='14'> Ban thưởng phẩm chất: </font><font color='#ff8f43' size='14'>%s</font><br/><font color='#e59607' size='14'> Nhiệm vụ điểm tích lũy: </font><font color='%s' size='14'>%s</font><br/><font color='#e59607' size='14'> Đồ ma ban thưởng: </font><font color='#d5b772' size='14'> Kinh nghiệm <font color='#00ff00'>%s</font></font><font color='#d5b772' size='14'> Ngân lượng <font color='#00ff00'>%s</font></font><br/><font color='#d5b772' size='14'>",
['fengyao15'] = "Đổi mới thành công",
['fengyao16'] = "Xách phẩm thành công",
['fengyao17'] = "Mời trước từ bỏ nhiệm vụ",
['fengyao18'] = "Tốn hao <font color='#00ff00'>%s Ngân lượng </font> Ngẫu nhiên đổi mới đồ ma nhiệm vụ",
['fengyao19'] = "Tốn hao <font color='#00ff00'>%s Nguyên bảo </font>( Ưu tiên sử dụng buộc nguyên ) Trực tiếp đem nhiệm vụ đổi mới đến tối cao phẩm chất",
['fengyao20'] = "Điểm kích tiến về quái vật sở tại địa",
['fengyao21'] = "<font color='%s'><u>%s</u></font>",
['fengyao22'] = "Đã vì tối cao phẩm chất, không cách nào đổi mới.",
['fengyao23'] = "Hiện tại <font color='#f9680c' size='16'> Truyền thuyết phẩm chất </font> Đã vì tối cao phẩm chất nhiệm vụ, phải chăng xác nhận đổi mới?",
['fengyao24'] = "%s Chuẩn bị tiến về %s Đánh giết đồ ma quái %s<font color='#ffffff'>%s</font>, hướng xác nhận này đồ ma nhiệm vụ cao thủ xin giúp đỡ, cộng đồng đánh giết hoàn thành!",
['fengyao25'] = "Hiện tại treo thưởng nhiệm vụ đã hoàn thành <br/><font color='#29cc00'> Điểm kích tiến về nhận lấy ban thưởng </font>",
['fengyao26'] = "Đem tiêu hao %s Ngân lượng nhận lấy %s Lần ban thưởng",
['fengyao27'] = "Đem tiêu hao %s Nguyên bảo nhận lấy %s Lần ban thưởng",
['fengyao0027'] = "%s Điểm tích lũy",
['fengyao28'] = "Ngân lượng không đủ",
['fengyao29'] = "Nguyên bảo không đủ",
['fengyao30'] = "Tiêu hao %s Ngân lượng nhận lấy 1.2 Lần ban thưởng",
['fengyao31'] = "Tiêu hao %s Nguyên bảo nhận lấy 1.5 Lần ban thưởng",
['fengyao32'] = "Hiện tại treo thưởng nhiệm vụ đã đổi mới <br/><font color='#29cc00'> Điểm kích tiến về nhận lấy nhiệm vụ </font>",
['fengyao33'] = "Hạ sóng đổi mới thời gian: Ngày mai %s:%s",
['fengyao34'] = "Hiện tại hoạt động không cách nào tiến về",
['fengyao35'] = "Đã đổi mới vì %s",
['fengyao36'] = "Ngài trước mắt chỗ nhận lấy treo thưởng nhiệm vụ so sánh khó, tranh thủ thời gian tìm <br/> Tìm bằng hữu cùng một chỗ tổ đội để hoàn thành!",
['fengyao37'] = "Hiện tại đã vì phẩm chất cao, phải chăng xác nhận đổi mới",
['fengyao38'] = "<font color='d905ff'>%s</font>",
['fengyao39'] = "Hôm nay đã hoàn thành",
['fengyao40'] = "Hôm nay đã kết thúc",
['fengyao41'] = "Ba lô đã đủ, không cách nào nhận lấy",
['fengyao42'] = "Nguyên bảo không đủ, không cách nào đổi mới",
['fengyao43'] = [[<font color='#a17033' size='16'> Đổi mới điều kiện:%s</font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/><font color='#d5b772'> Đẳng cấp đạt tới </font>%s<font color='#d5b772'> Hoặc là </font>%s<font color='#d5b772'> Tiêu hao </font>%s Nhưng lập tức đổi mới <img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/><font color='#d5b772'> Đẳng cấp đạt tới </font>%s Có thể miễn phí đổi mới.
</textformat>]],
['fengyao44'] = "Điều kiện không đủ, không cách nào đổi mới",
['fengyao45'] = "Mỗi 10 Phút nhưng gửi đi một lần!",
['fengyao100'] = "<font color='#eeeeee' size='14'> Phổ thông (70% Kinh nghiệm ban thưởng )</font>",
['fengyao101'] = "<font color='#22c50b' size='14'> Ưu lương (90% Kinh nghiệm ban thưởng )</font>",
['fengyao102'] = "<font color='#00b7ef' size='14'> Tinh anh (100% Kinh nghiệm ban thưởng )</font>",
['fengyao104'] = "<font color='#b400ff' size='14'> Sử thi (120% Kinh nghiệm ban thưởng )</font>",
['fengyao105'] = "<font color='#f9680c' size='14'> Truyền thuyết (180% Kinh nghiệm ban thưởng )</font>",
['fengyao200'] = "#eeeeee",
['fengyao201'] = "#22c50b",
['fengyao202'] = "#00b7ef",
['fengyao204'] = "#b400ff",
['fengyao205'] = "#f9680c",
['fengyao210'] = "Phổ thông",
['fengyao211'] = "Ưu lương",
['fengyao212'] = "Tinh anh",
['fengyao214'] = "Sử thi",
['fengyao215'] = "Truyền thuyết",
['fengyao301'] = "Cấp",
['fengyao302'] = "Nguyên bảo",
['fengyao303'] = "Mục tiêu:<font color='#fefefe'> Đánh bại </font><u><font color='#00ff00'> Tùy ý quái </font></u><font color='#fefefe'>(%s/%s)</font>",
['fengyao304'] = "%s",
['fengyao305'] = "Nhận lấy ban thưởng",
['fengyao306'] = "<font color='#e59607' size='14'> Nhận lấy điều kiện:<font color='#dcdcdc'> Điểm tích lũy đạt tới %s</font></font>",
['fengyao307'] = "Ban thưởng vật phẩm:",
['fengyao308'] = "Hoàn thành ban thưởng:",
['fengyao309'] = "Tổng số lần: Vô hạn lần   Đã hoàn thành chém yêu đồ ma <font color='#00FF00'>%s</font> Lần",
['fengyao310'] = "<font color='#ae8352'> Tích Phân: </font><font color='#ffa527'>%s</font><br/><font color='#ae8352'> Trải qua Nghiệm: </font><font color='#00ff00'>%s</font><br/><font color='#ae8352'> Ngân Hai: </font><font color='#00ff00'>%s</font>",
['fengyao311'] = "Tiêu hao ngân lượng nhận lấy đồ ma nhiệm vụ, nhận lấy nhiệm vụ phẩm chất ngẫu nhiên",
['fengyao312'] = "Tiêu hao Nguyên bảo nhận lấy đồ ma nhiệm vụ, nhận lấy nhiệm vụ cố định vì truyền thuyết phẩm chất",
['fengyao313'] = "1. Đánh giết tùy ý quái có thể hoàn thành đồ ma nhiệm vụ <br/>2. Ngân lượng nhận lấy nhưng ngẫu nhiên nhiệm vụ phẩm chất, Nguyên bảo nhận lấy cố định truyền thuyết phẩm chất, phẩm chất càng cao ban thưởng càng phong phú",
['fengyao314'] = "<u> Xem xét đồ ma nhiệm vụ </u>",
['fengyao315'] = "Đánh bại tùy ý quái",
}
);
