UIStrConfig:Add(
{
['fengyao1'] = 'Ngân lượng nhận lấy',
['fengyao2'] = 'Nguyên bảo đổi mới',
['fengyao3'] = 'Nhận lấy nhiệm vụ',
['fengyao4'] = 'Từ bỏ nhiệm vụ',
['fengyao5'] = 'Nhận lấy',
['fengyao6'] = 'Lượt này đã hoàn thành',
['fengyao7'] = 'Đồ ma',
['fengyao8'] = 'Điểm tích lũy ban thưởng',
['fengyao9'] = 'Lượt này đã hoàn thành',
['fengyao10'] = 'Ngân lượng đổi mới',
['fengyao11'] = 'Nhận lấy ban thưởng',
['fengyao12'] = 'Gấp đôi nhận lấy',
['fengyao13'] = 'Gấp ba nhận lấy',
['fengyao14'] = 'Nhắc nhở',
['fengyao15'] = 'Không nhắc nhở',
['fengyao16'] = 'Xác định',
['fengyao17'] = 'Hủy bỏ',
['fengyao18'] = 'Đồ ma',
['fengyao19'] = 'Nhưng xác nhận',
['fengyao20'] = 'Đồ ma ban thưởng',
['fengyao21'] = 'Hải lượng kinh nghiệm, chủ yếu thăng cấp đường tắt',
['fengyao22'] = '<u> Tiến về </u>',
['fengyao23'] = '10-22 Điểm mỗi nửa điểm lúc đổi mới nhiệm vụ',
['fengyao24'] = "<u> Từ bỏ nhiệm vụ </u>",
['fengyao25'] = "<u> Thế giới xin giúp đỡ </u>",
['fengyao26'] = '<u> Trạng thái đổi mới </u>',
['fengyao27'] = 'Nguyên bảo nhận lấy',
['fengyao28'] = 'Xem xét đồ ma nhiệm vụ',
}
)
