StrConfig:Add(
{
['tianshen01'] ='<font color="#00b0f0"> Sau khi đột phá, tăng lên  thuộc tính, tăng lên đẳng cấp hạn mức cao nhất </font>',
['tianshen02'] ='<font color="#de9afa"> Sau khi đột phá, tăng lên  thuộc tính, tăng lên đẳng cấp hạn mức cao nhất </font>',
['tianshen03'] ='<font color="#ffc000"> Sau khi đột phá, tăng lên  thuộc tính, tăng lên đẳng cấp hạn mức cao nhất </font>',
['tianshen31'] ='<font color="#00b0f0">( Tư chất càng cao, cấp thuộc tính càng cao )</font>',
['tianshen32'] ='<font color="#de9afa">( Tư chất càng cao, cấp thuộc tính càng cao )</font>',
['tianshen33'] ='<font color="#ffc000">( Tư chất càng cao, cấp thuộc tính càng cao )</font>',
['tianshen61'] = '<font color="#e7d6b5">%s<font color="#00b0f0"> lv.%s</font>',
['tianshen62'] = '<font color="#e7d6b5">%s<font color="#de9afa"> lv.%s</font>',
['tianshen63'] = '<font color="#e7d6b5">%s<font color="#ffc000"> lv.%s</font>',
['tianshen001'] = 'Kích hoạt thiên thần',
['tianshen002'] = 'Tự Động',
['tianshen003'] = "Tăng Cấp Thiên Thần",
['tianshen004'] = "Tăng cấp tiêu hao: ",
['tianshen005'] = "<font color='#FFCC33'> Cấp nhưng kích hoạt </font>",
['tianshen006'] = "<font color='%s'> Công  Kích: </font> <font color='%s'>%s</font>",
['tianshen007'] = "<font color='%s'> Phòng  Ngự: </font> <font color='%s'>%s</font>",
['tianshen008'] = "<font color='%s'> Sinh  Mệnh: </font> <font color='%s'>%s</font>",
['tianshen009'] = "<font color='%s'> Chính  Xác: </font> <font color='%s'>%s</font>",
['tianshen010'] = "<font color='%s'> Né  Tránh: </font> <font color='%s'>%s</font>",
['tianshen011'] = "<font color='%s'> Bạo  Kích: </font> <font color='%s'>%s</font>",
['tianshen012'] = "<font color='%s'> Sức  Bền: </font> <font color='%s'>%s</font>",
['tianshen014'] = "Đạo cụ không đủ, không thể kích hoạt ",
['tianshen016'] = "Cấp bậc chưa đủ, %s Cấp nhưng kích hoạt!",
['tianshen017'] = "%s Cấp",
['tianshen020'] = "<u><font color='%s'>%sX%s</font></u>",
['tianshen021'] ="Thiên thần phụ thể",
['tianshen022'] = '<font color="#00ff00">%s</font>',
['tianshen023'] = '<font color="#ff0000">%s</font>',
['tianshen024'] = "<u><font color='%s'>%s</font></u>",
['tianshen025'] = "%s Sau mở ra",
['tianshen026'] ="Thiên thần phụ thể bên trong không thể hoán đổi biến thân",
['tianshen027'] = "Click mở ",
['tianshen028'] = 'Chọn Thiên thần phụ thể',
['tianshen031'] ='Màu lam thiên thần',
['tianshen032'] ='Màu tím thiên thần',
['tianshen033'] ='Màu cam thiên thần',
['tianshen034'] ='<font color="#ff0000"> Chưa kích hoạt </font>',
['tianshen035'] ='Thăng đến %s Tinh giải tỏa này thuộc tính',
['tianshen036'] = '<font color="#e7d6b5">%s<font color="#00ff00"> lv.%s</font>',
['tianshen037'] = '<font color="#e7d6b5">%s/%s</font>',
['tianshen038'] = "%s Giây sau tự động đóng",
['tianshen039'] ='%s Tinh',
['tianshen040'] = "<font color='%s'>%s)</font>",
['tianshen041'] ='<font color="#666666">%s</font>',
['tianshen042'] ='<font color="#0066FF">( Tư chất càng cao, thăng cấp thuộc tính càng cao )</font>',
['tianshen043'] ='Chưa mở ra',
['tianshen044'] ="Trước mắt điểm nộ khí số:%s/%s<br/> <br/> Điểm nộ khí càng cao, thiên thần kỹ năng hiệu quả càng mạnh <br/> <br/> 2 Nộ khí nhưng phát động phổ thông kỹ năng <br/> 4 Nộ khí nhưng phát động cao cấp kỹ năng",
['tianshen045'] = "<u><font color='%s'>%s X%s</font></u>",
['tianshen046'] ='<font color="%s">%s Cấp </font>',
['tianshen047'] ="<font color='%s'> Sau khi đột phá, tăng lên trên diện rộng thuộc tính, tăng lên đẳng cấp hạn mức cao nhất </font>",
['tianshen048'] = [[<font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Kích hoạt thiên thần sau có thể đạt được  thiên thần thuộc tính tăng thêm.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vô luận thiên thần phải chăng trợ chiến, thiên thần chiến lực đều sẽ vĩnh cửu kèm theo tại nhân vật trên thân.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Kích hoạt sau thiên thần có thể sử dụng thiên thần trợ chiến.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thiên thần trợ chiến sau nhưng phóng thích cường lực thiên thần kỹ năng
</textformat>]],
['tianshen0001'] ='<font color="#00b0f0">%s</font>',
['tianshen0002'] ='<font color="#de9afa">%s</font>',
['tianshen0003'] ='<font color="#ffc000">%s</font>',
['tianshen0004'] = "%s Thiên thần",
}
)
