UIStrConfig:Add(
{
['uarena101'] = "Sân thi đấu",
['uarena102'] = "Biệt danh: ",
['uarena103'] = "Vinh dự: ",
['uarena104'] = "Hôm nay đã khiêu chiến:",
['uarena105'] = "Thời gian chờ: ",
['uarena106'] = "Bất Bại: ",
['uarena107'] = "Lực chiến của ngươi: ",
['uarena108'] = "Thưởng xếp hạng",
['uarena109'] = "Shop Vinh Dự",
['uarena110'] = "Mỗi ngày 0 Điểm kết toán xếp hạng ban thưởng, hạng thi đấu càng lớn, ban thưởng càng cao",
['uarena111'] = "Ngân lượng: ",
['uarena112'] = "Thi đấu chiến báo",
['uarena113'] = "Lực Chiến: ",
['uarena114'] = "Đẳng cấp: ",
['uarena115'] = "Thắng lợi",
['uarena116'] = "Hạng đã thăng đến",
['uarena117'] = "Thưởng nhận được",
['uarena118'] = "Kinh nghiệm",
['uarena119'] = "Thất bại",
['uarena120'] = "Hạng của ngươi không thay đổi",
['uarena122'] = "Ba hạng đầu",
['uarena123'] = "Ta xếp hạng: ",
-- 2 Cấp giao diện
['ua201'] = "Xếp hạng ban thưởng",
['ua202'] = "Thứ Tự Thưởng Xếp Hạng",
['ua203'] = "Xếp Hạng: ",
['ua204'] = "Thưởng XH: ",
['ua205'] = "Thưởng thứ hạng là chỉ tại 0 Điểm đổi mới nhận lấy ban thưởng lúc ngài xếp hạng, khả năng cùng ngài trước mắt xếp hạng khác biệt",
['ua206'] = "Tổng thưởng",
['ua207'] = "Nhận thưởng",
['ua208'] = "Thưởng lần sau:",
['ua209'] = "Tổng thưởng hôm nay: ",
['ua210'] = "",
-- skinfo
['ua301'] = "Chiến báo",
--- Chiến đấu kết thúc
['zdjx001'] = "Thoát",
['zdjx002'] = "Thưởng nhận được: ",
['zdjx003'] = "Kinh nghiệm: ",
['zdjx004'] = "Vinh dự: ",
}
)
