UIStrConfig:Add(
{
['cave1'] = 'BOSS:',
['cave2'] = 'Đổi mới:',
['cave3'] = 'BOSS rớt:',
['cave4'] = 'Quái rớt:',
['cave5'] = 'Cày đồ bí cảnh mỗi ngày có thẻ nhận được vật phẩm giá trị, đề nghị sử dụng kiêu căng bảo suất thời gian',
['cave6'] = 'Thoát',
['cave7'] = 'Đã đổi mới',
['cave10'] = 'BOSS Bối cảnh',
['cave11'] = 'Chỗ tràng cảnh: ',
['cave12'] = 'Có tỉ lệ khá thấp: ',
['cave15'] = 'Theo dõi phó bản',
['cave16'] = 'Cày đồ bí cảnh',
['cave17'] = 'Tiến Về',
['cave18'] = 'Bắt đầu cày đồ',
['cave20'] = '</font><font color="#00ff00">Cấp %s trở lên  </font>',
['cave21'] = '</font><font color="#00ff00"> Toàn bộ ngày </font>',
['cave22'] = '<u> Mô tả </u>',
['cave25'] = 'Bản tầng tin tức',
['cave26'] = 'Nhận được vật phẩm',
['cave27'] = 'Treo máy',
['cave28'] = 'Điểm thí luyện:',
--BOSS Đổi mới nhắc nhở
['cave100'] = 'Cày đồ bí cảnh BOSS',
['cave101'] = 'Rớt trang bị tốt cùng vật liệu quý',
['cave102'] = 'Rơi xuống bảo vật',
['cave103'] = '<u> Tiến về </u>',
['cave200'] = 'BOSS rớt trang bị, tiểu quái 150% Exp, tự do PK',
['cave201'] = 'BOSS rớt trang bị, tiểu quái 150% Exp, tự do PK<br/><font color="#29cc00"> Tỷ lệ gấp bội </font>',
['cave501'] = '<u> Tiến về </u>',
['cave502'] = 'Khu vực an toàn kinh nghiệm *1 Lần',
['cave503'] = 'Không phải khu vực an toàn kinh nghiệm *1.5 Lần',
['cave600'] = '( Khu tự do PK )',
['cave700'] = 'Tiến Về',
['cave701'] = 'Sử dụng',
-- Trang ký tin tức
['cave800'] = 'Tin Tức',
['cave801'] = 'X.H BOSS',
}
)
