StrConfig:Add(
{
['jewellery1'] = "<font color='#ff0000'> Nhân vật đẳng cấp đạt tới %d Cấp lúc giải tỏa <</font>",
['jewellery2'] = "<font color='#0000ff'>( %d%)</font>",
['jewellery3'] = "<font color='#ff0000'> Đạo cụ không đủ, không cách nào nhắc nhở </font>",
['jewellery4'] = "Tiến về đánh giết" ,
['jewellery6'] = "<br>",
['jewellery7'] = "<font color='#e59607'> Thuộc tính tổng tăng thêm: </font>",
['jewellery8'] = "Đã thu hoạch được thuộc tính tăng thêm: ",
['jewellery9'] = "Thuộc tính tăng thêm tỉ lệ phần trăm: ",
['jewellery006'] = "Công Kích:",
['jewellery007'] = "Phòng Ngự:",
['jewellery008'] = "Sinh Mệnh:",
['jewellery0021'] = "( %s%%)",
['jewellery12'] = "/",
['jewellery15'] = "Toàn bộ thuộc tính %s",
['jewellery17'] = "<font color='#ff0000'> Chưa khải linh </font>",
['jewellery18'] = "<font color='#00ff00'> Đã khải linh </font>",
['jewellery19'] = "<font color='#dcdcdc'> Mỗi lần tăng lên thu thập tiến độ, cũng sẽ tăng thêm thuộc tính giá trị </font>",
['jewellery20'] = "Nên trân bảo chưa thu hoạch được thuộc tính tăng thêm",
['jewellery21'] = "Đã đưa ra",
['jewellery22'] = "Đưa ra",
['jewellery25'] = "Thu thập tiến độ",
['jewellery30'] = "Điểm kích đưa ra nút bấm, có thể tiến hành trân bảo khải linh",
['jewellery50'] = "<font color='#d5b772'> Công kích:</font><font color='#00ff00'> %s</font>",
['jewellery51'] = "<font color='#d5b772'> Phòng ngự:</font><font color='#00ff00'> %s</font>",
['jewellery52'] = "<font color='#d5b772'> Sinh mệnh:</font><font color='#00ff00'> %s</font>",
['jewellery53'] = "Chính xác:<font color='#29CC00'> %s</font>",
['jewellery54'] = "Né tránh:<font color='#29CC00'> %s</font>",
['jewellery55'] = "Bạo kích:<font color='#29CC00'> %s</font>",
['jewellery70'] = "Chưa thu hoạch được bất luận cái gì tăng thêm, đưa ra trân bảo đạo cụ có thể đạt được  thuộc tính tăng thêm.",
['jewellery56'] = "<font color='#29CC00'>( %s%%)</font>",
['jewellery100'] = " %s",
['jewellery101'] = "<font color='#ff0022'>",
['jewellery102'] = "</font>",
['jewellery105'] = "<font color='#ffffff'>%s/%s</font>",
['jewellery106'] = "%s",
['jewellery109'] = "<font color='#7f7f7f'>%s</font>",
['jewellery110'] = "Hiện tại số lượng: <font color='#2fe00d'>%s</font>",
['jewellery111'] = "<font color='#dcdcdc'> Đưa ra </font><font color='%s'>(%s)</font>",
['jewellery151'] = "Cần thiết tiêu hao: ",
['jewellery152'] = "Thu thập đủ sau có thể đạt được  thuộc tính tăng thêm: ",
['jewellery153'] = "Chưa khải linh",
['jewellery154'] = "Đã khải linh",
['jewellery155'] = "Tiến độ: <font color='#2fe00d'>%s/%s</font>",
['jewellery156'] = "Đưa ra <font color='#2fe00d'>(%s)</font>",
['jewellery157'] = "Đưa ra <font color='#cc0000'>(%s)</font>",
['jewellery250'] = "Đạo cụ không đủ, không cách nào đưa ra",
['jewellery251'] = "Hoàn mỹ độ đã đủ",
['jewellery500'] = "Hiện tại tràng cảnh không cách nào truyền tống",
['jewellery555'] = "( Toàn bộ thắp sáng có thể lấy được ngoài định mức thuộc tính tăng thêm %s%%)",
['jewellery666'] = "Hiện tại trân bảo chưa mở ra",
['jewellery700'] = "<u>%s Khỏa </u>",
}
)
