StrConfig:Add(
{
['autoBattle01'] = 'Khôi phục thiết lập ( Thiết trí sau tự động có hiệu lực )',
['autoBattle02'] = 'HP',
['autoBattle03'] = 'Khoảng cách dùng thuốc',
['autoBattle04'] = 'Giây',
['autoBattle05'] = 'MP',
['autoBattle06'] = 'Thiếp lập chiến đấu ( Tự động lúc chiến đấu có hiệu lực )',
['autoBattle07'] = 'Nhân vật tự động dùng kỹ năng, lúc trước về sau phóng thích. Không thiết trí kỹ năng ngầm thừa nhận phổ công',
['autoBattle08'] = 'Phổ thông kỹ năng',
['autoBattle09'] = 'Kỹ năng đặc thù',
['autoBattle10'] = 'Tự động tìm quái bán kính',
['autoBattle11'] = 'Gạo',
['autoBattle12'] = 'Nhặt thiết trí ( Tự động lúc chiến đấu có hiệu lực )',
['autoBattle13'] = 'Trang bị',
['autoBattle14'] = 'Bắt đầu treo máy Phím tắt: Z',
['autoBattle15'] = 'Lớn đến nhỏ',
['autoBattle16'] = 'Nhỏ đến lớn',
['autoBattle17'] = 'Toàn bộ nghề',
['autoBattle18'] = 'Toàn bộ đẳng cấp',
['autoBattle19'] = 'Lớn hơn 20 Cấp',
['autoBattle20'] = 'Lớn hơn 40 Cấp',
['autoBattle21'] = 'Lớn hơn 60 Cấp',
['autoBattle22'] = 'Lớn hơn 80 Cấp',
['autoBattle24'] = 'Toàn bộ phẩm chất',
['autoBattle31'] = "Thiết lập chưa lưu, ngươi có muốn lưu?",
['autoBattle32'] = 'Bảo tồn',
['autoBattle33'] = 'Trực tiếp',
['autoBattle34'] = "<font color='#d1c0a5'> Nhắc nhở: </font> Nhưng tại <font color='#29cc00'><a href='asfunction:hrefevent'><u> Thiết lập treo máy </u></a></font> sẽ tự động hủy bỏ mua sắm",
['autoBattle35'] = "Ngươi tự động treo máy tự động mua <font color='#F9680C'>1 Tổ </font><font color='#29cc00'>%s </font> Chung tiêu hao <font color='#29cc00'>%s </font> Ngân lượng",
['autoBattle36'] = "Mở treo máy",
['autoBattle37'] = "Hủy bỏ treo máy",
['autoBattle38'] = "Tự động chiến đấu không thể sử dụng liên tục kỹ",
['autoBattle39'] = "Tự động chiến đấu không thể sử dụng linh trận kỹ năng",
['autoBattle100'] = "Toàn bộ cấp bậc",
['autoBattle101'] = "Lớn hơn 1 Giai",
['autoBattle102'] = "Lớn hơn 2 Giai",
['autoBattle103'] = "Lớn hơn 3 Giai",
['autoBattle104'] = "Lớn hơn 4 Giai",
['autoBattle105'] = "Lớn hơn 5 Giai",
['autoBattle106'] = "Lớn hơn 6 Giai",
['autoBattle107'] = "Lớn hơn 7 Giai",
['autoBattle108'] = "Lớn hơn 8 Giai",
['autoBattle109'] = "Lớn hơn 9 Giai",
---test Gm
['autoBattle110'] = "createitem",
['autoBattle111'] = "levelup",
['autoBattle112'] = "dailyrefresh",
['autoBattle113'] = "activit",
['autoBattle114'] = "addpoint",
}
);
