StrConfig:Add(
{
['friend101'] = "Đẳng cấp: Lv.%s",
['friend102'] = "Trong ba ngày chưa đăng lục",
['friend103'] = "Trong ba ngày đăng ký qua",
['friend104'] = "Nhất định phải xóa bỏ hảo hữu a?",
['friend105'] = "Nhất định phải đem [%s] Gia nhập sổ đen a?",
['friend106'] = "Nên người chơi là của ngài hảo hữu, nhất định phải đem [%s] Gia nhập sổ đen a?",
['friend107'] = "Nhất định phải đem [%s] Gỡ ra sổ đen?",
['friend108'] = "%s Đã là hảo hữu của ngươi",
['friend109'] = "%s Đã ở ngươi sổ đen",
['friend110'] = "Xin điền vào người chơi biệt danh",
['friend111'] = "Hảo hữu thỉnh cầu đã phát ra",
['friend112'] = "Không thể tăng thêm mình làm hảo hữu",
['friend201'] = "Không hảo hữu kết quả tìm kiếm",
['friend202'] = "<font color='#d89743'> Kinh nghiệm tăng thêm </font> <font color='#29cc00'> %s%%</font><br/><font color='#d89743'> Ngân lượng tăng thêm </font> <font color='#29cc00'> %s%%</font>",
['friend203'] = "Tổ đội tăng thêm: Hảo hữu độ thân mật đạt tới nhất định cấp bậc lúc, cùng hảo hữu tổ đội nhưng phát động thuộc tính tăng thêm.<br/> Độ thân mật thu hoạch được: Hảo hữu ở giữa có thể thông qua tổ đội giết quái, hỗ tặng hoa tươi chờ gia tăng độ thân mật.",
['friend204'] = "[%s]",
['friend205'] = "[%s]%s",
['friend206'] = "Ngài từng bị nên người chơi đánh bại:%s Lần",
['friend301'] = 'Gần nhất người liên hệ [%s/%s]',
['friend302'] = 'Hảo hữu của ta [%s/%s]',
['friend303'] = 'Cừu nhân của ta [%s/%s]',
['friend304'] = 'Sổ đen [%s/%s]',
['friend401'] = "Xem",
['friend402'] = "Nói chuyện",
['friend403'] = "Tạo đội ngũ",
['friend404'] = "Xin về chỗ",
['friend405'] = "Mời về chỗ",
['friend406'] = "Mời nhập bang",
['friend407'] = "Xin nhập bang",
['friend408'] = "Thêm hảo hữu",
['friend409'] = "Xóa hảo hữu",
['friend410'] = "Phục chế danh tự",
['friend411'] = "Dời ra khỏi hàng biểu",
['friend412'] = "Xóa cừu hận",
['friend413'] = "Thêm sổ đen",
['friend414'] = "Dời nổi danh đơn",
['friend501'] = "%s Giây sau tự động đóng",
['friend502'] = "Hảo hữu của ngươi đã thăng: %s Cấp. Ngươi thu hoạch được: ",
}
)
