StrConfig:Add(
{
['registerReward1'] = 'Offline: %s Giờ %s Phút %s Giây',
['registerReward2'] = 'Kích hoạt không thành công',
['registerReward3'] = 'Mã đã sử dụng',
['registerReward4'] = 'Đã nhận quà này rồi',
['registerReward5'] = 'Kích hoạt sai lầm',
['registerReward6'] = "<font color='#29cc00'> Kích hoạt hoàng kim VIP  nhận </font>",-- Lục sắc
['registerReward7'] = "<font color='#cc0000'> Kích hoạt hoàng kim VIP  nhận </font>",-- Màu đỏ
['registerReward8'] = "<font color='#29cc00'> Kích hoạt kim cương VIP  nhận </font>",
['registerReward9'] = "<font color='#cc0000'> Kích hoạt kim cương VIP  nhận </font>",
['registerReward10'] = 'Cách bảo rương lần sau mở ra còn có %s:%s:%s',
['registerReward11'] = 'Chưa kích hoạt hoàng kim VIP, không cách nào nhận',
['registerReward111'] = 'Chưa kích hoạt kim cương VIP, không cách nào nhận',
['registerReward12'] = ' Gói quà mã đã bị sử dụng',
['registerReward13'] = "Có thể nhận quà <br/><font color='#29cc00'> Nhấp chuột nhận </font>",
['registerReward14'] = "<font color='#00ff00'>%s Cấp gói quà </font>",
['registerReward15'] = 'Nguyên bảo không đủ, không cách nào nhận',
['registerReward16'] = "Phải chăng tiêu hao <font color='#00ff00'>%s Nguyên bảo </font> Nhận quà offline",
['registerReward30'] = '<font color ="#ffab32">%s</font>',
['registerReward51'] = 'Tổng số lần báo danh tháng này:',
['registerReward52'] = "%s",
['registerReward53'] = "Bạn chưa khai thông VIP",
['registerReward54'] = "Báo danh %s Lần",
['registerReward55'] = "Ký tên",
['registerReward56'] = "Đã Báo danh",
['registerReward100'] = "Bạn VIP Cấp bậc chưa đủ, không cách nào sử dụng chức năng này",
['registerReward101'] = "Có thể bổ ký số lần đã đạt hạn mức cao nhất, không cách nào bổ ký",
['registerReward102'] = " sớm Báo danh số lần đã đạt hạn mức cao nhất, không cách nào sớm Báo danh",
['registerReward500'] = " <font color ='#ff8f43'> Sớm Báo danh </font>",
['registerReward501'] = " <font color='#D1C0A5'> Ta VIP Đẳng cấp:</font> <font color='#29cc00'>%s</font>",
['registerReward502'] = " <font color='#D1C0A5'> Tháng này còn thừa sớm Báo danh số ngày:</font> <font color='#29cc00'>%s</font>",
['registerReward503'] = "<font color='#c8c8c8'>  sớm Báo danh </font><font color='#29cc00'>%s ngày </font>",
['registerReward504'] = " <font color='#ff8f43'> Kim cương VIP%s</font>",
['registerReward600'] = " <font color ='#ff8f43'> Bổ ký </font>",
['registerReward601'] = " <font color='#D1C0A5'> Ta VIP Đẳng cấp:</font> <font color='#29cc00'>%s</font>",
['registerReward602'] = " <font color='#D1C0A5'> Tháng này còn thừa bổ ký số ngày:</font> <font color='#29cc00'>%s</font>",
['registerReward603'] = "<font color='#c8c8c8'> Có thể bổ ký </font><font color='#29cc00'>%s ngày </font>",
['registerReward604'] = " <font color='#ff8f43'> Kim cương VIP%s</font>",
['registerReward1001'] = "<font color='#dfb550'>%s</font>",-- Hôm nay
['registerReward1002'] = "<font color='#dfb550'>%s</font>",-- Bình thường
['registerReward1003'] = "<font color='#666666'>%s</font>",-- Tương lai
['registerReward1004'] = "<font color='#666666'>%s</font>",-- Trước kia
['registerReward2000'] = 'nhận thành công',
['registerReward2001'] = 'nhận thất bại',
['registerReward2002'] = 'Đã nhận quà rồi',
['registerReward2003'] = 'Mã chưa tới thời gian sử dụng',
['registerReward2004'] = 'Mã vô hiệu',
['registerReward2005'] = 'Mã sử dụng số lần đã đạt tới hạn mức cao nhất',
['registerReward2006'] = 'Mã sử dụng đã đạt hạn mức cao nhất',
['registerReward5000'] = "<font color='0fb300'>%s</font>",
['registerReward5001'] = "nhận thành công",
['registerReward5002'] = "nhập không đúng",
['registerReward5003'] = "Gói quà mã vô hiệu",
['registerReward5004'] = "Gói quà mã đã bị sử dụng",
['registerReward5005'] = "Gói quà mã sử dụng đã đạt hạn mức cao nhất",
['registerReward5006'] = "Hệ thống bận bịu, xin sau thử lại",
['registerReward5007'] = "Bạn hôm nay tính gộp lại online thời gian: ",
['registerReward6001'] = "%s Năm %s tháng %s Ngày",
['registerReward6002'] = "1. Khi Bạn offline, hệ thống sẽ tự động gộp lại quà offline đền bù ( Cao nhất 12 Giờ );    2. Đăng nhập lại sẽ nhận quà offline, VIP nhận nhiều hơn",
}
)
