UIStrConfig:Add(
{
['registerReward1'] = 'Nạp tiền',
['registerReward2'] = 'Nhận thưởng',
['registerReward21'] = 'Nhận ngay',
['registerReward3'] = 'Nhận gấp đôi',
['registerReward4'] = 'Nhận gấp ba',
['registerReward5'] = 'Kích hoạt',
['registerReward6'] = 'Nhận lấy gói quà',
['registerReward7'] = 'Cấp bậc chưa đủ',
['registerReward8'] = 'Mở ra gói quà',
['registerReward100'] = '<font color ="#7baac4">%s</font>',
['registerReward101'] = 'Thứ hai',
['registerReward102'] = 'Thứ ba',
['registerReward103'] = 'Thứ tư',
['registerReward104'] = 'Thứ năm',
['registerReward105'] = 'Thứ sáu',
['registerReward106'] = 'Thứ bảy',
['registerReward107'] = 'Chủ Nhật',
['registerReward150'] = 'Rút Thưởng',
['registerReward300'] = 'Báo danh hàng ngày',
['registerReward301'] = 'Thưởng online',
['registerReward302'] = 'Thưởng offline',
['registerReward303'] = 'Quà cấp độ',
['registerReward304'] = 'Quà Giftcode',
['registerReward305'] = 'Gói quà',
['registerReward502'] = 'Nhận thưởng',
['registerReward503'] = 'Lên VIP',
['registerReward505'] = 'Hoàng kim VIP Nhưng tự động đánh dấu, kim cương VIP Có thể gia tăng bổ ký cùng sớm ký số lần ờ!',
['registerReward506'] = 'Ký danh',
['registerReward508'] = 'Mở ra',
['registerReward507'] = 'Lên VIP',
}
)
