StrConfig:Add(
{
['dailymustdo1'] = "Số lần hoàn thành %s Lần",
['dailymustdo2'] = "Tiêu hao %s Trực tiếp hoàn thành nhiệm vụ, có thể đạt <font color='#00ff00'>%s%%</font> phần thưởng",
['dailymustdo3'] = "Tiêu hao %s hoàn thành nhiệm vụ này? Sau khi hoàn thành, có thể đạt <font color='#00ff00'>%s%%</font> phần thưởng!",
['dailymustdo4'] = "Tiêu hao %s hoàn thành tất cả nhiệm vụ này, mỗi nhiệm vụ có thể đạt <font color='#00ff00'>%s%%</font> phần thưởng",
['dailymustdo5'] = "Tiêu hao %s hoàn thành tất cả nhiệm vụ này? Sau khi hoàn thành, có thể đạt được  <font color='#00ff00'>%s%%</font> phần thưởng!",
['dailymustdo6'] = "<font color='#00ff00'>%s Nguyên bảo </font>",
['dailymustdo7'] = "<font color='#00ff00'>%s Ngân lượng </font>",
['dailymustdo8'] = "Tiêu hao %s để truy hồi <font color='#00ff00'>%s%%</font> Tài nguyên",
['dailymustdo9'] = "Có muốn dùng %s truy hồi <font color='#00ff00'>%s%%</font> Tài nguyên?",
['dailymustdo10'] = "Tiêu hao %s để truy hồi tất cả nhiệm vụ này <font color='#00ff00'>%s%%</font> Tài nguyên",
['dailymustdo11'] = "Truy hồi %s Lần",
['dailymustdo12'] = "NL Hoàn thành",
['dailymustdo13'] = "NB Hoàn thành",
['dailymustdo14'] = "Một khóa ngân lượng hoàn thành",
['dailymustdo15'] = "Một khóa Nguyên bảo hoàn thành",
['dailymustdo16'] = "Ngân lượng truy hồi",
['dailymustdo17'] = "Nguyên bảo truy hồi",
['dailymustdo18'] = "Truy hồi hết",
['dailymustdo19'] = "Hoàn mỹ truy hồi",
['dailymustdo20'] = "Ngân lượng không đủ",
['dailymustdo21'] = "Nguyên bảo không đủ",
['dailymustdo22'] = "Hiện không có tài nguyên truy hồi ",
['dailymustdo23'] = "Tiêu hao %s để truy hồi <font color='#00ff00'>0</font> Tài nguyên",
['dailymustdo24'] = "Sử dụng %s Truy hồi <font color='#00ff00'>0</font> Tài nguyên?",
['dailymustdo25'] = "Tiêu hao %s để truy hồi tất cả nhiệm vụ <font color='#00ff00'>0</font> Tài nguyên",
['dailymustdo26'] = "Sử dụng ngân lượng để truy hồi 65% Tài nguyên, sử dụng hoàng kim VIP Truy hồi để truy hồi 100% Tài nguyên.<br/> Một khóa truy hồi khiến cho dùng ngân lượng truy hồi 65% Tài nguyên, Chí tôn truy hồi dùng Nguyên bảo truy hồi 100% Tài nguyên.",
['dailymustdo27'] = "Không phải VIP Người chơi không cách nào sử dụng",
['dailymustdo28'] = "<font color='#4d4d4d'>%s</font>",
['dailymustdo29'] = "Dự tính tổng ích lợi: ",
['dailymustdo30'] = "Tổng cộng nhưng truy hồi tài nguyên: ",
['dailymustdo31'] = "<font color='#00ff00'>%s</font>",
['dailymustdo32'] = "%sVIP1 Trở lên mới có thể dùng",
['dailymustdo33'] = "<font color='#B86F11'> Hoàng kim VIP Truy hồi </font><br/>",
['dailymustdo34'] = "<font color='#B86F11'> Hoàng kim VIP Càn quét </font><br/>",
['dailymustdo1001'] = "Bạch ngân",
['dailymustdo1002'] = "Hoàng kim",
['dailymustdo1003'] = "Kim cương",
}
);
