StrConfig:Add(
{
-- Công năng chưa mở ra
['common001'] = 'Công năng chưa mở ra',
['common002'] = '<u> Thu hoạch đường tắt </u>',
-- Trang bị vị tên
['commonEquipName1'] = 'Vũ khí',
['commonEquipName2'] = 'Hộ kiên',
['commonEquipName3'] = 'Áo',
['commonEquipName4'] = 'Mũ giáp',
['commonEquipName5'] = 'Quần',
['commonEquipName6'] = 'Giày',
['commonEquipName7'] = 'Hộ thủ',
['commonEquipName8'] = 'Dây chuyền',
['commonEquipName9'] = 'Trang sức',
['commonEquipName10'] = 'Nhẫn trái',
['commonEquipName11'] = 'Nhẫn phải',
['commonEquipName12'] = 'Thời trang',
['commonEquipName21'] = 'Yên cỗ',
['commonEquipName22'] = 'Dây cương',
['commonEquipName23'] = 'Đồ trang sức',
['commonEquipName24'] = 'Đạp cỗ',
['commonEquipName31'] = 'Vòng cổ',
['commonEquipName32'] = 'Áo giáp',
['commonEquipName33'] = 'Hộ oản',
['commonEquipName34'] = 'Đồ trang sức',
['commonEquipName41'] = 'Mũi sừng',
['commonEquipName42'] = 'Gót sắt',
['commonEquipName43'] = 'Roi ngựa',
['commonEquipName44'] = 'Giáp ngực',
['commonNoLimit'] = 'Không hạn',
-- Nghề nghiệp tên
['commonProf1'] = 'Phượng Vũ',
['commonProf2'] = 'Vô Song',
['commonProf3'] = 'Ảnh Nha',
['commonProf4'] = 'Lôi Thú',
-- Giới tính
['commonSex1'] = 'Nam',
['commonSex0'] = 'Nữ',
['commonNon'] = 'Không',
-- Thuộc tính tên
['commonAttr1'] = 'Danh tự',
['commonAttr2'] = 'Nghề nghiệp',
['commonAttr3'] = 'Giới tính',
['commonAttr4'] = 'Cấp VIP',
['commonAttr5'] = 'Khu phục ID',
['commonAttr6'] = 'Đẳng cấp',
['commonAttr7'] = 'Kinh nghiệm',
['commonAttr8'] = 'Còn thừa điểm thuộc tính',
['commonAttr9'] = 'Tổng điểm thuộc tính',
['commonAttr10'] = 'Ngân lượng khóa',
['commonAttr11'] = 'Ngân lượng',
['commonAttr12'] = 'Nguyên bảo',
['commonAttr13'] = 'Nguyên bảo khóa',
['commonAttr14'] = 'Tu vi',
['commonAttr15'] = 'Hồn lực',
['commonAttr16'] = 'Thể phách',
['commonAttr17'] = 'Thân pháp',
['commonAttr18'] = 'Tinh thần',
['commonAttr19'] = 'Sinh mệnh',
['commonAttr20'] = 'Sinh mệnh',
['commonAttr21'] = 'Tốc độ hồi phực sinh mệnh',
['commonAttr22'] = 'Nội lực',
['commonAttr23'] = 'Nội lực',
['commonAttr24'] = 'Tốc độ hồi phực nội lực',
['commonAttr25'] = 'Thể lực',
['commonAttr26'] = 'Thể lực tối đa',
['commonAttr27'] = 'Tốc độ hồi phục thể lực',
['commonAttr28'] = 'Công kích',
['commonAttr29'] = 'Phòng ngự',
['commonAttr30'] = 'Chính xác',
['commonAttr31'] = 'Né tránh',
['commonAttr32'] = 'Bạo kích',
['commonAttr33'] = 'Sức bền',
['commonAttr34'] = 'Tốc độ đánh',
['commonAttr35'] = 'Tốc độ di chuyển',
['commonAttr36'] = 'Bạo tổn thương',
['commonAttr37'] = 'Kháng bạo',
['commonAttr38'] = 'Đâm xuyên',
['commonAttr39'] = 'Đón đỡ',
['commonAttr40'] = 'Tăng sát thương',
['commonAttr41'] = 'Giảm sát thương',
['commonAttr42'] = 'Xuyên thấu',
['commonAttr43'] = 'Hồn linh',
['commonAttr44'] = 'Hồn linh tối đa',
['commonAttr45'] = 'Tốc độ khôi phục Hồn linh ',
['commonAttr46'] = 'Lực Chiến',
['commonAttr47'] = 'Liên trảm',
['commonAttr48'] = 'Phá phòng',
['commonAttr49'] = 'Cày đồ sức sống giá trị',
['commonAttr50'] = 'Điểm thiện ác',
['commonAttr51'] = 'Vinh dự giá trị',
['commonAttr52'] = 'Trác tuyệt một kích tỉ lệ',
['commonAttr53'] = 'Trác tuyệt một kích tổn thương',
['commonAttr54'] = 'Linh trị',
['commonAttr55'] = 'Thiên thần năng lượng',
['commonAttr56'] = 'Mệt nhọc giá trị',
['commonAttr57'] = 'Tinh lực',
['commonAttr58'] = 'Sức sống giá trị',
['commonAttr59'] = 'Cực hạn phó bản điểm tích lũy',
['commonAttr60'] = 'Người chơi nạp số tiền',
['commonAttr61'] = '1V1 Điểm tích lũy',
['commonAttr62'] = 'Công huân',
['commonAttr63'] = 'Chiến ý giá trị',
['commonAttr64'] = 'Đẳng cấp',
['commonAttr65'] = 'Chuyển sinh đẳng cấp',
['commonAttr66'] = 'Sinh mệnh',
['commonAttr67'] = 'Công kích',
['commonAttr68'] = 'Phòng ngự',
['commonAttr69'] = 'Chính xác',
['commonAttr70'] = 'Né tránh',
['commonAttr71'] = 'Bạo kích',
['commonAttr72'] = 'Sức bền',
['commonAttr73'] = 'Đâm xuyên',
['commonAttr74'] = 'Xác suất đỡ đòn',
['commonAttr75'] = 'Xác suất xuyên thấu',
['commonAttr76'] = 'Phá phòng',
['commonAttr77'] = 'BOSS Điểm số',
['commonAttr78'] = 'Thần uy',
['commonAttr79'] = 'Tẩy luyện may mắn giá trị',
['commonAttr80'] = 'Tinh nguyên',
['commonAttr100'] = 'Giết quái hồi máu',
['commonAttr101'] = 'Giết quái hồi lam',
['commonAttr102'] = 'Công kích hồi máu',
['commonAttr103'] = 'Mỗi giây hồi máu',
['commonAttr104'] = 'Tỉ lệ rớt Ngân lượng',
['commonAttr105'] = 'Tỉ lệ rớt đạo cụ ',
['commonAttr106'] = 'Tổn thương quá mức',
['commonAttr107'] = 'Giảm tổn thương',
['commonAttr120'] = 'Tổn thương tiểu quái',
['commonAttr121'] = 'Tổn thương tiểu quái',
['commonAttr122'] = 'Tổn thương Boss',
['commonAttr123'] = 'Tổn thương Boss',
['commonAttr124'] = 'Tỉ lệ né tránh',
['commonAttr125'] = 'Công kích',
['commonAttr126'] = 'Phản sát thương',
['commonAttr127'] = 'Trác tuyệt một kích tỉ lệ',
['commonAttr128'] = 'Không nhìn một kích',
--
['commonAttr129'] = 'Tọa kỵ công kích',
['commonAttr130'] = 'Tọa kỵ phòng ngự',
['commonAttr131'] = 'Tọa kỵ sinh mệnh',
['commonAttr132'] = 'Tọa kỵ bạo kích',
['commonAttr133'] = 'Tọa kỵ sức bền',
['commonAttr134'] = 'Tọa kỵ né tránh',
['commonAttr135'] = 'Tọa kỵ chính xác',
['commonAttr136'] = 'Tọa kỵ toàn thuộc tính',
['commonAttr137'] = 'Thần thú công kích',
['commonAttr138'] = 'Thần thú phòng ngự',
['commonAttr139'] = 'Thần thú sinh mệnh',
['commonAttr140'] = 'Thần thú bạo kích',
['commonAttr141'] = 'Thần thú sức bền',
['commonAttr142'] = 'Thần thú né tránh',
['commonAttr143'] = 'Thần thú chính xác',
['commonAttr144'] = 'Thần thú toàn thuộc tính',
--
['commonAttr145'] = 'Kim',
['commonAttr146'] = 'Mộc',
['commonAttr147'] = 'Thủy',
['commonAttr148'] = 'Hỏa',
['commonAttr149'] = 'Thổ',
--
['commonAttr150'] = 'Kháng giảm tốc',
['commonAttr151'] = 'Kháng định thân',
['commonAttr152'] = 'Kháng mê muội',
['commonAttr153'] = 'Kháng trầm mặc',
-- Số lượng phân tích
['commonNum001'] = '%s Vạn',
['commonNum002'] = '%s Ức',
-- Đếm ngược văn bản
['commonCountDown001'] = '<font color="#cc0000">%s Giây </font> Sau tự động đóng',
-- Linh ấn trang bị vị
['commonEquipName50'] = 'Đại lãng chi ấn',
['commonEquipName51'] = 'Vẫn diễm chi ấn',
['commonEquipName52'] = 'Lôi phạt chi ấn',
['commonEquipName53'] = 'Tiên huyết chi ấn',
['commonEquipName54'] = 'Thiên quân chi ấn',
['commonEquipName55'] = 'Chiến hồn chi ấn',
['commonEquipName56'] = 'Tử vong chi ấn',
['commonEquipName57'] = 'Linh phách chi ấn',
['commonEquipName58'] = 'Địa Ngục chi ấn',
-- Cưỡi ấn trang bị vị
['commonEquipName60'] = 'U Minh chi linh',
['commonEquipName61'] = 'Ảm diệt chi linh',
['commonEquipName62'] = 'Tai nan chi linh',
['commonEquipName63'] = 'Tiêm khiếu chi linh',
['commonEquipName64'] = 'Thị huyết chi linh',
['commonEquipName65'] = 'Diệt thế chi linh',
['commonEquipName66'] = 'Hạo kiếp chi linh',
['commonEquipName67'] = 'Ẩn thiên chi linh',
['commonEquipName68'] = 'Thí thần chi linh',
-- Thần linh trang bị vị
['commonEquipName70'] = 'Hỗn độn chi hồn',
['commonEquipName71'] = 'Thánh quang chi hồn',
['commonEquipName72'] = 'Táng chi hồn',
['commonEquipName73'] = 'Thần hỏa chi hồn',
['commonEquipName74'] = 'Lôi đình chi hồn',
['commonEquipName75'] = 'Huyền băng chi hồn',
['commonEquipName76'] = 'Cửu thiên chi hồn',
['commonEquipName77'] = 'U Minh chi hồn',
['commonEquipName78'] = 'Đại thiên chi hồn',
-- Binh hồn trang bị vị
['commonEquipName109'] = 'Bất khuất chi hồn',
['commonEquipName110'] = 'Bất bại chi hồn',
['commonEquipName111'] = 'Bất hủ chi hồn',
['commonEquipName112'] = 'Sát huyết chi hồn',
['commonEquipName113'] = 'Phệ huyết chi hồn',
['commonEquipName114'] = 'Sôi huyết chi hồn',
['commonEquipName115'] = 'Kình thiên chi hồn',
['commonEquipName116'] = 'Ngự thuẫn chi hồn',
['commonEquipName117'] = 'Tiếc nhạc chi hồn',
-- Mệnh ngọc trang bị vị
['commonEquipName200'] = 'Ngọc hồn',
['commonEquipName201'] = 'Ngọc Phách',
['commonEquipName202'] = 'Ngọc Linh',
['commonEquipName203'] = 'Ngọc châu',
-- Thần binh trang bị vị
['commonEquipName300'] = 'Kiếm thủ',
['commonEquipName301'] = 'Chuôi kiếm',
['commonEquipName302'] = 'Lưỡi kiếm',
['commonEquipName303'] = 'Mũi kiếm',
-- Bảo giáp trang bị vị
['commonEquipName400'] = 'Hộ kiên',
['commonEquipName401'] = 'Hộ thủ',
['commonEquipName402'] = 'Hộ giáp',
['commonEquipName403'] = 'Hộ kính',
-- Pháp bảo Linh khí trang bị vị
['commonEquipName500'] = 'Linh dực',
['commonEquipName501'] = 'Linh tâm',
['commonEquipName502'] = 'Linh Tinh',
['commonEquipName503'] = 'Linh căn',
}
);
