StrConfig:Add(
{
['equipbuild001'] = '<font color="#be8c44"> Cần đem nhân vật đẳng cấp tăng lên tới <font color="#960000">%s Cấp </font> Mới có thể kích hoạt chế tạo </font>',
['equipbuild002'] = '<font color="%s">(%s/%s)</font>',
['equipbuild003'] = '<font color="#23961e">%s</font><br/><font color="#a0a0a0"> Kích hoạt sau thu hoạch được nên trang bị chế tạo phương pháp </font><br/><font color="#7896aa"> Nhưng tại [ Chúa tể con đường ] Thứ %s Chương ~ Thứ %s Tiết thu hoạch được </font>',
['equipbuild004'] = '<font color="#32961e">%s</font>',
['equipbuild005'] = 'Sức sống giá trị có thể dùng tại trang bị chế tạo tiêu hao <br/> Sức sống giá trị mỗi ngày tự động khôi phục, tăng lên vip Đẳng cấp có thể đạt được  cao hơn tốc độ khôi phục.',
['equipbuild006'] = '%s/%s',
['equipbuild007'] = 'Không phải vip',
['equipbuild008'] = 'Kim tệ không đủ',
['equipbuild009'] = 'Sức sống giá trị không đủ',
['equipbuild010'] = 'Vật liệu không đủ',
['equipbuild011'] = 'Hiện tại trang bị không thêm vào thuộc tính',
['equipbuild012'] = 'Ngẫu nhiên thu hoạch được %s Kèm theo thuộc tính',
['equipbuild013'] = 'Mời lựa chọn sử dụng trang bị',
['equipbuild014'] = 'Sức sống: %s',
['equipbuild015'] = '%s<font color="#960000">(%s)</font>',
['equipbuild016'] = '%s<font color="#29cc00">(%s)</font>',
['equipbuild017'] = 'Nhất định thu hoạch được 1 Đầu trác tuyệt thuộc tính',
['equipbuild018'] = '/ Mỗi %s Phút',
['equipbuild019'] = '<font color="#960000"> Chưa kích hoạt </font>',
['equipbuild020'] = 'Chế tạo bị thủ tiêu!',
['equipbuild021'] = '<font color="#960000">(%s)</font>',
['equipbuild022'] = 'Đang đánh tạo, xin sau!',
['equipbuild023'] = 'Xác suất thu hoạch được 3 Đầu trác tuyệt thuộc tính',
['equipbuild024'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Chế tạo quy tắc: </font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Phổ thông chế tạo xác suất thu hoạch được 2 Trác tuyệt cực phẩm trang bị.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/>VIP Chế tạo có tỉ lệ chế tạo ra có được mấy đầu trác tuyệt thuộc tính trang bị.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chỉ có kích hoạt bộ vị mới có thể đi vào đi chế tạo, đẳng cấp đạt tới sau, nhưng tự động kích hoạt chế tạo bộ vị.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Trang bị chế tạo vật liệu có thể thông qua chúa tể con đường cùng dã ngoại cày quái thu hoạch được.<img height='10'/></textformat>]],
['equipbuild025'] = 'Mời lựa chọn ngài muốn rèn đúc số lượng',
['equipbuild026'] = 'VIP Chế tạo có tỉ lệ ngoài định mức thu hoạch được 2 Đầu kèm theo thuộc tính',
['equipbuild027'] = "<textformat leading='5'>VIP Chế tạo nhất định thu hoạch được 1 Đầu cực phẩm thuộc tính </textformat><br/><textformat leading='5'>VIP Chế tạo nhất định thu hoạch được thứ 2 Đầu trác tuyệt thuộc tính </textformat><br/>VIP Chế tạo có tỉ lệ thu hoạch được thứ 3 Đầu trác tuyệt thuộc tính",
['equipbuild028'] = '<font color="#32961e">(%s)</font>',
['equipbuild029'] = 'Ngài cần lựa chọn chế tạo tiêu hao vật liệu loại hình',
['equipbuild030'] = 'Lựa chọn sau đem tiêu hao khóa lại vật liệu tiến hành chế tạo <br/> Chỉ có thể chế tạo ra khóa lại trang bị.<br/> Đồng thời câu tuyển khóa lại cùng không phải buộc vật liệu, đem ưu tiên tiêu hao khóa lại vật liệu.',
['equipbuild031'] = 'Lựa chọn sau đem tiêu hao không phải khóa lại vật liệu tiến hành chế tạo <br/> Có thể chế tạo ra không phải khóa lại trang bị.<br/> Đồng thời câu tuyển khóa lại cùng không phải buộc vật liệu, đem ưu tiên tiêu hao khóa lại vật liệu.',
['equipbuild200'] = 'Số không',
['equipbuild201'] = 'Một',
['equipbuild202'] = 'Hai',
['equipbuild203'] = 'Ba',
['equipbuild204'] = 'Bốn',
['equipbuild205'] = 'Năm',
['equipbuild206'] = 'Sáu',
['equipbuild207'] = 'Bảy',
['equipbuild208'] = 'Tám',
['equipbuild209'] = 'Chín',
['equipbuild210'] = 'Mười',
['equipbuild211'] = 'Mười một',
['equipbuild212'] = 'Mười hai',
['equipbuild315'] = '<font color="#960000"> Cực thấp </font>',
--['equipbuild315'] = '<font color="#960000">   <textformat leading="10" leftmargin="100"> Cực thấp </textformat><br/></font>',
['equipbuild314'] = '<font color="#D6A940"> Khá thấp </font>',
['equipbuild313'] = '<font color="#690ED9">  </font>',
['equipbuild312'] = '<font color="#7896AA"> Tương đối cao </font>',
['equipbuild311'] = '<font color="#32961e"> Cực cao </font>',
--
-- item Phẩm giai
['equipbuildlvl000'] = 'Linh giai trang bị',
['equipbuildlvl001'] = 'Nhất giai trang bị',
['equipbuildlvl002'] = 'Nhị giai trang bị',
['equipbuildlvl003'] = 'Tam giai trang bị',
['equipbuildlvl004'] = 'Tứ giai trang bị',
['equipbuildlvl005'] = 'Ngũ giai trang bị',
['equipbuildlvl006'] = 'Lục giai trang bị',
['equipbuildlvl007'] = 'Thất giai trang bị',
['equipbuildlvl008'] = 'Bát giai trang bị',
['equipbuildlvl009'] = 'Cửu giai trang bị',
['equipbuildlvl0010'] = 'Thập giai trang bị',
-- Trang bị phân giải
['equipbuild101'] = 'Mời lựa chọn muốn phân giải trang bị phẩm chất loại hình!',
['equipbuild102'] = 'Không có trang bị nhưng để vào!',
['equipbuild103'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Quy tắc nói rõ:</font>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Phân giải trang bị có thể đạt được  cực phẩm vật liệu.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Tử sắc phẩm chất trang bị phân giải có thể đạt được tẩy luyện thạch.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Phân giải trang bị cấp bậc, phẩm chất càng cao, có thể lấy được vật liệu càng nhiều.<img height='10'/></textformat>]],
['equipbuild104'] = 'Khảm nạm có sáo trang thạch trang bị không cách nào phân giải',
}
)
