StrConfig:Add(
{
['christmas001'] = '%s Ngày %s Giờ %s Phút %s Giây',
['christmas002'] = 'Hoạt động đã kết thúc',
['christmas003'] = 'Hoạt động chưa mở ra',
['christmas004'] = 'Cấp bậc chưa đủ',
['christmas010'] = 'Hoạt động đã kết thúc',
['christmas011'] = 'Hoạt động đã đóng',
['christmas012'] = 'Đạo cụ không đủ',
['christmas013'] = 'Hiện tại không thể nhận thưởng',
['christmas014'] = 'Đã nhận',
['christmas050'] = 'Cống hiến %s Cái đạo cụ khỏa thu hoạch được:',
['christmas111'] = 'Hoạt động mở ra sau, tại Bắc Thương thành ngẫu nhiên tuyến, ngẫu nhiên vị trí đổi mới 50 Chỉ người tuyết.',
['christmas112'] = 'Cách mỗi 10 Phút, ngoài định mức đổi mới một đợt 50 Chỉ người tuyết.',
['christmas113'] = 'Người tuyết ở ngươi chơi tiếp cận lúc sẽ chạy loạn. Tại khoảng cách nhất định bên trong con chuột điểm trúng người tuyết, có thể tiến hành bắt giữ.',
['christmas114'] = 'Người chơi mỗi thành công bắt được 1 Cái người tuyết sau, bên trong túi đeo lưng gia tăng đạo cụ',
['christmas115'] = 'Người chơi mang theo',
['christmas116'] = 'Nhưng tại',
['christmas117'] = 'Chỗ tiến hành hối đoái.',
['christmas118'] = 'Đổi mới địa đồ: Bắc Thương thành %s Tuyến',
['christmas150'] = '<u> Bắc Thương thành %s</u>',
['christmas151'] = '<u>%s</u>',
['christmas152'] = '<u> Bắc Thương thành %s</u>',
['christmas200'] = 'Cây thông Noel tiến độ: %s/%s <br/> Cống hiến đạo cụ có thể tăng lên cây thông Noel tiến độ, cây thông Noel dựng đến trình độ nhất định sau, toàn bộ server nhưng nhận lấy gói quà ban thưởng.',
}
)
