StrConfig:Add(
{
['gm001'] = "Cấm ngôn 1 Giờ",
['gm002'] = "Cấm ngôn 1 Ngày",
['gm003'] = "Vĩnh cửu cấm ngôn",
['gm004'] = "Giải trừ cấm ngôn",
['gm005'] = "Phong ngừng 1 Giờ",
['gm006'] = "Phong ngừng 1 Ngày",
['gm007'] = "Vĩnh cửu phong ngừng",
['gm008'] = "Giải trừ phong ngừng",
['gm009'] = "Phong ngừng Mac",
['gm010'] = "Giải trừ phong ngừng Mac",
['gm011'] = "Đá xuống tuyến",
['gm012'] = "Bổ nhiệm bang chủ",
['gm013'] = "Nhâm phó bang chủ",
['gm014'] = "Bổ nhiệm trưởng lão",
['gm015'] = "Bổ nhiệm tinh anh",
['gm016'] = "Bổ nhiệm bang chúng",
['gm017'] = "Đá ra bang phái",
['gm018'] = "Thao tác thất bại",
['gm019'] = "<font color='#00ff00'> Thao tác thành công </font>",
['gm020'] = "Quan bế GM Xưng hào",
['gm021'] = "Sử dụng GM Xưng hào",
["gm022"] = "Bang phái:",
["gm023"] = "Xác định giải tán bang phái?",
["gm024"] = " Đối",
["gm025"] = "[ Loa ]",
["gm026"] = "Nội dung không thể vì không",
["gm027"] = "Kim cương",
["gm028"] = "Hoàng kim",
["gm029"] = "Bạch ngân",
["gm030"] = "<u> Xem xét bang phái </u>",
["gm031"] = "Bình thường",
["gm032"] = "Ngày",
["gm033"] = "Giờ",
["gm034"] = "Phút",
["gm035"] = "Giây",
});
