StrConfig:Add(
{
-- ['quest1'] = '',
['quest2'] = '',
['quest3'] = '',
['quest4'] = '',
['quest5'] = '',
-- Npc Nhiệm vụ đối thoại
['quest6'] = 'Xác nhận',
['quest7'] = 'Nhận thưởng',
['quest8'] = 'Tiến vào phó bản',
['quest9'] = "Hiện tại đã nhận nhiệm vụ đạt 20 Cái, mời giao phó hoặc từ bỏ bộ phận nhiệm vụ sau lần nữa xác nhận.",
['quest10'] = "Chủ tuyến",
['quest11'] = "Tuần Hoàn",
['quest12'] = "Phụ Tuyến",
['quest13'] = "Lịch luyện",
['quest14'] = "Đẳng cấp",
['quest15'] = "Thành tựu",
['quest16'] = "Nhận thưởng",
['quest17'] = "Tuần hoàn nhiệm vụ hôm nay đã hoàn thành",
['quest18'] = "Kỳ ngộ nhiệm vụ hôm nay đã hoàn thành",
['quest19'] = "Đào bảo nhiệm vụ hôm nay đã hoàn thành",
['quest20'] = "Chém yêu đồ ma hôm nay đã hoàn thành",
['quest21'] = "Chuyển chức",
['quest22'] = "Đồ ma",
['quest30'] = "[Chính]",
['quest31'] = "[Phụ]",
['quest32'] = "[EXP]",
['quest33'] = "[EXP]",
['quest34'] = "[Trang]",
['quest35'] = "[EXP]",
['quest36'] = "[Phi]",
['quest37'] = "[Mục]",
['quest38'] = "[EXP]",
['quest39'] = "[Đạo]",
['quest40'] = "[Đạo]",
['quest41'] = "[Thiên]",
['quest42'] = "[EXP]",
['quest43'] = "[Chiến]",
['quest44'] = "[EXP]",
['quest45'] = "[T.Bị]",
['quest46'] = "[Đạo]",
['quest47'] = "[Đạo]",
['quest48'] = "[Đạo]",
['quest49'] = "[EXP]",
['quest50'] = "[Bang]",
['quest51'] = "[Đạo]",
['quest52'] = "[Vinh]",
['quest53'] = "[Auto]",
['quest60'] = "[EXP]",
['quest61'] = "[Tiền]",
['quest62'] = "[Tu vi]",
['quest63'] = "[Đạo]",
-- Tuần hoàn nhiệm vụ ( Chủ bảng )
['quest001'] = 'Tự động đem nhiệm vụ tăng lên đến 5 Tinh,VIP%s Trở lên có thể sử dụng chức năng này',
['quest002'] = "Tuần hoàn nhiệm vụ chưa mở ra, cần đạt tới %s Cấp",
['quest101'] = '<font color="#A17033"> Mỗi hoàn thành 5 Vòng  </font><font color="#00ff00"> Rút thưởng 1 Lần </font>',
['quest102'] = '<font color="#A17033"> Hoàn thành cùng ngày <font color="#00ff00">20 Lần </font> Vòng nhiệm vụ sau có thể đạt được  trở xuống ban thưởng </font>',
['quest103'] = '<font color="#A17033"> Tiêu hao:<font color="#00ff00">%s  / Vòng </font></font>',
['quest104'] = 'Nhắc nhở: Tuần hoàn nhiệm vụ vào khoảng mỗi ngày 00:00 Tiến hành thiết lập lại, mời kịp thời hoàn thành.',
['quest105'] = 'Hoàn thành <font color="#00FF00">%s Lần </font> Tuần hoàn nhiệm vụ sau  nhận lấy',
['quest106'] = 'Hiện tại đã hoàn thành <font color="#00FF00">%s Vòng </font>, lại hoàn thành <font color="#00FF00">%s Lần </font> Tuần hoàn nhiệm vụ có thể đạt được  đặc thù ban thưởng',
['quest107'] = 'Tốn hao <font color="#00FF00">%s Nguyên bảo </font>( Ưu tiên sử dụng buộc nguyên ) Có thể đem ban thưởng tăng lên đến <font color="#ff8f43">5 Tinh </font><br/>5 Tinh ban thưởng làm cơ sở ban thưởng 200%%',
['quest108'] = '<font color="#d5b772"> Địa đồ </font><u><font color="#00ff00">[%s]</font></u>',
['quest109'] = "%s <font color='#EC8E11'>× %s</font>",
['quest110'] = "Tiền không đủ",
-- Tuần hoàn nhiệm vụ ( Phổ thông ban thưởng bảng )
['quest111'] = "<font color='#00ff00'> Thứ %s Vòng </font>",
['quest112'] = '<font color="#00ff00"><font color="#FF0000">%s Giây </font> Sau tự động lĩnh thưởng rời khỏi!</font>',
['quest111112'] = '<font color="#00ff00"><font color="#FF0000">%s Giây </font> Sau tự động ngân lượng nhận lấy!</font>',
-- Tuần hoàn nhiệm vụ ( Bạo kích ban thưởng bảng )
['quest113'] = "<i><font color='#2fe00d'><font color='#cc0000' size='16'>%s Giây </font> Sau đem tự động đóng!</font></i>",
-- Tuần hoàn nhiệm vụ ( Một lần hoàn thành ban thưởng bảng )
['quest114'] = "Thứ %s Vòng thu hoạch được",
['quest115'] = "Lần ban thưởng",
['quest116'] = '<font color="#00ff00"><font color="#FF0000">%s Giây </font> Sau tự động đóng </font>',
-- Tuần hoàn nhiệm vụ ( Nhiệm vụ truy tung bảng ) Hoàn thành Tuần hoàn thời điểm bắn ra vật kia
['quest117'] = "<font color='#c8c8c8'>%s</font>",
['quest118'] = "Nhiệm vụ Tinh cấp",
['quest119'] = "Tự động tăng lên đến %s Tinh, <font color='#b86f11'>VIP%s</font> Có thể sử dụng",
['quest120'] = "Nhiệm vụ ban thưởng",
['quest0000000120'] = "Nhiệm vụ truy tung",
['quest121'] = "Hoàng kim VIP1 Người chơi  tự động đem nhiệm vụ thăng đến %s Tinh",
-- Tuần hoàn rút thưởng bảng
['quest126'] = "<u><font color='#cc0000' size='16'>%s Giây </font> Sau tự động vì bạn rút ra </u>",
['quest127'] = "<u><font color='#cc0000' size='16'>%s Giây </font> Sau tự động đóng bảng </u>",
-- Tuần hoàn nhiệm vụ tips
['quest130'] = "Bản vòng nhiệm vụ ban thưởng",
['quest131'] = "Hoàn thành hôm nay <font color='#00ff00'>(%s) Vòng </font> Nhiệm vụ sau có thể đạt được  ban thưởng",
['quest132'] = "( Hôm nay 24 Điểm trước toàn bộ sau khi hoàn thành mới có thể nhận lấy )",
['quest133'] = "Hôm nay thứ <font color='#29cc00'>(%s)</font> Vòng",
['quest134'] = "Lại hoàn thành <font color='#00ff00'>%s Lần </font> Tuần hoàn nhiệm vụ sau có thể lấy được lấy",
['quest135'] = "Ban thưởng kinh nghiệm / Thăng cấp kinh nghiệm: %.2f%%",
['quest136'] = "( Có thể sử dụng Nguyên bảo trực tiếp hoàn thành toàn bộ nhiệm vụ )",
['quest137'] = "<u> Có thể tăng lên </u>",
-- Tuần hoàn nhiệm vụ một kiện hoàn thành tips
['quest140'] = "Theo <font color='#31b84e'>%s Tinh </font> Hoàn thành còn thừa số lần nhiệm vụ",
['quest141'] = "Dự tính có thể đạt được  ích lợi",
['quest142'] = "Một lần sau khi hoàn thành có thể thu hoạch được toàn bộ bảo rương ban thưởng",
['quest143'] = "Hiện tại cần tốn hao:   <font color='#a0a0a0'>%s</font>",
-- Tuần hoàn nhiệm vụ chủ giao diện Tinh cấp tips
['quest144'] = "<font color='#ffffff'> Tinh cấp:</font>",
-- Tuần hoàn nhiệm vụ chủ giao diện truyền tống tips
['quest145'] = "Nhấp chuột truyền tống đến nhiệm vụ địa điểm",
-- Tuần hoàn Cái khác
['quest146'] = "Nguyên bảo không đủ, không cách nào thăng tinh",
['quest147'] = "Một lần hoàn thành còn lại Tuần hoàn nhiệm vụ, mỗi vòng tiêu hao %s Buộc nguyên",
['quest148'] = "Một lần hoàn thành",
['quest149'] = "Đã nhận lấy",
-- Tuần hoàn nhảy vòng ban thưởng bảng
['quest150'] = "<font color='#d5b772'> Chúc mừng rút thưởng thu hoạch được nhảy <font color='#00FF00'>     </font> Ban thưởng, nhảy vòng ban thưởng theo ngũ tinh thu hoạch!</font>",
['quest151'] = "Có thể đạt được : ",
--
['quest161'] = "Bạch ngân VIP Có thể sử dụng tự động thăng tinh",
['quest162'] = "Hoàng kim VIP1 Có thể sử dụng Một lần hoàn thành",
-- Nhiệm vụ ban thưởng trang bị bạo kích
['quest201'] = "",
['quest202'] = "",
-- Tuần hoàn toàn bộ hoàn thành mỗi ngày ban thưởng
['quest301'] = "<font color='#d5b772'> Hôm nay toàn bộ </font>",
['quest3001'] = "<font color='#d5b772'> Đã hoàn thành %s Vòng Tuần hoàn nhiệm vụ,  nhận lấy trở xuống ban thưởng </font>",
-- Tuần hoàn Một lần hoàn thành bội số lựa chọn bảng
['quest302'] = "1 lần hoàn thành",
['quest303'] = "%s Lần hoàn thành <font color='#00FF00'> vượt mức tiêu hao: Ngân lượng %s</font>",
['quest304'] = "%s Lần hoàn thành <font color='#00FF00'> vượt mức tiêu hao: Nguyên bảo %s( Ưu tiên sử dụng buộc nguyên )</font>",
['quest305'] = "Đem tiêu hao %s Ngân lượng nhận lấy %s Lần ban thưởng",
['quest306'] = "Đem tiêu hao %s Nguyên bảo nhận lấy %s Lần ban thưởng",
['quest307'] = 'Một lần hoàn thành %s Vòng nhiệm vụ cần tiêu hao: <font color="#D2A930">%s Nguyên bảo </font>( Ưu tiên sử dụng buộc nguyên )',
['quest308'] = "Ngân lượng không đủ",
['quest309'] = "Nguyên bảo không đủ",
['quest310'] = 'Một lần hoàn thành %s Vòng nhiệm vụ cần tiêu hao: <font color="#D2A930">%s Nguyên bảo </font>',
['quest311'] = "%s Lần hoàn thành <font color='#00FF00'> vượt mức tiêu hao: Nguyên bảo %s</font>",
--
['quest401'] = "Hiện tại rút thưởng",
['quest402'] = "Tăng lên Tinh cấp có thể tăng lên nhiệm vụ ban thưởng",
['quest403'] = "Bản vòng nhiệm vụ đã hoàn thành, không cách nào tăng lên Tinh cấp",
-- Thăng tinh thất bại nhắc nhở
['quest404'] = "Tiền không đủ",
-- Ban thưởng tương quan
['quest501'] = "Kinh nghiệm <font color='#00ff00'>%s</font>",
['quest502'] = "Ngân lượng <font color='#00ff00'>%s</font>",
['quest503'] = "Tu vi <font color='#00ff00'>%s</font>",
['quest504'] = "1 lần nhận lấy",
['quest505'] = "%s Lần nhận lấy (%s<img src='%s'/>)",
['quest506'] = "<font size = '14' >%s Lần nhận lấy (%s<img src='%s'/>)</font>",
['quest601'] = "Ban thưởng:%s",
['quest602'] = "Đề cử treo máy:<u><font color='#00ff00'>%s</font></u>(%s Cấp )",
['quest603'] = "Đề cử phó bản:<u><font color='#00ff00'>%s</font></u>",
['quest604'] = "Đề cử hoạt động:<u><font color='#00ff00'>%s</font></u>",
['quest605'] = "Đề cử nhiệm vụ:<u><font color='#00ff00'>%s</font></u>",
['quest701'] = "Nhấp chuột tiến về",
['quest702'] = "Chức năng chưa mở ra",
['quest703'] = "Tiến vào điều kiện không, Nhấp chuột xem xét tường tình",
['quest704'] = "<i> Chúc mừng bạn thành công hoàn thành Linh thú kích hoạt phó bản,<br/> Kích hoạt Linh thú Chức năng </i>",
['quest705'] = "Thoát",
['quest706'] = "<i> Chúc mừng bạn mở ra Tuần hoàn nhiệm vụ, hoàn thành Tuần hoàn có thể đạt được  đại lượng kinh nghiệm.</i>",
['quest707'] = "Bắt đầu Tuần hoàn",
['quest708'] = "Sau đó lại nói",
['quest801'] = "Khoảng cách đời tiếp theo vụ địa điểm khá xa, Nhấp chuột xác định miễn phí truyền tống",
['quest802'] = "bạn Hiện tại có <font color='#29cc00'>%s</font> Lần miễn phí truyền tống cơ hội, phải chăng truyền tống tiến về?",
['quest803'] = "Truyền tống",
['quest804'] = "Đi bộ",
---------------- Kỳ ngộ phó bản -----------------------
['randomQuest001'] = "Thoát", -- Nút bấm
['randomQuest002'] = "Hỏi thăm manh mối", -- Nút bấm
['randomQuest003'] = "Kỳ ngộ phó bản", -- Tiêu đề
-- Bài thi phó bản
['randomQuest004'] = "Bài thi tiến độ:<font color='#00FF00'>%s/%s</font>",
['randomQuest005'] = "Chúc mừng ngươi toàn bộ đáp đúng!",
['randomQuest006'] = "Cáo từ",
-- Tìm manh mối phó bản
['randomQuest007'] = "Đã tìm tới",
['randomQuest008'] = "Không tìm được",
['randomQuest009'] = "Manh mối phải chăng tìm tới:<font color='#00FF00'>%s</font>",
-- Thu thập phó bản
['randomQuest010'] = "Thu thập số lượng:<font color='#00FF00'>%s/%s</font>",
-- Đánh quái phó bản
['randomQuest011'] = "Đã giết quái:<font color='#00FF00'>%s/%s</font>",
-- Ngồi xuống phó bản
['randomQuest012'] = "Còn thừa thời gian:<font color='#00FF00'>%s</font>",
-- tips
['randomQuest101'] = "Ban thưởng: ",
['randomQuest102'] = "<u> Kỳ ngộ ·%s</u>",
['randomQuest103'] = "%s Giây sau tự động rời khỏi",
['randomQuest104'] = "Tìm được: Chúc mừng ngươi tìm được chân chính manh mối",
['randomQuest105'] = "Không tìm được: Thật đáng tiếc, chân tướng không phải cái này",
['randomQuest106'] = "Tổ đội đang trang thái không cách nào tiến vào kỳ ngộ phó bản",
["npcDialog0007"] = "<font color='#ff0000' size='18'>%s Giây </font> Sau tiến nhập phó bản",
['randomQuest201'] = "<font color='#ffffff' size='14'> Đánh bại </font>",
['randomQuest202'] = "<u><font color='%s' size='%s'>%s</font></u>",
['randomQuest203'] = "Mời trước xác nhận lịch luyện nhiệm vụ",
-- Thú phách phó bản
["shoupuo001"] = "Nhiệm vụ hoàn thành, phải chăng rời khỏi?",
["npcDialog001"] = 'Thu được',
["npcDialog002"] = "Nhận lấy hoàng tử thao chuyên môn xưng hào",
["npcDialog003"] = "Kích hoạt mã hối đoái",
["npcDialog004"] = "Nhận lấy Dương Mịch chuyên môn xưng hào",
["npcDialog005"] = "Hối đoái cửa hàng",
["npcDialog006"] = "<font size='18' color='#FF0000'>%s Giây </font> Sau tự động tiếp tục",
["quest901"] = 'bạn không phải hoàng kim VIP',
["quest902"] = "Chém yêu đồ ma",
["quest90002"] = "Tiên giai cửa vào",
["quest903"] = "%s Phút sau đổi mới",
["quest904"] = "Hôm nay đã kết thúc",
["quest905"] = "Xác nhận nhiệm vụ",
["quest9005"] = "Xác nhận đồ ma nhiệm vụ", -- Đồ ma xác nhận nhiệm vụ
["quest90005"] = "Tiên giai cửa vào",
["quest90006"] = "Kinh nghiệm phó bản",
["quest906"] = "Đánh bại <u><font size='%s' color='%s'> Tùy ý quái </font></u><font color='#fefefe'>(%s/%s)</font>",
["quest907"] = "Nhận lấy ban thưởng",
["quest908"] = "<font size='14' color='#ffde00'>  %s</font>",
["quest909"] = "<font size='14' color='#ffde00'>  Trác tuyệt thu thập </font>",
["quest90009"] = "<font size='14' color='#ffde00'>  Phó bản đại sảnh </font>",
["quest910"] = "Nhấp chuột đào bảo",
["quest911"] = "<font size='14' color='#ffde00'>  Tầm bảo </font>",
["quest912"] = "<font size='14' color='#feaf05'>( Còn thừa %s Lần )</font>",
["quest913"] = "<font size='18' color='#FF0000'>%s Giây </font> Sau tự động tiến về Tuần hoàn",
["quest914"] = "<font size='18' color='#FF0000'>%s Giây </font> Sau tự động tiếp tục",
["quest915"] = "<font size='18' color='#FF0000'>%s Giây </font> Sau tự động rời khỏi phó bản",
["quest916"] = "<font color='#e59607' size='14'> Nhận lấy điều kiện:<font color='#dcdcdc'> Hoàn thành %s Vòng </font></font>",
["quest917"] = "( Cần đạt tới %s Cấp )",
["quest918"] = "Biến hình địa cung",
["quest919"] = "Tổ đội khiêu chiến",
["quest920"] = "Thiên thần chiến trường",
["quest921"] = "Tổ đội khiêu chiến cửa vào",
["quest922"] = "Tổ đội thăng cấp cửa vào",
["quest923"] = "<font color='%s' size='%s'>  Lịch luyện nhiệm vụ thứ %s/%s Lần </font>",
["quest924"] = "Thảo phạt nhiệm vụ",
["quest925"] = "Tìm kiếm %s",
["quest926"] = "Treo thưởng nhiệm vụ",
["quest927"] = "Mỗi ngày kinh nghiệm nhiệm vụ",
["quest928"] = "Cày đồ địa cung",
["quest929"] = "<font size='14' color='#feaf05'>( Còn thừa %s Phút )</font>",
["quest930"] = "Cam trang thí luyện",
["quest931"] = "<font size='14' color='#feaf05'>( Hôm nay chưa khiêu chiến )</font>",
["quest932"] = "Tru Tiên Trận",
["quest933"] = "Biến hình địa cung",
["quest934"] = "Thượng cổ chiến trường",
["quest935"] = "<font size='14' color='#feaf05'>(  khiêu chiến )</font>",
["quest936"] = "Săn ma nhiệm vụ",
['quest937'] = '<font color="#00ff00"><font color="#FF0000">%s Giây </font> Sau tự động đóng, cũng bắt đầu tiếp theo vòng </font>',
['quest938'] = '<font color="#00ff00"><font color="#FF0000">%s Giây </font> Sau tự động đóng, cũng tiếp tục làm chủ tuyến nhiệm vụ </font>',
["quest939"] = "Gia nhập bang phái",
['quest940'] = '<font color="#00ff00"><font color="#FF0000">%s Giây </font> Sau tự động đóng </font>',
['quest941'] = '<font color="#00ff00"><font color="#FF0000">%s Giây </font> Sau tự động đóng, cũng tự động tiến hành xuống một nhiệm vụ </font>',
["quest942"] = "Sân thi đấu",
["quest943"] = "<font size='14' color='#ffde00'>  Đề cử %s</font><font size='14' color='#feaf05'>(%s Cấp )</font>",
["npcDialog007"] = "Giáng Sinh hối đoái cửa hàng",
['npcDialog008'] = "bạn sắp tiến vào địa cung một tầng, tiến vào tiêu hao: <font color='%s'><u> Địa cung vé vào cửa *1</u></font>",
["npcDialog009"] = "Tiến vào địa cung một tầng",
-- Hoan nghênh bảng
["quest1000"] = "<font color='#ff0000'>%s Giây </font><font color='#00ff00'> Sau tự động nhận lấy </font>",
['quest1001'] = "Tiếp nhận nhiệm vụ",
['quest1002'] = "Hoàn thành nhiệm vụ",
['quest1003'] = "Đánh bại",
['quest1004'] = "Tiến vào phó bản",
-- Một mình phó bản tương quan
["quest2000"] = "1. Mỗi ngày miễn phí tiến vào số lần <font color='%s'>%s</font> Lần",
["quest2001"] = "2. Tiêu hao lệnh bài phó bản đơn vượt mức tiến vào <font color='%s'>%s</font> Lần",
["quest2002"] = "3. Hoàng kim vip Mỗi ngày tùy ý tuyển một cái phó bản vượt mức tiến vào <font color='#00ff00'>1</font> Lần",
["quest2003"] = " vượt mức tiến vào <font color='#00ff00'>1</font> Lần",
-- Hội nghị chỗ Mới đồ ma Mới treo thưởng
['agoraQuest001'] = "<u><font color='%s' size='%s'>%s</font></u>",
['agoraQuest002'] = "Mời trước xác nhận treo thưởng nhiệm vụ",
}
)
