UIStrConfig:Add(
{
['quest1'] = 'Chủ tuyến',
['quest2'] = 'Phụ tuyến',
['quest3'] = 'Tuần hoàn',
['quest4'] = 'Kỳ ngộ',
['quest5'] = '( Tiếp Theo )',
['quest6'] = '( Chưa hoàn thành )',
['quest7'] = '( Có thể kết giao )',
['quest8'] = 'Nhiệm vụ ban thưởng: ',
['quest9'] = 'Hoàn thành tấu chương kịch bản kích hoạt thuộc tính: ',
['quest10'] = 'Chương sau',
['quest11'] = '<font size="12" color="#29cc00"><u> Trở về tấu chương </u></font>',
['quest12'] = 'Đã nhận nhiệm vụ',
['quest13'] = 'Nhận nhiệm vụ',
['quest14'] = 'Xác nhận',
['quest15'] = 'Tiến về',
['quest16'] = 'Nhiệm vụ',
['quest17'] = '( Không thể tiếp )',
['quest18'] = 'Lập tức tiến về',
['quest19'] = '( Đã hoàn thành )',
['quest20'] = 'Thoát',
['quest21'] = 'Xác thực',
['quest22'] = 'Bắt đầu đi',
-- Ngày vòng
['quest101'] = 'Một lần hoàn thành',
['quest102'] = 'Thăng Tinh',
['quest103'] = 'Mời lựa chọn một lần hoàn thành cần thiết',
['quest104'] = 'Xác thực',
['quest105'] = 'Xác thực',
['quest106'] = '1 lần nhận lấy',
['quest107'] = 'Ngân lượng gấp đôi',
['quest108'] = 'Nguyên bảo gấp ba',
['quest109'] = 'Xác thực',
['quest110'] = 'Lấy Tiêu',
['quest111'] = "Thăng tinh",
['quest112'] = "Lập tức đi",
['quest113'] = "Nhắc lại",
['quest121'] = "Ta đã biết",
-- Mục tiêu
['quest201'] = "Nhận thưởng",
}
)
