StrConfig:Add(
{
-- Bảo giáp bảng
['armor001'] = 'Bảo giáp cấp bậc',
['armor002'] = '<font color="#e59607"> Độ thuần thục cấp: </font><font color="#dcdcdc">%s</font><br><font color="#dcdcdc">%s</font><font color="#e56a10"> Mỗi lần phát động <font color="#00b7ef">%s</font>, độ thuần thục đều sẽ tăng lên </font>',
['armor003'] = "Đã thăng đến cao giai nhất",
['armor004'] = "Công  Kích: %s",
['armor005'] = "Phòng  Ngự: %s",
['armor006'] = "Bạo  Kích: %s",
['armor007'] = "Sinh  Mệnh: %s",
['armor008'] = "Bạo thương: %s",
['armorplus009'] = "Sức bền: %s",
['armorplus010'] = "Kháng bạo: %s",
['armor009'] = "<font color='#29cc00'> Độ thuần thục đạt tối đa </font>",
-- Bảo giáp tiến giai bảng
['armor010'] = "Tiến giai tiêu hao: ",
['armor011'] = "Ngân lượng: ",
['armor012'] = "<u><font color='%s'>%s%s Khỏa </font></u>",
-- Bảo giáp kỹ năng thăng cấp bảng
['armor013'] = "%s:<br><font color='#c8c8c8'>1, giai vị:<font color='%s'>%s Giai %s</font><br>2, cần tiêu hao đạo cụ:</font>",
['armor014'] = "Đạo cụ không đủ",
['armor015'] = "Cấp Bảo Giáp không đủ",
['armor016'] = "Đã tập được",
['armor017'] = "Chưa tập được",
['armor018'] = "( Đã đạt thành )",
['armor019'] = "( Chưa đạt thành )",
-- Nhắc nhở tin tức
['armor020'] = "Độ thuần thục không đủ",
['armor021'] = "Ngân lượng không đủ",
['armor022'] = "Đạo cụ số lượng không đủ",
['armor023'] = "Độ thuần thục đầy sau mới có thể thăng giai",
['armor024'] = "<font color='#e59607'> Hiện tại giá trị chúc phúc: <font color='#dcdcdc'>%s</font></font><br/><font color='#e59607'> Chúc phúc giá trị thanh không tình trạng: </font><font color='#e56a10'> Chúc phúc giá trị tại mỗi ngày rạng sáng <font color='#00ff00'>6 Điểm </font> Về không </font><br/><font color='#e59607'> Chúc phúc giá trị nói rõ: </font><br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi lần chưa thể thành công tiến giai, đều đem tăng lên chúc phúc giá trị.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị càng cao, lần sau thao tác xác suất thành công càng cao.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị thăng đầy sau, thì lần sau thăng giai thao tác nhất định thành công </font>",
['armor025'] = "Hiện tại kỹ năng đã đạt cấp cao nhất",
['armor026'] = "Độ thuần thục: ",
['armor027'] = "Thắp sáng hạ khỏa tinh có thể gia tăng như sau thuộc tính: \n%s",
['armor028'] = "Bảo giáp kỹ năng",
['armor029'] = "Thăng cấp điều kiện",
['armor030'] = "Điều kiện học tập",
['armor031'] = "Thăng cấp kỹ năng",
['armor032'] = "Học tập kỹ năng",
['armor033'] = "Độ thuần thục đầy có thể thăng giai",
['armor034'] = "Đạo cụ không đủ, không thể tiến giai",
['armor035'] = "Ngân lượng không đủ, không thể tiến giai",
['armor036'] = "Công Kích",
['armor037'] = "Phòng Ngự",
['armor038'] = "Sinh Mệnh",
['armor039'] = "Bạo Kích",
['armor040'] = "Chính Xác",
['armor041'] = "Bạo Thương",
['armor042'] = "Phá Phòng",
['armor043'] = "Xuyên Đâm",
['armor044'] = "Kim linh <font color='%s'>%s</font>",
['armor045'] = "Mộc linh <font color='%s'>%s</font>",
['armor046'] = "Thủy linh <font color='%s'>%s</font>",
['armor047'] = "Hỏa linh <font color='%s'>%s</font>",
['armor048'] = "Thổ Linh <font color='%s'>%s</font>",
['armor049'] = "Chưa kích hoạt",
['armor050'] = "<font color='#E59607' size='16'> Thuộc tính tổng tăng thêm </font><br/>%s",
['armor051'] = "<font color='#D5B772'>%s</font>  <font color='#00ff00'>%s</font>",
['armor052'] = "Bảo giáp cấp bậc không đủ, không cách nào kích hoạt",
['armor053'] = "Binh Linh cấp bậc",
['armor054'] = "<font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>%s</textformat>",
['armor055'] = "<font color='%s'> Bảo giáp đạt tới %s Giai có thể tùy ý kích hoạt Binh Linh: %s</font>",
['armor056'] = "<font color='%s'> Hiện tại bảo giáp %s Giai, có thể kích hoạt Binh Linh số lượng: %s</font>",
['armor057'] = "<font color='%s'> Bảo giáp đạt tới %s Giai, nhưng lần nữa kích hoạt Binh Linh: %s</font>",
['armor058'] = "<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Bảo giáp <font color='#00ff00'>%s Giai </font> Nhưng kích hoạt <font color='#00ff00'>%s Cái </font> Binh Linh",
['armor059'] = "( Có được:%s)";
['armor060'] = "%s/%s"
}
)
