StrConfig:Add
{
['newtianshen1'] = "Thiên thần",
-- Thiên thần thăng cấp
['newtianshen10'] = "Tiêu hao:<font>%sX%s</font>",
['newtianshen11'] = "( Có được:%s)",
['newtianshen12'] = "%s/%s",
['newtianshen13'] = "<font color = '#00b7ef'> Lam sắc phẩm chất </font>",
['newtianshen14'] = "<font color = '#cc00ff'> Tử sắc phẩm chất </font>",
['newtianshen15'] = "Hiện tại thiên thần đẳng cấp <font color='#00ff00'>%s</font>, có thể đem đẳng cấp truyền thừa đến tùy ý <font color='#00ff00'> Ra trận thiên thần </font>\n Chú: Mời ở phía dưới liệt biểu lựa chọn đẳng cấp không cao tại <font color='#00ff00'>%s Cấp </font> Thiên thần tiến hành truyền thừa",
['newtianshen16'] = "Hiện tại thiên thần Tinh cấp <font color='#00ff00'>%s</font>, có thể đem Tinh cấp truyền thừa đến <font color='#00ff00'> Đồng phẩm chất ra trận thiên thần </font>\n Chú: Mời ở phía dưới liệt biểu lựa chọn Tinh cấp không cao tại <font color='#00ff00'>%s Tinh </font> Thiên thần tiến hành truyền thừa",
['newtianshen17'] = "Trả về ngài một trương <font color ='#ffffff'> Bạch sắc </font> Thiên thần thẻ",
['newtianshen41'] = "Trả về ngài một trương <font color ='#00b7ef'> Lam sắc </font> Thiên thần thẻ",
['newtianshen18'] = 'Ngươi hợp thành mới thiên thần thẻ',
['newtianshen19'] = "Phải chăng muốn tiêu hủy thiên thần: \n<font color = '%s'>%s</font>( Tư chất: <font color = '%s'>%s</font>)?",
['newtianshen46'] = "Trả về: \n<font color='#ffffff'> Lam sắc trở lên trả về thiên thần thăng tinh thẻ <font>",
['newtianshen47'] = "Trả về: \n",
['newtianshen20'] = "<font size = '18'> Lần này hợp thành có <font color = '#00ff00'> Tỷ lệ nhất định </font> Thành công </font>\n Sau khi thành công thu hoạch được một trương mới <font color = '#b324f6'> Tử thiên thần thẻ </font>, sau khi thất bại thu hoạch được một trương mới <font color = '#00b7ef'> Lam sắc thiên thần thẻ </font>",
['newtianshen21'] = "<font size = '18'> Lần này hợp thành <font color = '#00ff00'> Nhất định thành công </font></font>\n Sau khi thành công thu hoạch được một trương mới <font color = '#00b7ef'> Lam sắc thiên thần thẻ </font>",
['newtianshen42'] = "Phải chăng dùng <font color='%s'>%s</font>( Tư chất:<font color='%s'>%s</font>) Thay thế đã ra trận <font color='%s'>%s</font>( Tư chất: <font color='%s'>%s</font>)?",
['newtianshen30'] = "<font color='#ffffff'> Bạch sắc </font>",
['newtianshen31'] = "<font color='#00b7ef'> Lam sắc </font>",
['newtianshen32'] = "<font color='#b324f6'> Tử sắc </font>",
['newtianshen33'] = "<font color='#ff6c00'> Cam sắc </font>",
['newtianshen34'] = "<font color='#dc1d03'> Đỏ sắc </font>",
['newtianshen35'] = "Mời để vào 10 Trương %s Thiên thần thẻ",
['newtianshen36'] = "<font color='#ea8d11'> Chủ Thần vị: </font>\n Chủ Thần vị ra trận thiên thần, nhưng mang ra tham chiến, đồng thời nhưng \n Sử dụng nộ khí kỹ năng tham dự chiến đấu.\n",
['newtianshen37'] = "<font color='#ea8d11'> Phó Thần vị: </font>\n Phó Thần vị ra trận thiên thần, không thể mang ra tham chiến, nhưng \n Thuộc tính cùng kỹ năng bị động sẽ toàn bộ kèm theo đến nhân vật chính trên thân.\n",
['newtianshen38'] = "<font color='#ea8d11'> Phó Thần vị ( Chưa giải khóa ): </font>\n Phó Thần vị ra trận thiên thần, không thể mang ra tham chiến, nhưng \n Thuộc tính cùng kỹ năng bị động sẽ toàn bộ kèm theo đến nhân vật chính trên thân.\n",
['newtianshen39'] = "<font color='#FFD099'> Ra trận thao tác: </font>\n Tại thiên thần xuất chiến trang ký, <font color='#fff000'> Trái khóa đơn kích </font> Phía bên phải thiên thần tại đạn \n Ra <font color='#fff000'> Liệt biểu </font> Bên trong tuyển chọn ra trận hoặc trực tiếp <font color='#fff000'> Phải khóa đơn kích </font> Thiên thần liệt \n Biểu liền có thể ra trận thiên thần",
['newtianshen40'] = "\n Chú: Nên trời Thần vị tại người chơi <font color ='#00ff00'>%s</font> Cấp giải tỏa",
['newtianshen43'] = "Cấp \n Giải tỏa",
['newtianshen44'] = "Bấm vào đây \n Ra trận thiên thần",
['newtianshen45'] = "Liệt biểu lựa chọn \n Ra trận thiên thần",
['newtianshen48'] = 'Thiên thần đẳng cấp đem tự động truyền thừa đến mới Thiên Thần bên trên',
['newtianshen49'] = 'Thiên thần Tinh cấp đem tự động truyền thừa đến mới Thiên Thần bên trên',
-- Nhắc nhở tin tức
['newtianshen100'] = "Vật phẩm không đủ",
['newtianshen101'] = "<font color='#f8af00'> Cần để vào 10 Trương <font color='#ffffff'> Bạch sắc phẩm chất </font> Thẻ phẩm </font>",
['newtianshen102'] = "<font color='#f8af00'> Cần để vào 10 Trương <font color='#00b7ef'> Lam sắc phẩm chất </font> Thẻ phẩm </font>",
['newtianshen103'] = 'Mời để vào Bạch sắc phẩm chất thiên thần thẻ',
['newtianshen104'] = 'Mời để vào Lam sắc phẩm chất thiên thần thẻ',
['newtianshen105'] = 'Không cách nào tiếp tục để vào tấm thẻ',
['newtianshen106'] = 'Mời thả đầy 10 Cái thiên thần thẻ',
['newtianshen107'] = 'Hiện tại xuất chiến thiên thần đã đủ',
['newtianshen108'] = 'Mời để vào %s Thiên thần thẻ',
['newtianshen109'] = "Ngài nhiều nhất có thể đồng thời có được 20 Cái thiên thần",
['newtianshen110'] = 'Giống nhau thiên thần chỉ có thể ra trận một cái',
['newtianshen111'] = 'Thấp hơn 80 Cấp không thể phá hủy thiên thần',
['newtianshen112'] = 'Thăng tinh thất bại',
['newtianshen113'] = 'Hiện tại không có có thể tiếp nhận đẳng cấp truyền thừa thiên thần',
['newtianshen114'] = 'Hiện tại không có có thể tiếp nhận Tinh cấp truyền thừa thiên thần',
['newtianshen115'] = 'Thiên thần đẳng cấp không thể vượt qua người chơi đẳng cấp',
['newtianshen116'] = 'Hiện tại thiên thần đã đạt tới lớn nhất Tinh cấp',
-- Miêu tả
['newtianshen201'] = "Thiên thần hệ thống <br>1. Đã kích hoạt thiên thần có thể lên trận trợ chiến, vì ngài cung cấp cường đại năng lực chiến đấu. Chú: Đồng loại thiên thần chỉ có thể xuất chiến 1 Cái <br>2. Chủ Thần vị thiên thần sẽ bị mang ra tham chiến, ngài có thể sử dụng kỹ năng chủ động, đồng thời tăng thêm thuộc tính cùng kỹ năng bị động, phó Thần vị thiên thần sẽ không ra chiến, chỉ tăng thêm thuộc tính cùng kỹ năng bị động.<br>3. Trái khóa Bấm vào thiên thần, nhưng tại bắn ra liệt biểu bên trong tiến hành bên trên, hạ trận thao tác. Phải khóa Bấm vào thiên thần cũng có thể tiến hành thiên thần bên trên, hạ trận thao tác <br>4. Ra trận thiên thần có thể tiến hành bồi dưỡng, tăng lên thuộc tính <br>5. Hạ trận thiên thần, có thể đem Tinh cấp, đẳng cấp truyền thừa đến đã ra trận thiên thần trên thân, nhưng trái khóa Bấm vào, tại bắn ra liệt biểu bên trong tuyển chọn truyền thừa <br>6. Nhiều nhất nhưng kích hoạt 20 Cái thiên thần, dư thừa thiên thần nhưng trái khóa Bấm vào lựa chọn tiêu hủy",
['newtianshen202'] = "Thiên thần bồi dưỡng <br>1. Ngài nhưng tại giới này trong mì tiến hành trời sinh'Thăng tinh' , 'Thăng cấp' Thao tác <br>2. [ Thiên thần thăng cấp ] Nhưng tiêu hao thăng cấp đan tăng lên thiên thần đẳng cấp, tăng lên thuộc tính. Thiên thần thăng cấp đan có thể thông qua dã ngoại treo máy, thiên thần phó bản thu hoạch được <br>3. [ Thiên thần thăng tinh ] Thiên thần có thể thông qua thôn phệ giống nhau phẩm chất thiên thần thẻ tăng lên Tinh cấp, từ đó tăng lên thuộc tính. Mỗi lần thăng tinh có nhất định tỉ lệ thành công. Khác biệt phẩm chất thiên thần, Tinh cấp hạn mức cao nhất khác biệt.",
['newtianshen203'] = "Thiên thần thẻ <br>1. Dã ngoại treo máy có thể thu hoạch được khác biệt tư chất, chủng loại thiên thần thẻ (60 Cấp về sau địa đồ bắt đầu rơi xuống )<br>2. Sử dụng thiên thần thẻ liền có thể kích hoạt thiên thần, tiến vào thiên thần hệ thống đem thiên thần ra trận, có thể vì ngài cung cấp cường đại năng lực chiến đấu",
['newtianshen204'] = "Thiên thần thăng tinh <br>1. Thiên thần có thể thông qua thôn phệ giống nhau phẩm chất thiên thần thẻ tăng lên Tinh cấp, từ đó tăng lên thuộc tính <br>2. Mỗi lần nhất định tiêu hao 10 Trương đồng phẩm chất thiên thần thẻ, đồng thời cũng có thể sử dụng chuyên môn thăng tinh thẻ. Chú: Thăng tinh thẻ là một loại đặc thù thiên thần thẻ, không thể kích hoạt thiên thần cũng không thể tiến hành hợp thành, chỉ có thể làm thăng tinh tiêu hao vật liệu <br>3. Thiên thần mỗi lần thăng tinh có nhất định tỉ lệ thành công <br>3. Khác biệt phẩm chất thiên thần thăng tinh hạn mức cao nhất khác biệt <br> Bạch sắc thiên thần cao nhất có thể thăng đến 2 Tinh <br> Lam sắc thiên thần cao nhất có thể thăng đến 4 Tinh <br> Tử sắc thiên thần cao nhất có thể thăng đến 6 Tinh <br> Cam sắc thiên thần cao nhất có thể thăng đến 8 Tinh <br> Đỏ sắc thiên thần cao nhất có thể thăng đến 10 Tinh",
['newtianshen205'] = "Thiên thần thăng cấp <br>1. Thiên thần nhưng tiêu hao thăng cấp đan tiến hành thăng cấp, thăng cấp sau có thể tăng lên thuộc tính. Thiên thần đẳng cấp không thể vượt qua nhân vật chính đẳng cấp <br>2. Thiên thần thăng cấp đan có thể thông qua dã ngoại treo máy, thiên thần phó bản thu hoạch được <br>3. Bấm vào [ Thăng cấp ], nhưng tiêu hao một cái thăng cấp đan, tăng lên cố định điểm kinh nghiệm.<br>4. Bấm vào [ Lên thẳng cấp một ], nhiều nhất sẽ tiêu hao hết có thể trực tiếp tăng lên 1 Cấp thăng cấp đan, như Hiện tại thăng cấp đan tổng lượng không đủ tăng lên 1 Cấp, thì toàn bộ tiêu hao hết",
['newtianshen206'] = "Thiên thần truyền thừa <br>1. Không lên trận thiên thần, có thể đem Tinh cấp, đẳng cấp truyền thừa đến đã ra trận thiên thần bên trên.<br>2. [ Truyền thừa Tinh cấp ] Chỉ có thể truyền thừa cho đồng phẩm chất thiên thần, bị truyền thừa thiên thần Tinh cấp cần thấp hơn truyền thừa thiên thần <br>3. [ Truyền thừa đẳng cấp ] Có thể đem đẳng cấp truyền thừa cho cấp bậc không cao tại tự thân tùy ý phẩm chất thiên thần",
['newtianshen207'] = "Thiên thần hợp thành <br>1. [ Hợp thành Lam sắc phẩm chất ]10 Cái Bạch sắc phẩm chất thiên thần thẻ nhưng hợp thành 1 Cái Lam sắc phẩm chất ngẫu nhiên chủng loại thiên thần, hợp thành nhất định thành công <br>2. [ Hợp thành tử sắc phẩm chất ]10 Cái Lam sắc phẩm chất thiên thần thẻ nhưng hợp thành 1 Cái tử sắc phẩm chất ngẫu nhiên chủng loại thiên thần, hợp thành có nhất định tỉ lệ thành công, như hợp thành thất bại thì ngẫu nhiên trả về 1 Cái Lam sắc phẩm chất thiên thần thẻ <br>3. Người chơi cấp bậc càng cao, hợp thành thiên thần thẻ chủng loại càng nhiều",
}
