UIStrConfig:Add
{
['newtianshen1'] = 'Xuất chiến',
['newtianshen2'] = 'Bồi dưỡng',
['newtianshen3'] = 'Phân giải',
['newtianshen4'] = "<font color='#ffffff'> Bạch </font>",
['newtianshen5'] = "<font color='#00b7ef'> Lam </font>",
['newtianshen6'] = "<font color='#b324f6'> Tử </font>",
['newtianshen7'] = "<font color='#ff6c00'> Cam </font>",
['newtianshen8'] = "<font color='#dc1d03'> Đỏ </font>",
['newtianshen9'] = 'Xác định',
-- Thiên thần thăng cấp
['newtianshen10'] = 'Thăng cấp',
['newtianshen11'] = 'Thăng nhanh',
['newtianshen12'] = 'Hợp thành',
['newtianshen13'] = 'Truyền thừa đẳng cấp',
['newtianshen14'] = 'Truyền thừa Tinh cấp',
['newtianshen15'] = 'Xác nhận truyền thừa',
['newtianshen16'] = 'Để vào',
['newtianshen17'] = 'Hợp thành',
['newtianshen18'] = "Hợp thành màu lam",
['newtianshen19'] = 'Hợp thành tử sắc',
['newtianshen20'] = 'Ra trận',
['newtianshen23'] = 'Hạ trận',
['newtianshen21'] = 'Tiêu hủy',
['newtianshen24'] = 'Bồi dưỡng',
['newtianshen22'] = 'Hủy bỏ tự động',
['newtianshen25'] = 'Thăng cấp',
['newtianshen26'] = 'Thăng tinh',
['newtianshen27'] = "Giao diện",
['newtianshen28'] = 'Truyền thừa',
['newtianshen29'] = '<u> Ba lô </u>',
['newtianshen30'] = 'Thăng tinh',
['newtianshen31'] = '<u> Hợp thành </u>',
['newtianshen32'] = 'Đã đủ cấp',
['newtianshen33'] = 'Đã đủ tinh'
}
