StrConfig:Add(
{
['linglihuizhang1'] = "Miễn phí (%s)",
['linglihuizhang2'] = "Linh lực không đủ",
['linglihuizhang3'] = "Nguyên bảo không đủ",
['linglihuizhang4'] = "Điều kiện không đủ, không cách nào đột phá",
['linglihuizhang5'] = "%s /%s Phút",
['linglihuizhang6'] = "Chỉ có VIP Mới có thể đi vào đi VIP Chú linh",
['linglihuizhang7'] = "Lần này cần tiêu hao <font color='#31b84e'>%s</font> Linh lực <br/> Phổ thông tăng lên có khá thấp tỉ lệ phát động nhiều lần tăng trưởng",
['linglihuizhang8'] = "Lần này cần tiêu hao <font color='#d2a930'>%s</font> Nguyên bảo <br/>VIP Tăng lên có tương đối cao tỉ lệ phát động nhiều lần tăng trưởng <br/>VIP Người chơi mỗi ngày có thể miễn phí sử dụng vip Tăng lên, tăng lên VIP Đẳng cấp có thể đạt được  càng nhiều miễn phí số lần",
['linglihuizhang9'] = "Lần này đột phá cần tiêu hao:%s",
['linglihuizhang10'] = "%s ( %s) /%s Phút",
['linglihuizhang11'] = "Đánh giết quái vật có nhất định tỉ lệ thu hoạch được linh lực, mỗi ngày nhiều nhất %s Điểm",
['linglihuizhang12'] = "<font color='#848484'>(VIP1 Sản lượng tăng lên %s%%)</font>",
['linglihuizhang13'] = "<font color='#00ff00'>(VIP%s Sản lượng tăng lên %s%%)</font>",
['linglihuizhang14'] = "<font color='#29cc00'><u> Kích hoạt bạch ngân VIP</u></font>",
['linglihuizhang15'] = "<font color='#29cc00'><u> Tăng lên VIP</u></font>",
['linglihuizhang16'] = "<font color='#464646'>(VIP1 Thu hoạch hạn mức cao nhất tăng lên 20%)</font>",
['linglihuizhang17'] = "<font color='#848484'>(VIP%s Thu hoạch hạn mức cao nhất tăng lên %s%%)</font>",
['linglihuizhang18'] = "<font color='#32961e'>%s%s </font><font color='#215e14'>( Hiện tại %s)</font>",
['linglihuizhang19'] = "<font color='#960000'>%s%s ( Hiện tại %s)</font>",
['linglihuizhang20'] = "<font color='#215e14'> Hiện tại %s</font>",
['linglihuizhang21'] = "<font color='#960000'> Hiện tại %s</font>",
['linglihuizhang22'] = "<font color='#32961e'>%s%s Cái </font><font color='#215e14'>( Hiện tại %s Cái )</font>",
['linglihuizhang23'] = "<font color='#960000'>%s%s Cái ( Hiện tại %s Cái )</font>",
['linglihuizhang24'] = "<font color='#215e14'> Hiện tại %s Cái </font>",
['linglihuizhang25'] = "<font color='#960000'> Hiện tại %s Cái </font>",
['linglihuizhang26'] = "<font color='#5a5a5a'>(VIP1 Sản lượng tăng lên %s%%) </font><font color='#ff0000'> Chưa kích hoạt </font>",
['linglihuizhang27'] = "(VIP%s Sản lượng tăng lên %s%%) <font color='#00ff00'> Đã kích hoạt </font>",
['linglihuizhang28'] = "%s ( %s) /%s Phút %s",
['linglihuizhang29'] = "<font color='#eeeeee'>( Cấp tiếp theo %s ( %s) /%s Phút )</font>",
['linglihuizhang30'] = "%s",
['linglihuizhang31'] = "<font color='#00b7ef' size='18'> Tông môn </font><br/> Mở ra sau nhưng tự động tính gộp lại linh lực, đồng thời giết quái <br/> Nhưng ngoài định mức thu hoạch được đại lượng linh lực <br/><font color='#960000'> Hoàn thành %s Cấp nhiệm vụ chính tuyến sau mở ra </font>",
['linglihuizhang32'] = "<font color='#32961e'> Mỗi ngày VIP Tăng lên còn thừa %s Lần miễn phí </font>",
['linglihuizhang33'] = "<font color='#960000'> Mỗi ngày VIP Tăng lên còn thừa 0 Lần miễn phí </font>",
['linglihuizhang34'] = "<font color='#00ff00'> Điểm kích này nút bấm mở ra [ Tông môn ] Giao diện </font>",
['linglihuizhang35'] = "Tạm thời chưa có bất luận cái gì thuộc tính tăng thêm",
['linglihuizhang36'] = "Thuộc tính tăng thêm",
['linglihuizhang37'] = "%s /%s Phút %s",
['linglihuizhang38'] = "<font color='#eeeeee'>( Cấp tiếp theo %s /%s Phút )</font>",
['linglihuizhang39'] = "Tông môn tích lũy linh lực đã đủ <br/><font color='#29cc00'> Mời kịp thời nhận lấy </font>",
['linglihuizhang40'] = "<br/> Tông môn có linh lực có thể nhận lấy <br/> Nhưng nhận lấy linh lực <font color='#29cc00'>%s</font>",
['linglihuizhang41'] = "VIP Đã đạt cao cấp nhất",
['linglihuizhang42'] = "Nhận lấy ích lợi thành công!",
}
);
