StrConfig:Add(
{
['consignment001'] = "%s",
['consignment002'] = "%s Ngày %s Giờ %s Phút",
['consignment003'] = "Ngươi muốn hủy bỏ tất cả vật phẩm đang bán ra?",
['consignment004'] = "%s/%s",
['consignment005'] = "Vật phẩm treo giá không tồn tại, hãy chọn lại vật phẩm treo giá!",
['consignment006'] = "Số lượng treo giá sai, mời điều chỉnh!",
['consignment007'] = "Ngươi xác định lấy 0 Ngân lượng treo giá vật phẩm đấy sao?",
['consignment008'] = "Số lần treo giá không đủ!",
['consignment009'] = "Mua sắm thành công",
['consignment010'] = "Nguyên bảo không đủ",
['consignment011'] = "Ngươi mua vật phẩm số lượng không đủ hoặc đã loại bỏ!",
['consignment012'] = "Loại bỏ thành công!",
['consignment013'] = "Toàn bộ loại bỏ thành công!",
['consignment014'] = "Treo giá thành công",
['consignment015'] = "Vật phẩm treo giá",
['consignment016'] = "Hủy bỏ treo giá",
['consignment017'] = "Vật phẩm đấy đã khóa lại, không thể treo giá!",
['consignment018'] = "Vật phẩm đơn giá: <font color='#29cc00'>%s</font> Nguyên bảo",
['consignment019'] = "Mời chọn vật phẩm muốn mua!",
['consignment020'] = "Không có vật phẩm phù hợp!",
['consignment021'] = "Đổi mới",
['consignment022'] = "Tìm",
['consignment023'] = "Số lượng là số không, không thể mua sắm!",
['consignment024'] = "Giá cả là số không, không thể treo giá!",
['consignment032'] = "Giá phải lớn hơn 1 Nguyên bảo!",
['consignment025'] = "Không thể mua vật phẩm của mình!",
['consignment026'] = "Vật phẩm đã loại bỏ hoặc đã bị mua",
['consignment027'] = "Ba lô đầy",
['consignment028'] = "Nguyên bảo không đủ",
['consignment029'] = "Ba lô đầy",
['consignment030'] = "Thất bại",
['consignment031'] = "Vật phẩm đấy không tồn tại, khả năng đã loại bỏ hoặc đã bị mua sắm!",
['consignment040'] = "Thành công bán đi sau thu lấy giao dịch thuế 5%",
['consignment999'] = "Hiện tại vật phẩm tạm không ủng hộ lên khung bán ra!",
-- ['consignment101'] = 'Vũ khí',
-- ['consignment102'] = 'Đồ phòng ngự',
-- ['consignment103'] = 'Trang sức',
['consignment101'] = 'Trang bị',
-- ['consignment102'] = 'Pháp bảo',
['consignment102'] = 'Đạo cụ',
-- ['consignment106'] = 'Cái khác',
['consignment201'] = 'Sách kỹ năng',
['consignment202'] = 'Thăng giai thạch',
['consignment203'] = 'Chế tạo vật liệu',
['consignment204'] = 'Vé vào cửa',
['consignment205'] = 'Cái khác',
['consignment301'] = 'Vũ khí',
['consignment302'] = 'Áo',
['consignment303'] = 'Quần',
['consignment304'] = 'Giày',
['consignment305'] = 'Hộ thủ',
['consignment306'] = 'Hộ kiên',
['consignment307'] = 'Mũ giáp',
['consignment308'] = 'Dây chuyền',
['consignment309'] = 'Bùa hộ mệnh',
['consignment310'] = 'Nhẫn trái',
['consignment311'] = 'Nhẫn phải',
['consignment501'] = 'Nhất giai pháp bảo',
['consignment502'] = 'Nhị giai pháp bảo',
['consignment503'] = 'Tam giai pháp bảo',
['consignment504'] = 'Tứ giai pháp bảo',
['consignment505'] = 'Ngũ giai pháp bảo',
-- Trác tuyệt thuộc tính
['consigsuperatb101'] = "Toàn trác tuyệt thuộc tính",
['consigsuperatb102'] = "Trác tuyệt đơn thuộc tính",
['consigsuperatb103'] = "Trác tuyệt song thuộc tính",
['consigsuperatb104'] = "Trác tuyệt ba thuộc tính",
['consigsuperatb105'] = "Trác tuyệt bốn thuộc tính",
-- Lên khung thời gian
['consignmentupitem1'] = "12 Giờ",
['consignmentupitem2'] = "24 Giờ",
['consignmentupitem3'] = "48 Giờ",
['consignmentupitem4'] = "72 Giờ",
['consignmentQuality1'] = "Màu lam trở lên phẩm chất",
['consignmentQuality2'] = "Tử sắc trở lên phẩm chất",
['consignmentQuality3'] = "Thần đúc 1 Trở lên phẩm chất",
['consignmentQuality4'] = "Thần đúc 2 Trở lên phẩm chất",
['consignmentQuality5'] = "Thần đúc 3 Phẩm chất",
-- wqn Gia tăng quy tắc nói rõ
['consignmentRule1'] =[[<font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Người chơi nhưng tại hãng giao dịch bên trong tự do giao dịch không phải khóa lại vật phẩm.<img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thành công giao dịch vật phẩm sẽ thu lấy 5% Giao dịch thuế, giao dịch thuế từ người bán thanh toán.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Hãng giao dịch sử dụng Nguyên bảo vì lưu thông tiền tệ.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Hãng giao dịch bên trong mua sắm vật phẩm lúc tiêu hao Nguyên bảo không đưa vào VIP Đẳng cấp kinh nghiệm, không đưa vào tiêu phí trở lại lợi hoạt động.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thành công giao dịch sau người bán lấy được Nguyên bảo thông qua bưu kiện gửi đi.
</textformat>]],
}
)
