UIStrConfig:Add(
{
['consignui001'] = 'Sử dụng đẳng cấp',
['consignui002'] = 'Phẩm chất',
['consignui003'] = 'Trác tuyệt thuộc tính',
['consignui004'] = 'Có thể dùng vật phẩm',
['consignui005'] = 'Tìm',
['consignui006'] = 'Thiết lập lại',
['consignui007'] = 'Tên vật phẩm       Đẳng cấp   Số lượng       Người bán       Đơn giá    Tổng giá trị',
['consignui008'] = 'Hiện tại có được:',
['consignui009'] = 'Mua',
['consignui010'] = 'Xác nhận',
['consignui011'] = 'Hủy bỏ',
['consignui012'] = 'Đơn giá:',
['consignui013'] = 'Số lượng mua:',
['consignui014'] = 'Tổng giá trị cần:',
['consignui015'] = 'Xem',
['consignui016'] = 'Bán ra',
['consignui017'] = 'Lợi ích',
['consignui018'] = 'Loại bỏ',
['consignui019'] = 'Vật phẩm treo giá',
['consignui020'] = 'Loại bỏ toàn bộ',
['consignui021'] = '  Vật phẩm tên           Đẳng cấp       Số lượng        Còn thừa thời gian           Đơn giá ',
['consignui022'] = 'Tên vật phẩm        Số lượng        Giao dịch hoàn thành thời gian            Người mua           Ích lợi ',
['consignui023'] = 'Lên một lượt đỡ vật phẩm số: ',
['consignui024'] = 'Xác nhận',
['consignui025'] = 'Hủy bỏ',
['consignui026'] = 'Số lượng',
['consignui027'] = 'Tổng giá trị',
['consignui028'] = 'Ngân lượng',
['consignui029'] = 'Nguyên bảo',
['consignui030'] = 'Thời hạn bán ra',
['consignui031'] = 'Giá cả',
['consignui032'] = 'Giao dịch nhận được',
['consignui033'] = 'Tên vật phẩm',
['consignui034'] = 'Số lượng',
['consignui035'] = 'Thời gian hoàn thành giao dịch',
['consignui036'] = 'Người mua',
['consignui037'] = 'Ích lợi',
['consignui038'] = 'Đẳng cấp',
['consignui039'] = 'Còn thừa thời gian',
['consignui040'] = 'Người bán ra',
['consignui041'] = 'Tổng giá trị',
}
)
