StrConfig:Add(
{
-- Ngọc bội bảng
['mingYu001'] = 'Ngọc bội cấp bậc',
['mingYu002'] = '<font color="#e59607"> Trước mắt ngọc bội độ thuần thục đẳng cấp: </font><font color="#dcdcdc">%s%s</font><font color="#e56a10"> Mỗi lần phát động <font color="#00b7ef">%s</font> Lúc, độ thuần thục đều sẽ tăng lên </font>',
['mingYu003'] = "Đã thăng đến cao giai nhất",
['mingYu004'] = "Công  Kích: %s",
['mingYu005'] = "Phòng  Ngự: %s",
['mingYu006'] = "Bạo  Kích: %s",
['mingYu007'] = "Sinh  Mệnh: %s",
['mingYu008'] = "Bạo  Tổn thương: %s",
['mingYuplus009'] = "Chính  Xác: %s",
['mingYuplus010'] = "Né  Tránh: %s",
['mingYuplus011'] = "SM tối đa: %s",
['mingYu009'] = "<font color='#29cc00'> Đã đạt tới trước mắt cấp bậc tối cao độ thuần thục đẳng cấp </font>",
-- Ngọc bội tiến giai bảng
['mingYu010'] = "Tiến giai tiêu hao: ",
['mingYu011'] = "Ngân lượng: ",
['mingYu012'] = "<u><font color='%s'>%s%s Khỏa </font></u>",
-- Ngọc bội kỹ năng thăng cấp bảng
['mingYu013'] = "%s:<br><font color='#c8c8c8'>1, giai vị:<font color='%s'>%s Giai %s</font><br>2, cần tiêu hao đạo cụ:</font>",
['mingYu014'] = "Đạo cụ không đủ",
['mingYu015'] = "Ngọc bội cấp bậc không đủ",
['mingYu016'] = "Đã tập được",
['mingYu017'] = "Chưa tập được",
['mingYu018'] = "( Đã đạt thành )",
['mingYu019'] = "( Chưa đạt thành )",
-- Nhắc nhở tin tức
['mingYu020'] = "Độ thuần thục không đủ",
['mingYu021'] = "Ngân lượng không đủ",
['mingYu022'] = "Đạo cụ số lượng không đủ",
['mingYu023'] = "Độ thuần thục đầy sau mới có thể thăng giai",
['mingYu024'] = "<font color='#e59607'> Trước mắt chúc phúc giá trị: <font color='#dcdcdc'>%s</font></font><br/><font color='#e59607'> Chúc phúc giá trị thanh không tình trạng: </font><font color='#e56a10'> Chúc phúc giá trị tại mỗi ngày rạng sáng <font color='#00ff00'>6 Điểm </font> Về không </font><br/><font color='#e59607'> Chúc phúc giá trị nói rõ: </font><br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi lần chưa thể thành công tiến giai, đều đem tăng lên chúc phúc giá trị.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị càng cao, lần sau thao tác xác suất thành công càng cao.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị thăng đầy sau, thì lần sau thăng giai thao tác nhất định thành công </font>",
['mingYu025'] = "Trước mắt kỹ năng đã thăng đến đẳng cấp cao nhất",
['mingYu026'] = "Độ thuần thục: ",
['mingYu027'] = "Thắp sáng hạ khỏa tinh có thể gia tăng như sau thuộc tính: \n%s",
['mingYu028'] = "Ngọc bội kỹ năng",
['mingYu029'] = "Thăng cấp điều kiện",
['mingYu030'] = "Điều kiện học tập",
['mingYu031'] = "Thăng cấp kỹ năng",
['mingYu032'] = "Học tập kỹ năng",
['mingYu033'] = "Độ thuần thục đầy sau có thể thăng giai",
['mingYu034'] = "Đạo cụ không đủ, không cách nào tiến giai",
['mingYu035'] = "Ngân lượng không đủ, không cách nào tiến giai",
['mingYu036'] = "Công Kích",
['mingYu037'] = "Phòng Ngự",
['mingYu038'] = "Sinh Mệnh",
['mingYu039'] = "Bạo Kích",
['mingYu040'] = "Chính  Xác",
['mingYu041'] = "Bạo Tổn thương",
['mingYu042'] = "Phá Phòng",
['mingYu043'] = "Xuyên Đâm",
['mingYu044'] = "Kim linh <font color='%s'>%s</font>",
['mingYu045'] = "Mộc linh <font color='%s'>%s</font>",
['mingYu046'] = "Thủy linh <font color='%s'>%s</font>",
['mingYu047'] = "Hỏa linh <font color='%s'>%s</font>",
['mingYu048'] = "Thổ Linh <font color='%s'>%s</font>",
['mingYu049'] = "Chưa kích hoạt",
['mingYu050'] = "<font color='#E59607' size='16'> Thuộc tính tổng tăng thêm </font><br/>%s",
['mingYu051'] = "<font color='#D5B772'>%s</font>  <font color='#00ff00'>%s</font>",
['mingYu052'] = "Ngọc bội cấp bậc không đủ, không cách nào kích hoạt",
['mingYu053'] = "Binh Linh cấp bậc",
['mingYu054'] = "<font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>%s</textformat>",
['mingYu055'] = "<font color='%s'> Ngọc bội đạt tới %s Giai có thể tùy ý kích hoạt Binh Linh: %s</font>",
['mingYu056'] = "<font color='%s'> Trước mắt ngọc bội %s Giai, còn có thể tùy ý kích hoạt Binh Linh số lượng: %s</font>",
['mingYu057'] = "<font color='%s'> Ngọc bội đạt tới %s Giai, nhưng lần nữa kích hoạt Binh Linh: %s</font>",
['mingYu058'] = "<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Ngọc bội <font color='#00ff00'>%s Giai </font> Nhưng kích hoạt <font color='#00ff00'>%s Cái </font> Binh Linh",
['mingYu059'] = "( Có được:%s)";
['mingYu060'] = "%s/%s"
}
)
