StrConfig:Add(
{
['bag1'] = 'Dùng nhiều',
['bag2'] = 'Số Lượng: ',
['bag3'] = 'Sử dụng: ',
['bag4'] = 'Không thể sử dụng',
['bag5'] = 'Không thể vứt bỏ',
['bag6'] = 'Xác định vứt bỏ vật phẩm?',
['bag7'] = 'Tách vật phẩm',
['bag8'] = 'Số lượng',
['bag9'] = 'Chia tách vật phẩm: ',
['bag10'] = "<font color='#dcdcdc'> Điểm kích ngăn chứa nhưng phát triển %s Dung lượng </font><br/><font color='#e56a10'>%s Phát triển sau có thể đạt được  thuộc tính ban thưởng </font>",
['bag11'] = 'Tồn nhập',
['bag12'] = 'Lấy ra',
['bag13'] = 'Sử dụng',
['bag14'] = 'Chia tách',
['bag15'] = 'Trang bị',
['bag16'] = 'Gỡ xuống trang bị',
['bag17'] = 'Hợp thành',
['bag18'] = 'Hiển thị',
['bag19'] = 'Phá hủy',
['bag20'] = 'Bán ra',
['bag21'] = "<font color='#df8B1e'>%s</font>x<font color='#df8B1e'>%s</font>",
['bag22'] = "Chuẩn bị mở ngăn chứa: <font color='#00ff00'>%s ngăn chứa </font>",
['bag23'] = "【%s】 Cái mới %s Ngăn chứa <br/> Sinh mệnh tối đa: <font color='#29cc00'> %s</font><br/> Kinh nghiệm: <font color='#29cc00'> %s</font>",
['bag24'] = "%s Giờ %s Phút %s Giây",
['bag25'] = "Tốn hao: <font color='#cc0000'>%s</font>",
['bag26'] = "Tốn hao: <font color='#ffcc33'>%s</font>",
['bag27'] = "Điều kiện không đủ, không thể mở rộng",
['bag28'] = "<font color='#508cd2'><font color='#dcdcdc'> Ngân lượng có thể dùng tại người chơi ở giữa giao dịch cùng mua sắm cửa hàng đạo cụ </font><br/> Thông qua hoàn thành nhiệm vụ, người chơi ở giữa giao dịch các phương thức có thể đạt được  ngân lượng </font>",
['bag29'] = "<font color='#508cd2'><font color='#dcdcdc'> Ngân lượng chỉ có thể dùng cho cửa hàng mua sắm, không cách nào dùng cho giao dịch </font><br/> Thông qua hoàn thành nhiệm vụ, giết quái rơi xuống, hoàn thành phó bản các phương thức có thể đạt được  ngân lượng </font>",
['bag30'] = "<font color='#508cd2'><font color='#dcdcdc'> Nguyên bảo có thể dùng tại trong Thương Thành quý giá đạo cụ mua sắm </font><br/> Nguyên bảo chỉ có thể thông qua nạp tiền cùng hoạt động thu hoạch được </font>",
['bag31'] = "<font color='#508cd2'><font color='#dcdcdc'> Buộc nguyên có thể dùng tại buộc nguyên thương thành mua sắm, không cách nào dùng cho giao dịch </font><br/> Thông qua hoàn thành trong trò chơi hoạt động cùng online có thể thu hoạch được đại lượng buộc nguyên </font>",
['bag32'] = [[ Thứ 【%s】 Cách %s Đang trong quá trình mở ra, còn thừa thời gian: <font color='#65c47e'>%s Giờ %s Phút %s Giây </font><img height='10'/>
Bảo trì online có thể tự động mở ra ba lô cách, điểm kích ngăn chứa có thể gia tốc mở ra
<font color='#b86f11'> Mở ra mới ngăn chứa, có thể thu hoạch được nhân vật thuộc tính </font>]],
['bag33'] = "Mở ra %s Ngăn chứa, thu hoạch được thuộc tính ban thưởng",
['bag34'] = "Sinh mệnh tối đa <font color='#29cc00'>%s</font>",
['bag35'] = "Kinh nghiệm <font color='#29cc00'>%s</font>",
['bag36'] = 'Nhanh chóng bán ra',
['bag37'] = 'Hủy bỏ',
['bag38'] = "Còn trống: <font color='#09d31c'>%s/%s</font>",
['bag39'] = "Còn trống: <font color='#09d31c'>%s/%s</font>",
['bag40'] = "Còn trống: <font color='#09d31c'>%s/%s</font>",
['bag41'] = "Còn trống: <font color='#09d31c'>%s/%s</font>",
['bag42'] = "Còn trống: <font color='#09d31c'>%s/%s</font>",
['bag43'] = "Còn trống: <font color='#09d31c'>%s/%s</font>",
['bag44'] = "Ấm áp nhắc nhở: <br/>  Có thể dùng lôi kéo hoặc phải khóa phương thức đem vật phẩm tiến hành tồn nhập / Lấy ra <br/>  Bảo trì online đem tự động mở ra nhà kho cách <br/>  Nhưng tiêu hao đạo cụ hoặc Nguyên bảo tới mở càng nhiều nhà kho cách",
['bag45'] = "Phá hủy thành công",
['bag46'] = "Bán ra thành công",
['bag47'] = "Điểm kích bên trong túi đeo lưng vật phẩm tiến hành bán ra, song kích đất trống hủy bỏ",
['bag48'] = "Trang bị sau đem khóa lại, khóa lại trang bị không cách nào tiến hành giao dịch, phải chăng xác định trang bị?",
['bag49'] = "Hiện tại có được số lượng: <font color='#00ff00'>%s</font>",
['bag50'] = 'Ba lô mở rộng',
['bag51'] = 'Nhà kho mở rộng',
['bag52'] = "Giao dịch bên trong không thể chỉnh lý ba lô",
['bag53'] = "Nên đạo cụ đã đạt hôm nay sử dụng hạn mức cao nhất",
['bag54'] = "Nên đạo cụ đã đạt sử dụng hạn mức cao nhất",
['bag55'] = "Nên đạo cụ hôm nay chỉ có thể tái sử dụng %s Lần",
['bag56'] = "Nên đạo cụ chỉ có thể tái sử dụng %s Lần",
['bag57'] = "Điểm kích bên trong túi đeo lưng vật phẩm tiến hành lên khung, song kích đất trống hủy bỏ",
['bag58'] = "Chúc mừng ngài tự động mở ra ba lô ngăn chứa",
['bag60'] = 'Tục phí',
['bag61'] = 'Phải chăng xác nhận sử dụng <font color="%s">%s</font>?<br/> Tiêu hao %s Nguyên bảo',
['bag611'] = "Còn cần <font color='#ff0000'>%s</font> Nguyên bảo mở ra gói quà <br/> Lập tức tiến về nạp tiền",
['bag62'] = 'Ngài thu hoạch được trở xuống ban thưởng: ',
["bag63"] = "<font color='#ff0000'>%s Giây </font><font color='#00ff00'> Sau tự động đóng </font>",
['bag64'] = 'Trang bị',
['bag65'] = 'Thăng cấp',
['bag66'] = 'Hợp thành',
['bag100'] = 'Đã khóa lại',
['bag101'] = 'Thu hoạch sau khóa lại',
['bag102'] = 'Không khóa lại',
['bag103'] = 'Sử dụng sau khóa lại',
['bag104'] = 'Đã khóa lại',
['bag201'] = "Trở lên là ngài trong hành trang phù hợp ngài đẳng cấp 【%s】<br/> Lựa chọn sau liền có thể đeo",
['bag20000001'] = "Trở lên là ngài trong hành trang phù hợp ngài đẳng cấp 【 Cánh 】 Lựa chọn sau liền có thể đeo",
['bag202'] = "Rất xin lỗi, ngài trong hành trang tạm thời chưa có phù hợp ngài đẳng cấp <br/>【%s】 Tồn tại",
['bag20000002'] = "Rất xin lỗi, ngài trong hành trang tạm thời chưa có phù hợp ngài đẳng cấp 【 Cánh 】 Tồn tại",
['bag300'] = "<font color='#00ff00'> Bang phái mở rộng thành công, có thể dung nạp nhân số gia tăng </font>",
['bag301'] = 'Mỗi cái bang phái chỉ có thể phát triển một lần',
['bag302'] = 'Vẻn vẹn bang chủ nhưng phát triển',
['bag303'] = 'Đạo cụ sai lầm',
['bag10001'] = "Lực chiến: %s",
['bagerror1'] = "Không thể sử dụng",
['bagerror2'] = "Giới tính không hợp",
['bagerror3'] = "Nghề nghiệp không hợp",
['bagerror4'] = "Cấp bậc chưa đủ",
['bagerror5'] = "Tọa kỵ cấp bậc không đủ",
['bagerror6'] = "Vật phẩm CD Bên trong",
['bagerror7'] = "Cảnh giới cấp bậc chưa đủ",
['bagerror8'] = "Nên trang bị không cách nào tiến hành mặc",
['bagerror9'] = "Linh thú cấp bậc không đủ",
['bagerror10'] = "Linh thú tọa kỵ cấp bậc không đủ",
['bagerror20'] = "Không thể bán ra",
-- Trang bị phẩm chất
['bagProduct1'] = "Phổ thông",-- Bạch
['bagProduct2'] = "Tinh lương",-- Lam
['bagProduct3'] = "Hi hữu",-- Tử
['bagProduct4'] = "Truyền thuyết",-- Cam
['bagProduct5'] = "Thần thoại",-- Đỏ
['bagProduct6'] = "Thần đúc 1",-- Lục 1
['bagProduct7'] = "Thần đúc 2",-- Lục 2
['bagProduct8'] = "Thần đúc 3",-- Lục 3
['bagerror11'] = "Linh trận cấp bậc không đủ",
['bagerror12'] = "Kỵ chiến cấp bậc không đủ",
['bagerror13'] = "Thần linh cấp bậc không đủ",
['bagerror14'] = "Thần binh cấp bậc không đủ",
['bagerror15'] = "Pháp bảo cấp bậc không đủ",
['bagerror16'] = "Ngọc bội cấp bậc không đủ",
['bagerror17'] = "Bảo giáp cấp bậc không đủ",
['bag00001'] = "Công năng chưa mở, %s Cấp mở ra!",
}
);
