_G.t_equipdescribe={
[1]={
['id'] = 1,
['name'] = "Bộ Nhất Giai Thần Trang",
['quality'] = "5,6,7",
['baseAttr'] = "att,112#def,56#hp,1122",
['describe'] = "Thu thập mặc đủ 11 trang bị nhất giai trở lên thần trang sau kích hoạt",
},
[2]={
['id'] = 2,
['name'] = "Bộ Nhị Giai Thần Trang",
['quality'] = "5,6,7",
['baseAttr'] = "att,224#def,112#hp,2244",
['describe'] = "Thu thập mặc đủ 11 trang bị nhị giai trở lên thần trang sau kích hoạt",
},
[3]={
['id'] = 3,
['name'] = "Bộ Tam Giai Thần Trang",
['quality'] = "5,6,7",
['baseAttr'] = "att,449#def,224#hp,4488",
['describe'] = "Thu thập mặc đủ 11 trang bị tam giai trở lên thần trang sau kích hoạt",
},
[4]={
['id'] = 4,
['name'] = "Bộ Tứ Giai Thần Trang",
['quality'] = "5,6,7",
['baseAttr'] = "att,898#def,449#hp,8976",
['describe'] = "Thu thập mặc đủ 11 trang bị tứ giai trở lên thần trang sau kích hoạt",
},
[5]={
['id'] = 5,
['name'] = "Bộ Ngũ Giai Thần Trang",
['quality'] = "5,6,7",
['baseAttr'] = "att,1795#def,898#hp,17952",
['describe'] = "Thu thập mặc đủ 11 trang bị ngũ giai trở lên thần trang sau kích hoạt",
},
[6]={
['id'] = 6,
['name'] = "Bộ Lục Giai Thần Trang",
['quality'] = "5,6,7",
['baseAttr'] = "att,3590#def,1795#hp,35904",
['describe'] = "Thu thập mặc đủ 11 trang bị lục giai trở lên thần trang sau kích hoạt",
},
[7]={
['id'] = 7,
['name'] = "Bộ Thất Giai Thần Trang",
['quality'] = "5,6,7",
['baseAttr'] = "att,7181#def,3590#hp,71808",
['describe'] = "Thu thập mặc đủ 11 trang bị thất giai trở lên thần trang sau kích hoạt",
},
};
