_G.t_guildActivity={
[1]={
['id'] = 1,
['name'] = "Địa cung Luyện Ngục",
['openTime'] = "00:00:00",
['ifShowChat'] = 0,
['openParam1'] = "",
['openParam2'] = "",
['duration'] = 10080,
['guildlv'] = 1,
['des'] = "<br/><br/><font color='#00ff00'> Có thể thoải mái tiến vào, mỗi tuần thiết lập lại </font><br/><br/><br/> Vô tận địa cung Luyện Ngục, khiêu chiến chư điện điện chủ, thành công có thể đạt được phần thưởng lớn!",
['tipdes'] = "",
['time'] = 1,
['reward'] = "151100042#151100052#151100062",
['name_img'] = "guild_act_1.png",
['bg_img'] = "guild_act_bg_1.jpg",
['notice_img'] = "guild_act_notice_1",
},
[2]={
['id'] = 2,
['name'] = "Bang phái chiến",
['openTime'] = "21:00:00",
['ifShowChat'] = 1,
['openParam1'] = "3",
['openParam2'] = "2,4,6",
['duration'] = 30,
['guildlv'] = 1,
['des'] = "<br/><br/><font color='#00ff00'> Khai mở trước một tuần, thứ 2, 4, 6 Thiên khai khải.<br/> Khai mở một tuần sau, mỗi thứ tư mở ra.</font><br/> Thời gian hoạt động 21: 00-21: 30<br/><br/> Bang phái thắng lợi có tư cách tham dự thượng cổ Thiên Cung",
['tipdes'] = "Chiếm đóng di tích, hùng bá tứ phương.",
['time'] = 1,
['reward'] = "151100042#151100052#151100062",
['name_img'] = "guild_act_2.png",
['bg_img'] = "guild_act_bg_2.jpg",
['notice_img'] = "guild_act_notice_2",
},
[3]={
['id'] = 3,
['name'] = "Bang phái vương thành chiến",
['openTime'] = "21:00:00",
['ifShowChat'] = 1,
['openParam1'] = "5",
['openParam2'] = "3,5,7",
['duration'] = 30,
['guildlv'] = 1,
['des'] = "<br/><br/><font color='#00ff00'> Khai mở trước một tuần, thứ 3, 5, 7 Thiên khai khải.<br/> Khai mở một tuần sau, mỗi thứ sáu mở ra.</font><br/> Thời gian hoạt động 21: 00-21: 30<br/><br/> Chỉ có bang phái mạnh nhất mới có thể thắng thượng cổ Thiên Cung!",
['tipdes'] = "Hưởng thượng cổ Thiên Cung người được thiên hạ.",
['time'] = 1,
['reward'] = "200360000#180400004#10",
['name_img'] = "guild_act_3.png",
['bg_img'] = "guild_act_bg_3.jpg",
['notice_img'] = "guild_act_notice_3",
},
[4]={
['id'] = 4,
['name'] = "Bang phái Boss",
['openTime'] = "10:00:00",
['ifShowChat'] = 0,
['openParam1'] = "30",
['openParam2'] = "",
['duration'] = 780,
['guildlv'] = 1,
['des'] = "<br/><br/><font color='#00ff00'> Mỗi ngày bang chủ tiến hành mở ra, sau đó tiến nhập </font><br/><br/><br/><br/> Tập hợp lực lương bang hội, chiến cường lực thủ hộ!",
['tipdes'] = "Thần thú đã triệu hoán, nhanh tiến về tiêu diệt.",
['time'] = 1,
['reward'] = "7#150100001#151803001",
['name_img'] = "guild_act_4.png",
['bg_img'] = "guild_act_bg_4.jpg",
['notice_img'] = "guild_act_notice_4",
},
};
