_G.t_homepupil={
[0]={
['id'] = 0,
['pupilName'] = "Thanh tiểu Vân",
['pupilQuality'] = 2,
['pupilImage'] = 105,
['pupilAttr'] = 1,
},
[1]={
['id'] = 1,
['pupilName'] = "Tiêu Viêm",
['pupilQuality'] = 3,
['pupilImage'] = 19,
['pupilAttr'] = 1,
},
[2]={
['id'] = 2,
['pupilName'] = "Tiêu Huân Nhi",
['pupilQuality'] = 3,
['pupilImage'] = 105,
['pupilAttr'] = 1,
},
[3]={
['id'] = 3,
['pupilName'] = "Thải Lân",
['pupilQuality'] = 3,
['pupilImage'] = 124,
['pupilAttr'] = 1,
},
[4]={
['id'] = 4,
['pupilName'] = "Lâm Động",
['pupilQuality'] = 3,
['pupilImage'] = 13,
['pupilAttr'] = 1,
},
[5]={
['id'] = 5,
['pupilName'] = "Lăng Thanh Trúc",
['pupilQuality'] = 3,
['pupilImage'] = 104,
['pupilAttr'] = 1,
},
[6]={
['id'] = 6,
['pupilName'] = "Ứng Hoan Hoan",
['pupilQuality'] = 3,
['pupilImage'] = 114,
['pupilAttr'] = 1,
},
[7]={
['id'] = 7,
['pupilName'] = "Mục Trần",
['pupilQuality'] = 3,
['pupilImage'] = 1,
['pupilAttr'] = 1,
},
[8]={
['id'] = 8,
['pupilName'] = "Lạc Ly",
['pupilQuality'] = 3,
['pupilImage'] = 120,
['pupilAttr'] = 1,
},
[9]={
['id'] = 9,
['pupilName'] = "Cửu U",
['pupilQuality'] = 3,
['pupilImage'] = 112,
['pupilAttr'] = 1,
},
[10]={
['id'] = 10,
['pupilName'] = "Tôn Ngộ Không",
['pupilQuality'] = 4,
['pupilImage'] = 24,
['pupilAttr'] = 1,
},
[11]={
['id'] = 11,
['pupilName'] = "Nhị Lang thần",
['pupilQuality'] = 4,
['pupilImage'] = 17,
['pupilAttr'] = 2,
},
[12]={
['id'] = 12,
['pupilName'] = "Hằng Nga",
['pupilQuality'] = 4,
['pupilImage'] = 118,
['pupilAttr'] = 3,
},
[13]={
['id'] = 13,
['pupilName'] = "Chung Quỳ",
['pupilQuality'] = 4,
['pupilImage'] = 14,
['pupilAttr'] = 3,
},
[14]={
['id'] = 14,
['pupilName'] = "Điêu Thuyền",
['pupilQuality'] = 4,
['pupilImage'] = 101,
['pupilAttr'] = 3,
},
[15]={
['id'] = 15,
['pupilName'] = "Na Tra",
['pupilQuality'] = 4,
['pupilImage'] = 19,
['pupilAttr'] = 3,
},
[16]={
['id'] = 16,
['pupilName'] = "Lữ Động Tân",
['pupilQuality'] = 4,
['pupilImage'] = 22,
['pupilAttr'] = 3,
},
[17]={
['id'] = 17,
['pupilName'] = "Khương Tử Nha",
['pupilQuality'] = 4,
['pupilImage'] = 20,
['pupilAttr'] = 3,
},
[18]={
['id'] = 18,
['pupilName'] = "Ðát Kỷ",
['pupilQuality'] = 4,
['pupilImage'] = 121,
['pupilAttr'] = 3,
},
[19]={
['id'] = 19,
['pupilName'] = "Tử Hà tiên tử",
['pupilQuality'] = 4,
['pupilImage'] = 111,
['pupilAttr'] = 3,
},
[20]={
['id'] = 20,
['pupilName'] = "Hồng hài nhi",
['pupilQuality'] = 4,
['pupilImage'] = 107,
['pupilAttr'] = 3,
},
};
