_G.t_homequestrange={
[0]={
['id'] = 0,
['QuestName'] = "Công thành đoạt đất",
['QuestTxt'] = "Gần nhất lại có vực ngoại yêu ma lưu thoán đến đại thiên thế giới làm xằng làm bậy, tiến về diệt trừ bọn hắn!",
['QuestType'] = 5,
['needAttr'] = 1,
['appointTime'] = 300,
['monsterGruop'] = 6,
['time'] = 0,
['quality'] = 0,
['type'] = 0,
},
[1]={
['id'] = 1,
['QuestName'] = "Công thành đoạt đất",
['QuestTxt'] = "Gần nhất lại có vực ngoại yêu ma lưu thoán đến đại thiên thế giới làm xằng làm bậy, tiến về diệt trừ bọn hắn!",
['QuestType'] = 1,
['needAttr'] = 1,
['appointTime'] = 0,
['monsterGruop'] = 1,
['time'] = 0,
['quality'] = 0,
['type'] = 0,
},
[2]={
['id'] = 2,
['QuestName'] = "Điều tra địch tình",
['QuestTxt'] = "Nghe nói lại có chí tôn di tích hiện thế, tiến về trong đó thăm viếng có thể đạt được  đại lượng ban thưởng, nhưng là phải cẩn thận trong đó địch nhân.",
['QuestType'] = 2,
['needAttr'] = 2,
['appointTime'] = 0,
['monsterGruop'] = 2,
['time'] = 0,
['quality'] = 0,
['type'] = 0,
},
[3]={
['id'] = 3,
['QuestName'] = "Chăm sóc người bị thương",
['QuestTxt'] = "Rất nhiều nơi thụ Tà Tộc độc hại, tử thương vô số, tiến về cứu vớt lê dân bách tính, có thể đạt được  đại lượng ngân lượng ban thưởng",
['QuestType'] = 3,
['needAttr'] = 3,
['appointTime'] = 0,
['monsterGruop'] = 3,
['time'] = 0,
['quality'] = 0,
['type'] = 0,
},
[4]={
['id'] = 4,
['QuestName'] = "Phong ấn yêu thú",
['QuestTxt'] = "Viễn cổ phong ấn đã buông lỏng, không ít Tà Linh trốn thoát, trấn áp bọn hắn cũng chữa trị phong ấn.",
['QuestType'] = 2,
['needAttr'] = 4,
['appointTime'] = 0,
['monsterGruop'] = 4,
['time'] = 3,
['quality'] = 0,
['type'] = 0,
},
[5]={
['id'] = 5,
['QuestName'] = "Trảm yêu trừ ma",
['QuestTxt'] = "Gần nhất yêu thú lại bắt đầu bạo loạn, tiến về phong ấn bọn hắn, cũng cảnh giác những cái kia đồng dạng đánh yêu thú chú ý người.",
['QuestType'] = 5,
['needAttr'] = 5,
['appointTime'] = 0,
['monsterGruop'] = 5,
['time'] = 10,
['quality'] = 0,
['type'] = 0,
},
[6]={
['id'] = 6,
['QuestName'] = "Trảm yêu trừ ma",
['QuestTxt'] = "Gần nhất yêu thú lại bắt đầu bạo loạn, tiến về phong ấn bọn hắn, cũng cảnh giác những cái kia đồng dạng đánh yêu thú chú ý người.",
['QuestType'] = 5,
['needAttr'] = 5,
['appointTime'] = 0,
['monsterGruop'] = 5,
['time'] = 1,
['quality'] = 0,
['type'] = 0,
},
};
