_G.t_homepupilname={
[1]={
['id'] = 1,
['manSurname'] = "Liệt thương",
['womanSurname'] = "Hoàng tộc",
['manName'] = "Hàn Sơn",
['womanName'] = "Thanh Đàn",
},
[2]={
['id'] = 2,
['manSurname'] = "Kiếm gãy",
['womanSurname'] = "Trăng tròn",
['manName'] = "Tạ huyền",
['womanName'] = "Đường băng",
},
[3]={
['id'] = 3,
['manSurname'] = "Bá Đao",
['womanSurname'] = "Kim Phượng",
['manName'] = "Lâm Viêm",
['womanName'] = "Đường Nhu",
},
[4]={
['id'] = 4,
['manSurname'] = "Tàn lưỡi đao",
['womanSurname'] = "Mây trôi",
['manName'] = "Liễu trời",
['womanName'] = "Võ doanh",
},
[5]={
['id'] = 5,
['manSurname'] = "Ma Tôn",
['womanSurname'] = "Diệt kiếm",
['manName'] = "Từ bá",
['womanName'] = "Doãn mộng",
},
[6]={
['id'] = 6,
['manSurname'] = "Hoàng giả",
['womanSurname'] = "Múa đơn",
['manName'] = "Lạc Vân",
['womanName'] = "Hạ hi",
},
[7]={
['id'] = 7,
['manSurname'] = "Ma vực",
['womanSurname'] = "Đạm Nguyệt",
['manName'] = "Tiêu Địch",
['womanName'] = "Cảnh Vân",
},
[8]={
['id'] = 8,
['manSurname'] = "Chí tôn",
['womanSurname'] = "Kiếm Tiên",
['manName'] = "Mực phong",
['womanName'] = "Ngô song",
},
[9]={
['id'] = 9,
['manSurname'] = "Tán Tiên",
['womanSurname'] = "Tử Kinh",
['manName'] = "Phó trời",
['womanName'] = "Lục dung",
},
[10]={
['id'] = 10,
['manSurname'] = "Kim Tiên",
['womanSurname'] = "Thấm Thủy",
['manName'] = "Lý chiến",
['womanName'] = "Văn tuyết",
},
[11]={
['id'] = 11,
['manSurname'] = "Địa Tiên",
['womanSurname'] = "Tán Tiên",
['manName'] = "Nhiếp thanh",
['womanName'] = "Viên tiêm",
},
[12]={
['id'] = 12,
['manSurname'] = "Tà Linh",
['womanSurname'] = "Kim Tiên",
['manName'] = "Hứa manh",
['womanName'] = "Lá đồng",
},
[13]={
['id'] = 13,
['manSurname'] = "Quỷ nhân",
['womanSurname'] = "Địa Tiên",
['manName'] = "Howan",
['womanName'] = "Màn linh",
},
[14]={
['id'] = 14,
['manSurname'] = "Thiên yêu",
['womanSurname'] = "Thiên yêu",
['manName'] = "Mạnh biển",
['womanName'] = "Lý Vi",
},
[15]={
['id'] = 15,
['manSurname'] = "Long tộc",
['womanSurname'] = "Linh Thần",
['manName'] = "Hình vĩnh",
['womanName'] = "Long Nguyệt",
},
[16]={
['id'] = 16,
['manSurname'] = "Linh Thần",
['womanSurname'] = "Hồ Tiên",
['manName'] = "Lữ Nham",
['womanName'] = "Lâu mưa",
},
[17]={
['id'] = 17,
['manSurname'] = "Ma kích",
['womanSurname'] = "Điệp yêu",
['manName'] = "Triều võ",
['womanName'] = "Tiết nhị",
},
[18]={
['id'] = 18,
['manSurname'] = "Bá vương",
['womanSurname'] = "Thiên ma",
['manName'] = "Đơn phong",
['womanName'] = "Tuần tĩnh",
},
[19]={
['id'] = 19,
['manSurname'] = "Luân hồi",
['womanSurname'] = "Phụng Tiên",
['manName'] = "Hoa thành",
['womanName'] = "An nhiễm",
},
[20]={
['id'] = 20,
['manSurname'] = "Thiên Bằng",
['womanSurname'] = "Phi ảnh",
['manName'] = "Mục rồng",
['womanName'] = "Quý tuyết",
},
};
