_G.t_itemacquireway={
[1]={
['id'] = 1,
['funid'] = 0,
['acquirename'] = "Thương thành",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "1102",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[2]={
['id'] = 2,
['funid'] = 0,
['acquirename'] = "Bang phái cửa hàng",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "6",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[3]={
['id'] = 3,
['funid'] = 0,
['acquirename'] = "Ngày vòng nhiệm vụ",
['acquirebuttname'] = "",
['scriptname'] = "",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[4]={
['id'] = 4,
['funid'] = 0,
['acquirename'] = "Mục tiêu nhiệm vụ",
['acquirebuttname'] = "",
['scriptname'] = "",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[5]={
['id'] = 5,
['funid'] = 0,
['acquirename'] = "Nhiệm vụ chính tuyến",
['acquirebuttname'] = "",
['scriptname'] = "",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[6]={
['id'] = 6,
['funid'] = 0,
['acquirename'] = "Thế giới BOSS",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "15",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[7]={
['id'] = 7,
['funid'] = 0,
['acquirename'] = "Địa cung BOSS",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "76",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[8]={
['id'] = 8,
['funid'] = 0,
['acquirename'] = "Dã ngoại BOSS",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "116",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[9]={
['id'] = 9,
['funid'] = 0,
['acquirename'] = "Người BOSS",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "72",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[10]={
['id'] = 10,
['funid'] = 0,
['acquirename'] = "Vượt phục chiến trường",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "64",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[11]={
['id'] = 11,
['funid'] = 0,
['acquirename'] = "Hoạt động - Phong thần loạn đấu",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "16",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[12]={
['id'] = 12,
['funid'] = 0,
['acquirename'] = "Hoạt động - Bí cảnh đoạt bảo",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "16",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[13]={
['id'] = 13,
['funid'] = 0,
['acquirename'] = "Hoạt động - Trên trời rơi xuống bảo rương",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "16",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[14]={
['id'] = 14,
['funid'] = 0,
['acquirename'] = "Phó bản - Biến hình địa cung",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "13",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[15]={
['id'] = 15,
['funid'] = 0,
['acquirename'] = "Thiên thần chiến trường",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "20",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[16]={
['id'] = 16,
['funid'] = 0,
['acquirename'] = "Phó bản - Tổ đội khiêu chiến",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "74",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[17]={
['id'] = 17,
['funid'] = 0,
['acquirename'] = "Tràng cảnh - Luyện cấp tháp",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "18",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[18]={
['id'] = 18,
['funid'] = 0,
['acquirename'] = "Đồ ma",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "14",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[19]={
['id'] = 19,
['funid'] = 0,
['acquirename'] = "Cam trang thí luyện",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "19",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[20]={
['id'] = 20,
['funid'] = 0,
['acquirename'] = "Hợp thành",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "38",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[21]={
['id'] = 21,
['funid'] = 0,
['acquirename'] = "Trang bị phân giải",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "43",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[22]={
['id'] = 22,
['funid'] = 0,
['acquirename'] = "Tiên giai",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "23",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[23]={
['id'] = 23,
['funid'] = 0,
['acquirename'] = "Đánh dấu",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "22",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[24]={
['id'] = 24,
['funid'] = 0,
['acquirename'] = "Sân thi đấu",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "17",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[25]={
['id'] = 25,
['funid'] = 0,
['acquirename'] = "Dã ngoại treo máy",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[26]={
['id'] = 26,
['funid'] = 0,
['acquirename'] = "Lần đầu nạp tiền",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "",
['parameter'] = "",
['ifrecommend'] = 0,
['imgUrl'] = "v_kuaisu_tuijian",
},
[27]={
['id'] = 27,
['funid'] = 0,
['acquirename'] = "Lịch luyện nhiệm vụ",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "117",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[28]={
['id'] = 28,
['funid'] = 0,
['acquirename'] = "Treo thưởng nhiệm vụ",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "124",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[29]={
['id'] = 29,
['funid'] = 0,
['acquirename'] = "Săn ma nhiệm vụ",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "119",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[30]={
['id'] = 30,
['funid'] = 0,
['acquirename'] = "Mục Dã chi chiến",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "123",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[31]={
['id'] = 31,
['funid'] = 0,
['acquirename'] = "Tử trang phó bản",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "44",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[32]={
['id'] = 32,
['funid'] = 0,
['acquirename'] = "Thiên thần chiến trường",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "20",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[33]={
['id'] = 33,
['funid'] = 0,
['acquirename'] = "Một mình phó bản - Thượng cổ chiến trường",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "13",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[34]={
['id'] = 34,
['funid'] = 0,
['acquirename'] = "Tru Tiên Trận",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "121",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[35]={
['id'] = 35,
['funid'] = 0,
['acquirename'] = "Một mình phó bản - Cửu khúc cát vàng trận",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "13",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[36]={
['id'] = 36,
['funid'] = 0,
['acquirename'] = "Một mình phó bản - Kim quang Lạc Phách Trận",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "13",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
[37]={
['id'] = 37,
['funid'] = 0,
['acquirename'] = "Cày đồ địa cung",
['acquirebuttname'] = "<u> Lập tức tiến về <u>",
['scriptname'] = "34",
['parameter'] = "",
['ifrecommend'] = 1,
['imgUrl'] = "v_kuaisu_tuijian",
},
};
