_G.t_kuafuactivity={
[1]={
['id'] = 1,
['name'] = "Vượt phục boss",
['openTime'] = "21:00:00",
['openParam1'] = "2,6",
['openParam2'] = "",
['duration'] = 60,
['notice_img'] = "kuafuboss_notice_1",
['des'] = "Lực chiến xếp hạng trước 10 Lại lớn hơn 125 Cấp có thể tham gia",
['reward_show'] = "",
},
[2]={
['id'] = 2,
['name'] = "Vượt phục thi dự tuyển",
['openTime'] = "20:30:00",
['openParam1'] = "1,5",
['openParam2'] = "",
['duration'] = 30,
['notice_img'] = "kuafuleitai_notice_2",
['des'] = "Lực chiến xếp hạng trước 10 Lại lớn hơn 150 Cấp có thể tham gia",
['reward_show'] = "",
},
[3]={
['id'] = 3,
['name'] = "Vượt phục lôi đài thi đấu",
['openTime'] = "21:30:00",
['openParam1'] = "2,6",
['openParam2'] = "",
['duration'] = 45,
['notice_img'] = "kuafuleitai_notice_2",
['des'] = "Có được vượt phục lôi đài thi đấu tư cách người chơi có thể tham gia",
['reward_show'] = "151000017,0#151000018,0#150800004,0",
},
};
