_G.t_kuafudan={
[1]={
['dan'] = 1,
['danName'] = "Kim cương đẳng cấp",
['base'] = 10,
['lowest'] = 3,
['winExploit'] = 100,
['loseExploit'] = 50,
},
[2]={
['dan'] = 2,
['danName'] = "Bạch kim đẳng cấp",
['base'] = 10,
['lowest'] = 3,
['winExploit'] = 80,
['loseExploit'] = 40,
},
[3]={
['dan'] = 3,
['danName'] = "Hoàng kim đẳng cấp",
['base'] = 10,
['lowest'] = 3,
['winExploit'] = 60,
['loseExploit'] = 30,
},
[4]={
['dan'] = 4,
['danName'] = "Bạch ngân đẳng cấp",
['base'] = 10,
['lowest'] = 3,
['winExploit'] = 40,
['loseExploit'] = 20,
},
[5]={
['dan'] = 5,
['danName'] = "Thanh đồng đẳng cấp",
['base'] = 10,
['lowest'] = 3,
['winExploit'] = 20,
['loseExploit'] = 10,
},
};
