_G.t_marryIntimate={
[1]={
['level'] = 1,
['needIntimate'] = 400,
['title'] = "Trai tài gái sắc",
['imgsource'] = "imgsource01",
['attrExtraPercent'] = 20,
},
[2]={
['level'] = 2,
['needIntimate'] = 1000,
['title'] = "Lưỡng tình tương duyệt",
['imgsource'] = "imgsource02",
['attrExtraPercent'] = 40,
},
[3]={
['level'] = 3,
['needIntimate'] = 1800,
['title'] = "Tâm hữu linh tê",
['imgsource'] = "imgsource03",
['attrExtraPercent'] = 80,
},
[4]={
['level'] = 4,
['needIntimate'] = 3000,
['title'] = "Ý hợp tâm đầu",
['imgsource'] = "imgsource04",
['attrExtraPercent'] = 140,
},
[5]={
['level'] = 5,
['needIntimate'] = 4200,
['title'] = "Châu liên bích hợp",
['imgsource'] = "imgsource05",
['attrExtraPercent'] = 220,
},
[6]={
['level'] = 6,
['needIntimate'] = 5600,
['title'] = "Cầm sắt hòa minh",
['imgsource'] = "imgsource06",
['attrExtraPercent'] = 320,
},
[7]={
['level'] = 7,
['needIntimate'] = 7500,
['title'] = "Ông trời tác hợp cho",
['imgsource'] = "imgsource07",
['attrExtraPercent'] = 430,
},
[8]={
['level'] = 8,
['needIntimate'] = 9200,
['title'] = "Cử án tề mi",
['imgsource'] = "imgsource08",
['attrExtraPercent'] = 550,
},
[9]={
['level'] = 9,
['needIntimate'] = 11400,
['title'] = "So Dực Song Phi",
['imgsource'] = "imgsource09",
['attrExtraPercent'] = 700,
},
[10]={
['level'] = 10,
['needIntimate'] = 13800,
['title'] = "Vĩnh kết đồng tâm",
['imgsource'] = "imgsource10",
['attrExtraPercent'] = 900,
},
};
