_G.t_mapSpoint={
[1]={
['id'] = 1,
['modelId'] = 80100001,
['name'] = "Khát máu lãnh chúa",
['icon'] = "monster_boss",
['tips'] = "Cày đồ địa cung 1 Tầng boss",
},
[2]={
['id'] = 2,
['modelId'] = 80100001,
['name'] = "Bất bại Long Vương",
['icon'] = "monster_boss",
['tips'] = "Cày đồ địa cung 2 Tầng boss",
},
[3]={
['id'] = 3,
['modelId'] = 80100001,
['name'] = "Vực sâu Ma Thần",
['icon'] = "monster_boss",
['tips'] = "Cày đồ địa cung 3 Tầng boss",
},
[4]={
['id'] = 4,
['modelId'] = 80100001,
['name'] = "Địa Ngục Diêm La",
['icon'] = "monster_boss",
['tips'] = "Cày đồ địa cung 4 Tầng boss",
},
[5]={
['id'] = 5,
['modelId'] = 80100001,
['name'] = "Cửu thiên chiến cuồng",
['icon'] = "monster_boss",
['tips'] = "Cày đồ địa cung 5 Tầng boss",
},
[6]={
['id'] = 6,
['modelId'] = 80100001,
['name'] = "Hộ bảo Phủ Vương",
['icon'] = "monster_boss",
['tips'] = "Khó khăn cày đồ bí cảnh 1 Tầng boss",
},
[7]={
['id'] = 7,
['modelId'] = 80100001,
['name'] = "Hộ bảo yêu bướm",
['icon'] = "monster_boss",
['tips'] = "Khó khăn cày đồ bí cảnh 2 Tầng boss",
},
[8]={
['id'] = 8,
['modelId'] = 80100001,
['name'] = "Hộ bảo Yêu Vương",
['icon'] = "monster_boss",
['tips'] = "Khó khăn cày đồ bí cảnh 3 Tầng boss",
},
[9]={
['id'] = 9,
['modelId'] = 80100001,
['name'] = "Hộ bảo Viên Vương",
['icon'] = "monster_boss",
['tips'] = "Khó khăn cày đồ bí cảnh 4 Tầng boss",
},
[10]={
['id'] = 10,
['modelId'] = 80100001,
['name'] = "Hộ bảo ma vương",
['icon'] = "monster_boss",
['tips'] = "Khó khăn cày đồ bí cảnh 5 Tầng boss",
},
[11]={
['id'] = 11,
['modelId'] = 80100001,
['name'] = "Di tích pho tượng điểm",
['icon'] = "monster_boss",
['tips'] = "Bang phái di tích pho tượng chỗ điểm",
},
[12]={
['id'] = 12,
['modelId'] = 80100001,
['name'] = "Di tích boss Điểm",
['icon'] = "monster_boss",
['tips'] = "Di tích boss Chỗ điểm",
},
};
