_G.t_notice={
[10000]={
['id'] = 10000,
['prefix'] = "",
['text'] = "",
['link'] = "",
['pos'] = "1",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10001]={
['id'] = 10001,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "<font color='#ffff00'>{1,nolink} Tại {2} Bên trong may mắn thu được {3}, quả thực tiện sát người bên ngoài.</font>",
['link'] = "Ta cũng muốn chơi!",
['pos'] = "2,4",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[10002]={
['id'] = 10002,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Sáng lập bang phái {2}, bang phái quật khởi, thế không thể đỡ!",
['link'] = "Ta muốn gia nhập",
['pos'] = "4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "6",
},
[10005]={
['id'] = 10005,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đang tìm cùng một chỗ khiêu chiến {2} Đồng đội, sức chiến đấu nhu cầu: {3},",
['link'] = "Lập tức gia nhập",
['pos'] = "4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10006]={
['id'] = 10006,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Server sắp giữ gìn, tranh thủ thời gian đều hạ tuyến a!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10007]={
['id'] = 10007,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Định chế người huyễn lệ xưng hào {2}, này xưng hào sẽ tại sau bảy ngày cấp cho!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10008]={
['id'] = 10008,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Viễn cổ yêu ma lần nữa tai họa nhân gian, các dũng sĩ, nhanh đi tiêu diệt bọn hắn, thắng được chí tôn Thần khí đi!",
['link'] = "Tiến về đánh giết",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "15",
},
[10009]={
['id'] = 10009,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đã tại sân thi đấu 5 Thắng liên tiếp, ai đi ngăn cản hắn giết chóc?",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10010]={
['id'] = 10010,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đã tại sân thi đấu 10 Thắng liên tiếp, ngay tại điên cuồng giết chóc, ai có thể chiến bại hắn?",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10011]={
['id'] = 10011,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đã tại sân thi đấu 20 Thắng liên tiếp, đã yêu quái giết chóc, không người có thể địch!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10012]={
['id'] = 10012,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đã tại sân thi đấu 50 Thắng liên tiếp, đã siêu thần giết chóc, để chúng ta cùng một chỗ cúng bái hắn đi!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10013]={
['id'] = 10013,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đã tại sân thi đấu 100 Thắng liên tiếp, hắn đã đứng ở thần vị trí bên trên, để các phàm nhân run rẩy đi!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10014]={
['id'] = 10014,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Cho BOSS{2} Một kích cuối cùng, đại lượng bảo vật rơi đầy đất, nhanh đoạt a!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10015]={
['id'] = 10015,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Bang phái thành công thăng đến {2} Cấp, bang phái thực lực tăng nhiều!",
['link'] = "Ta muốn nhập giúp",
['pos'] = "4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "6",
},
[10016]={
['id'] = 10016,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Nhặt {2} Rơi xuống vũ khí cực phẩm {3}!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10017]={
['id'] = 10017,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Mở ra thế giới BOSS Tham dự gói quà người đương thời phẩm bộc phát, thu hoạch được trác tuyệt vũ khí {2}!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10018]={
['id'] = 10018,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Nhặt {2} Rơi xuống vũ khí màu tím {3}!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10101]={
['id'] = 10101,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Nâng lên đại thiên thế giới chiến kỳ!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10102]={
['id'] = 10102,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Nâng lên vực ngoại Tà Tộc chiến kỳ!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10103]={
['id'] = 10103,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Thành công cướp đoạt đại thiên thế giới chiến kỳ",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10104]={
['id'] = 10104,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Thành công cướp đoạt vực ngoại Tà Tộc chiến kỳ",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10105]={
['id'] = 10105,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Mới một nhóm chiến kỳ đã tới!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10106]={
['id'] = 10106,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Đã đánh giết 5 Tên cờ làm, trung lập chiến kỳ điểm có đại thiên thế giới chiến kỳ xoát ra",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10107]={
['id'] = 10107,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Đã đánh giết 5 Tên cờ làm, trung lập chiến kỳ điểm có vực ngoại Tà Tộc chiến kỳ xoát ra",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10108]={
['id'] = 10108,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "First blood!! Rượu còn ấm, {1} Đã xem {2} Chém xuống dưới ngựa!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10109]={
['id'] = 10109,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Nhanh như gió táp!!{1} Dẫn đầu đoạt được địch quân chiến kỳ!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10110]={
['id'] = 10110,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 5 Người! Thật là đẹp trai!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10111]={
['id'] = 10111,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 10 Người! Những người khác trong lòng run sợ!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10112]={
['id'] = 10112,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 15 Người! Giống như một đầu dũng cảm trâu đực!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10113]={
['id'] = 10113,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 20 Người! Hắn là chân chính anh hùng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10114]={
['id'] = 10114,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 25 Người! Sự tích của hắn khích lệ người trẻ tuổi tiếp tục chiến đấu!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10115]={
['id'] = 10115,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 30 Người! Nghe nói hắn đại biểu cho chiến thần!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10116]={
['id'] = 10116,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 40 Người! Nghe nói hắn đại biểu cho chiến thần!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10117]={
['id'] = 10117,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đã mệt kế đánh bại 50 Người! Nghe nói hắn đại biểu cho chiến thần!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10118]={
['id'] = 10118,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Tam sát!{1} Đã đại sát đặc sát!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10119]={
['id'] = 10119,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Bốn giết!{1} Đã giết người như ngóe!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10120]={
['id'] = 10120,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Năm giết!{1} Tiếp tục đồ sát địch quân người chơi!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10121]={
['id'] = 10121,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Lục Sát!{1} Như vào chỗ không người, thủ hạ không ai đỡ nổi một hiệp!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10122]={
['id'] = 10122,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Thất Sát!{1} Đã biến thái mổ giết!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10123]={
['id'] = 10123,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Tám giết!{1} Chúa tể toàn bộ chiến cuộc!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10124]={
['id'] = 10124,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Cửu Sát!{1} Bắt đầu viết tiếp một đoạn truyền kỳ mới!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10125]={
['id'] = 10125,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Mười người trảm!{1} Đạp vào Thần vị, chí tôn giáng lâm, chư thần tán thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10126]={
['id'] = 10126,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{3} Trảm! Giống như thần {1} Đánh bại {2}, mọi người tranh thủ thời gian quỳ lạy đi!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10127]={
['id'] = 10127,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh bại {2}, đồ tể bị Thiên Khiển!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10128]={
['id'] = 10128,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Kết thúc {2} Không ai có thể ngăn cản!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10129]={
['id'] = 10129,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Kết thúc {2} Biến thái giết chóc!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10130]={
['id'] = 10130,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh bại {2}, nào đó chúa tể bị ném tiến xuống thủy đạo!",
['link'] = "",
['pos'] = "4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10131]={
['id'] = 10131,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh bại {2}, truyền kỳ bị bỏ dở!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10132]={
['id'] = 10132,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Diệt thần thành công, {2} Bị đã kéo xuống thần đàn!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10133]={
['id'] = 10133,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Chiến thần vẫn lạc, chư thiên than thở!{2} Bị kết thúc, {1} Liền là cái kia thí thần người!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10134]={
['id'] = 10134,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Phúc tinh cao chiếu!{1} Đem trang bị {2} Lên tới {3} Tinh!",
['link'] = "Tiến về thăng tinh",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "30",
},
[10135]={
['id'] = 10135,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đem trang bị thăng phẩm thành công, thu hoạch được lục sắc phẩm chất {2}!",
['link'] = "Tiến về thăng phẩm",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "32",
},
[10136]={
['id'] = 10136,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem tọa kỵ lên tới {2} Giai, thu được {3}!",
['link'] = "Tọa kỵ của ta",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "5",
},
[10137]={
['id'] = 10137,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công kích hoạt lên Linh thú -{2}, Thú phách phụ thân, chiến lực tăng vọt!",
['link'] = "Ta Linh thú",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "4",
},
[10138]={
['id'] = 10138,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem {2} Giai Linh thú {3} Tiến giai đến {4} Giai, thu được Linh thú {5}!",
['link'] = "Ta Linh thú",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "4",
},
[10139]={
['id'] = 10139,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công vượt qua kiếp nạn, tiến giai đến {2} Giai {3}!",
['link'] = "Cảnh giới của ta",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "25",
},
[10140]={
['id'] = 10140,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đem bảo thạch lên tới {2} Cấp, quang huy sáng chói!",
['link'] = "Ta bảo thạch",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "33",
},
[10141]={
['id'] = 10141,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đem [ Trang bị thức tỉnh ] Lên tới {2} Cấp, trác tuyệt thuộc tính trên diện rộng tăng thêm!",
['link'] = "Ta thức tỉnh",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "35",
},
[10142]={
['id'] = 10142,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem thần binh lên tới {2} Giai, thu được {3}!",
['link'] = "Ta thần binh",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "21",
},
[10143]={
['id'] = 10143,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem bảo vật {2} Hoàn mỹ khải linh!",
['link'] = "Ta muốn khải linh",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "10",
},
[10144]={
['id'] = 10144,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đánh bại {2} Tinh phệ hồn quái!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10145]={
['id'] = 10145,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Dẫn đầu thông quan {2}{3} Độ khó phó bản!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10146]={
['id'] = 10146,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Dẫn đầu thông quan Đấu Phá Thương Khung thứ {2} Tầng!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10147]={
['id'] = 10147,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đánh bại cày đồ địa cung {2} Tầng BOSS, thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10148]={
['id'] = 10148,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Khiêu chiến {2} Thành công, trở thành sân thi đấu thứ {3} Tên!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10149]={
['id'] = 10149,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Khiêu chiến {2} Thành công, vinh đăng sân thi đấu hạng nhất bảo tọa!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10150]={
['id'] = 10150,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đang đánh nát phong ấn lúc phát động [ Băng phong ], 50 Gạo phạm vi bên trong người chơi đều bị đông kết 2 Giây!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10151]={
['id'] = 10151,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đang đánh nát phong ấn lúc không cẩn thận dẫn xuất viễn cổ boss, đánh bại nó có thể đạt được  đặc thù ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10152]={
['id'] = 10152,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đang đánh nát phong ấn lúc phát động [ Bạo tạc ], bị liên lụy người chơi toàn bộ biến thành than đen, cũng giảm tốc 2 Giây!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10153]={
['id'] = 10153,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đang đánh nát phong ấn lúc không cẩn thận dẫn đến một con quái thú biến dị, cẩn thận sự điên cuồng của nó công kích!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10154]={
['id'] = 10154,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đem trang bị {2} Cường hóa đến {3} Chui!",
['link'] = "Tiến về trang bị",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "30",
},
[10155]={
['id'] = 10155,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đem trang bị thăng phẩm thành công, thu hoạch được màu lam phẩm chất {2}!",
['link'] = "Tiến về thăng phẩm",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "32",
},
[10156]={
['id'] = 10156,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đem trang bị thăng phẩm thành công, thu hoạch được tử sắc phẩm chất {2}!",
['link'] = "Tiến về thăng phẩm",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "32",
},
[10157]={
['id'] = 10157,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh bại {2}, đoạt lại chiến kỳ, chiến kỳ trả lại đến ban đầu vị trí!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10158]={
['id'] = 10158,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Hoạt động đã mở khải, mời kịp thời tiến vào!",
['link'] = "Lập tức tham gia",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openactivity",
['linkParam'] = "",
},
[10159]={
['id'] = 10159,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem chiến khải lên tới {2} Giai, thu được {3}!",
['link'] = "Ta chiến khải",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "36",
},
[10160]={
['id'] = 10160,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem linh trận lên tới {2} Giai, thu được {3}!",
['link'] = "Ta linh trận",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "50",
},
[10161]={
['id'] = 10161,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem Linh thú tọa kỵ lên tới {2} Giai, thu được {3}!",
['link'] = "Ta Linh thú tọa kỵ",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "67",
},
[10201]={
['id'] = 10201,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Chí tôn vương tọa ngay tại gặp công kích, mời kịp thời phòng thủ!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10202]={
['id'] = 10202,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Tượng thần ngay tại gặp công kích",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10203]={
['id'] = 10203,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Bang phái chiếm lĩnh {2} Tượng thần, phe tấn công thành công kích hoạt {3} Điểm phục sinh!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10204]={
['id'] = 10204,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Bang phái chiếm lĩnh {2} Tượng thần, phe tấn công {3} Điểm phục sinh mất đi hiệu lực!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10205]={
['id'] = 10205,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Chúc mừng bang phái {1} Đoạt được chí tôn vương thành, {2} Trở thành tam giới chí tôn, hiệu lệnh thiên hạ, không dám không theo!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10206]={
['id'] = 10206,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Bang phái trải qua dục huyết phấn chiến, thành công đánh hạ thượng cổ Thiên Cung, trở thành mới chí tôn vương giúp!{2} Thành công mới tam giới chí tôn, hiệu lệnh thiên hạ, không dám không theo!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10207]={
['id'] = 10207,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Bang phái trải qua chiến đấu kịch liệt, thành công đánh lui địch quân, liên tục {2} Vòng thủ vệ vương thành, vương giúp thực lực, không thể nghi ngờ!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10208]={
['id'] = 10208,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đem {2} Bổ nhiệm làm mới tam giới Thần Vương, chí tôn vinh quang, phổ chiếu thiên hạ!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10209]={
['id'] = 10209,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Bang phái trải qua dục huyết phấn chiến, thu hoạch được lần này [ Bang phái - Di tích chi chiến ] Hạng nhất, đoạt được lượt này thượng cổ Thiên Cung tranh đoạt tư cách! Mọi người chờ mong biểu hiện của bọn hắn đi!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10210]={
['id'] = 10210,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Cùng {2} Bang phái thu hoạch được lần thứ nhất [ Bang phái - Di tích chi chiến ] Thứ nhất, hai tên, bọn hắn sẽ tại ngày mai [ Bang phái - Thượng cổ Thiên Cung ] Bên trong lần nữa quyết chiến, tranh đoạt thượng cổ Thiên Cung thuộc về quyền! Ai có thể trở thành chí tôn vương giúp, chúng ta rửa mắt mà đợi!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[10211]={
['id'] = 10211,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đã đổi mới, công kích di tích có thể đạt được  đại lượng điểm tích lũy.",
['link'] = "Tiến về đánh giết",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10212]={
['id'] = 10212,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Bang phái thành công chiếm lĩnh chí tôn di tích, mỗi giây thu hoạch được đại lượng điểm tích lũy.",
['link'] = "Tiến về tranh đoạt",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "unionwarpath",
['linkParam'] = "",
},
[10301]={
['id'] = 10301,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem cảnh giới đột phá tới {2}! Thu hoạch được mạnh hơn chiến lực cùng cảnh giới càng cao hơn áp chế hiệu quả, cùng giai phía dưới lại vô địch tay!",
['link'] = "Cảnh giới của ta",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "25",
},
[10401]={
['id'] = 10401,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Dẫn đầu đánh giết người chơi {2} Cũng cướp đoạt hắn điểm tích lũy!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10402]={
['id'] = 10402,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Điểm tích lũy đạt tới 2000, tất cả mọi người nhanh đi cướp đoạt điểm tích lũy a!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10403]={
['id'] = 10403,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Điểm tích lũy đạt tới 3000, trong tay tồn lấy bó lớn điểm tích lũy!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10404]={
['id'] = 10404,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Điểm tích lũy đạt tới 4000, xem thường đám người, không người nào dám tới cướp đoạt!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10405]={
['id'] = 10405,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Điểm tích lũy đạt tới 5000, điểm tích lũy đã đột phá chân trời rồi!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10406]={
['id'] = 10406,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Điểm tích lũy đạt tới 10000, danh tự đã vang vọng Hoa Hạ đại địa!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10407]={
['id'] = 10407,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Điểm tích lũy đạt tới 50000, anh hùng thiên hạ ra chúng ta, danh lưu thiên cổ vạn người truy!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10408]={
['id'] = 10408,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Điểm tích lũy đạt tới 100000, chúng thần cũng không nhịn được cũng theo đó cảm thán một tiếng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10409]={
['id'] = 10409,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh giết {2} Duy nhất một lần cướp được 1000 Điểm tích lũy, trốn ở trong góc vụng trộm cười nửa ngày!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10410]={
['id'] = 10410,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh giết {2} Duy nhất một lần cướp được 2000 Điểm tích lũy, thật sự là may mắn sủng nhi!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10411]={
['id'] = 10411,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh giết {2} Duy nhất một lần cướp được 3000 Điểm tích lũy, may mắn cũng không thể che lại thực lực của hắn!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10412]={
['id'] = 10412,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh giết {2} Duy nhất một lần cướp được 5000 Điểm tích lũy, thực lực siêu cường thần may mắn chiếu cố người a!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10413]={
['id'] = 10413,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh giết {2} Duy nhất một lần cướp được 10000 Điểm tích lũy, cái này... Đã không phải là người có khả năng đạt tới tiêu chuẩn!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10414]={
['id'] = 10414,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "BOSS Tại chúng thủ hạ chen chúc bên trong giáng lâm đến {1} Thanh Long đài, đánh giết bọn chúng có thể đạt được  đại lượng điểm tích lũy!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10415]={
['id'] = 10415,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "BOSS Tại chúng thủ hạ chen chúc bên trong giáng lâm đến {1} Chu Tước đài, đánh giết bọn chúng có thể đạt được  đại lượng điểm tích lũy!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10416]={
['id'] = 10416,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "BOSS Tại chúng thủ hạ chen chúc bên trong giáng lâm đến {1} Huyền Vũ đài, đánh giết bọn chúng có thể đạt được  đại lượng điểm tích lũy!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10417]={
['id'] = 10417,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "BOSS Tại chúng thủ hạ chen chúc bên trong giáng lâm đến {1} Bạch Hổ đài, đánh giết bọn chúng có thể đạt được  đại lượng điểm tích lũy!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10418]={
['id'] = 10418,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Thành công đánh giết {1}, điểm tích lũy {2}",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10419]={
['id'] = 10419,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Bị người chơi {1} Đánh giết, điểm tích lũy -{2}",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10420]={
['id'] = 10420,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Nên người chơi điểm tích lũy quá thấp, điểm tích lũy 0",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10421]={
['id'] = 10421,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Thành công đánh giết BOSS{1}, điểm tích lũy {2}",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10422]={
['id'] = 10422,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Thành công đánh giết {1}, điểm tích lũy {2}",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10501]={
['id'] = 10501,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Cày đồ trong cung điện dưới lòng đất BOSS Đã đổi mới, tranh thủ thời gian tiến về cướp đoạt bí bảo đi!",
['link'] = "Lập tức tiến về",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "34",
},
[10601]={
['id'] = 10601,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đánh chết cờ làm, lại đánh giết {2} Tên trung lập chiến kỳ điểm tướng đổi mới ngoài định mức cờ xí!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[10701]={
['id'] = 10701,
['prefix'] = "<img src='img://resfile/icon/chat_ch_2.png'/>",
['text'] = "{1} Chuẩn bị tiến về {2} Đánh giết treo thưởng quái {3}<font color='#ffffff'>{4}</font>, hướng xác nhận này treo thưởng nhiệm vụ cao thủ xin giúp đỡ, cộng đồng đánh giết hoàn thành!",
['link'] = "",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[10801]={
['id'] = 10801,
['prefix'] = "<img src='img://resfile/icon/chat_ch_2.png'/>",
['text'] = "{1} Sáng lập {2}, đội ngũ nhu cầu <font color='#ffffff'> Chiến lực </font> Lớn hơn <font color='#ffffff'>{4}</font>, mau chạy tới người a, chậm liền không có địa.",
['link'] = "Ta muốn gia nhập",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openzdsj",
['linkParam'] = "20",
},
[10901]={
['id'] = 10901,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Khiêu chiến <font color='#ffff00'> Đấu Phá Thương Khung thứ {2} Tầng </font> Thành công!",
['link'] = "Ta muốn khiêu chiến",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "19",
},
[11001]={
['id'] = 11001,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Không để ý, chế tạo ra {2} Trác tuyệt trang bị {3}!",
['link'] = "Ta muốn rèn đúc",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "48",
},
[11101]={
['id'] = 11101,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Xác nhận truyền thuyết tầm bảo nhiệm vụ, chuẩn bị tiến về đào lấy truyền thuyết bảo tàng!",
['link'] = "Ta muốn tìm bảo",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "57",
},
[11201]={
['id'] = 11201,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}{2} Cấp bang phái rộng mời tứ hải anh hào gia nhập, đồng lòng lớn mạnh bang phái thực lực, cùng một chỗ chinh phạt thiên hạ!",
['link'] = "Ta muốn nhập giúp",
['pos'] = "4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "6",
},
[11301]={
['id'] = 11301,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "{1} Đánh chết BOSS{2}, BOSS Rơi xuống đại lượng đạo cụ!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11401]={
['id'] = 11401,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "V Kế hoạch thượng tuyến rồi, càng nhiều hào lễ kính thỉnh kỳ đợi.",
['link'] = "Điểm kích xem xét",
['pos'] = "4",
['channel'] = 1,
['linkScript'] = "openui",
['linkParam'] = "UIVplanMain",
},
[11402]={
['id'] = 11402,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Trên trời rơi xuống phúc duyên {1} Mở ra v Kế hoạch, vui lấy được xa hoa [v Kế hoạch đặc cung gói quà ]",
['link'] = "Ta yếu lĩnh lấy",
['pos'] = "4",
['channel'] = 1,
['linkScript'] = "openui",
['linkParam'] = "UIVplanMain",
},
[11501]={
['id'] = 11501,
['prefix'] = "<img src='img://resfile/icon/chat_ch_2.png'/>",
['text'] = "<font color='#ffff00'>{1}</font> Bang phái ngay tại chiêu mộ các lộ tinh anh, hoan nghênh mọi người gia nhập.",
['link'] = "Xin nhập giúp",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openfunc",
['linkParam'] = "6",
},
[11601]={
['id'] = 11601,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}<font color='#f95208'> Hoàn thành lần đầu nạp tiền, thu được <font color='#dc1d03'> Không xuất bản nữa màu cam trưởng thành vũ khí </font>, <font color='#00ff00'> Thiên thần - Khương Tử Nha kích hoạt thẻ </font>, <font color='#00ff00'> Bạch ngân VIP Vĩnh cửu thẻ </font>, <font color='#00ff00'>300 Vạn ngân lượng thẻ </font>, tọa kỵ giây thăng, chiến lực tăng vọt!</font>",
['link'] = "Ta cũng muốn nhận lấy",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfirstcharge",
['linkParam'] = "",
},
[11602]={
['id'] = 11602,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Kích hoạt lên bạch ngân VIP, nhận lấy tọa kỵ - Vong linh Băng Hồn ngựa, thu được linh lực sản lượng gấp bội, đánh quái kinh nghiệm ngoài định mức tăng thêm, thăng giai đạo cụ nhiều lần thu hoạch quyền hạn!",
['link'] = "Ta muốn kích hoạt",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openvipview",
['linkParam'] = "",
},
[11603]={
['id'] = 11603,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}<font color='#f95208'> Sử dụng trang bị gói quà, thu được <font color='#b324f6'> Cực phẩm 3 Trác tuyệt trang bị </font>{2}, Thần cấp sáo trang, ngươi đáng giá có được!</font>",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "opendaycharge",
['linkParam'] = "",
},
[11604]={
['id'] = 11604,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}<font color='#f95208'> Vận may không sai, mở ra Nguyên bảo hồng bao, thu hoạch được {2} Nguyên bảo, tâm động? Vậy còn không tranh thủ thời gian hành động!</font>",
['link'] = "Ta muốn hồng bao",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openactivity3",
['linkParam'] = "",
},
[11605]={
['id'] = 11605,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Hấp thu tinh hoa của nhật nguyệt hoàn thành lần thứ hai phi thăng, thu hoạch được siêu cường chiến dực, chiến đấu trị số tiêu thăng!",
['link'] = "Ta muốn phi thăng",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "104",
},
[11606]={
['id'] = 11606,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Tụ tinh thần chi lực hoàn thành lần thứ ba phi thăng, mở ra luyện khí hành trình!",
['link'] = "Ta muốn phi thăng",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "104",
},
[11607]={
['id'] = 11607,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Thời không phong bạo dẫn phát không gian rung chuyển, có giấu bí bảo bí cảnh hiện ở nhân thế, thời không chi môn đã ở {1} Xoát ra, cấp tốc tiến về cướp đoạt!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11608]={
['id'] = 11608,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Ngưng tụ linh khí của thiên địa hoàn thành lần đầu phi thăng, thu được hi hữu xưng hào, chiến đấu trị số tiêu thăng!",
['link'] = "Ta muốn phi thăng",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "104",
},
[11609]={
['id'] = 11609,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công kích hoạt lên tuyệt học -{2}, thu hoạch được cao giai kỹ năng đặc thù, hủy thiên diệt địa đều ở một ý niệm!",
['link'] = "Ta muốn học tập",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openMagic",
['linkParam'] = "61",
},
[11610]={
['id'] = 11610,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}<font color='#f95208'> Thành công nhận lấy đoàn mua ban thưởng <font color='#b324f6'>{2}x{3}</font>. Hải lượng đạo cụ, đều ở đoàn mua bên trong!</font>",
['link'] = "Ta yếu lĩnh thưởng",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openactivity4",
['linkParam'] = "",
},
[11611]={
['id'] = 11611,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}<font color='#f95208'> Kích hoạt lên bạch ngân VIP, nhận lấy <font color='#b324f6'> Chiến lực · Thần Phách Đan thuốc </font>, được hưởng vô hạn truyền tống, kinh nghiệm tăng thêm, thuộc tính gấp bội chờ đặc quyền!</font>",
['link'] = "Ta muốn kích hoạt",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openvipview",
['linkParam'] = "",
},
[11612]={
['id'] = 11612,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}<font color='#f95208'> Kích hoạt lên hoàng kim VIP, nhận lấy <font color='#b324f6'> Thần dực · Gió bão thép cánh </font>, được hưởng trả về vật liệu, thăng giai bạo kích, sản xuất gia tăng chờ đặc quyền!</font>",
['link'] = "Ta muốn kích hoạt",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openvipview",
['linkParam'] = "",
},
[11613]={
['id'] = 11613,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1}<font color='#f95208'> Kích hoạt lên kim cương VIP, nhận lấy <font color='#b324f6'> Thiên thần · Long Thần Thái tử </font>, được hưởng thăng giai hệ thống thuộc tính tăng thêm, cấp cho buộc nguyên, nhiều lần ích lợi chờ đặc quyền!</font>",
['link'] = "Ta muốn kích hoạt",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openvipview",
['linkParam'] = "",
},
[11614]={
['id'] = 11614,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "BOSS Nhóm tao ngộ kinh hãi phát sinh bạo động, hiện đã xuất hiện tại {1}{2}{3} Tiến hành quấy rối, xin nhanh chóng tiến về đánh giết!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11615]={
['id'] = 11615,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Dũng mãnh phi thường vô cùng, thu được {2} Bạo tẩu mà ra BOSS Mang theo đại lượng hi hữu ban thưởng!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11616]={
['id'] = 11616,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công kích hoạt lên <font color='#f95208'>{2}</font> Bộ kiện, thu được đại lượng thuộc tính, tập hợp đủ toàn bộ sáo trang bộ kiện sau có thể đạt được  huyễn khốc kỹ năng hiệu quả!",
['link'] = "Ta sáo trang",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "71",
},
[11617]={
['id'] = 11617,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Tuần này cái thứ nhất thông quan địa cung Luyện Ngục thứ {2} Tầng, thu hoạch được {3}, BOSS Công thủ thuộc tính giảm xuống, bang phái thành viên nhưng cấp tốc tiến về khiêu chiến!",
['link'] = "Tiến về khiêu chiến",
['pos'] = "4",
['channel'] = 5,
['linkScript'] = "openlianyu",
['linkParam'] = "",
},
[11618]={
['id'] = 11618,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thừa lúc vắng mà vào, thông quan địa cung Luyện Ngục thứ {2} Tầng, thu hoạch được {3}, BOSS Khí thế gặp khó công thủ thuộc tính tiếp tục giảm xuống, bang phái thành viên nhưng cấp tốc tiến về khiêu chiến!",
['link'] = "Tiến về khiêu chiến",
['pos'] = "4",
['channel'] = 5,
['linkScript'] = "openlianyu",
['linkParam'] = "",
},
[11619]={
['id'] = 11619,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Tại động thiên tầm bảo lúc thu được {2}!",
['link'] = "Ta muốn luyện khí",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openSpiritWarprintCfg",
['linkParam'] = "",
},
[11620]={
['id'] = 11620,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Sử dụng {2} Thu được {3}!",
['link'] = "Ta muốn luyện khí",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openSpiritWarprintCfg",
['linkParam'] = "",
},
[11621]={
['id'] = 11621,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem kỵ binh lên tới {2} Giai, thu được {3}!",
['link'] = "Kỵ binh của ta",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "73",
},
[11622]={
['id'] = 11622,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bang phái <font color='#00FF00'>{1}</font> Hướng bang phái <font color='#00FF00'>{2}</font> Di tích pho tượng phát động công kích, thành công đánh tan pho tượng nhưng diện rộng hạ thấp <font color='#00FF00'>{3}</font> Thành viên treo máy kinh nghiệm tăng thêm!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11623]={
['id'] = 11623,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bang phái <font color='#00FF00'>{1}</font> Ngay tại tiến công bản bang di tích pho tượng, mời nhanh đi chi viện!",
['link'] = "Tiến về chi viện",
['pos'] = "4",
['channel'] = 5,
['linkScript'] = "openswyj",
['linkParam'] = "",
},
[11624]={
['id'] = 11624,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bang phái <font color='#00FF00'>{1}</font> Thành công đánh tan bang phái <font color='#00FF00'>{2}</font> Di tích pho tượng!<font color='#00FF00'>{3}</font> Bang phái thành viên tại bên trong di tích treo máy kinh nghiệm diện rộng hạ thấp, chữa trị pho tượng nhưng khôi phục kinh nghiệm tăng thêm!",
['link'] = "Tiến về chữa trị",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openswyj",
['linkParam'] = "",
},
[11625]={
['id'] = 11625,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bang phái <font color='#00FF00'>{1}</font> Thành công thủ hộ bản bang di tích pho tượng, bảo vệ bang phái vinh quang!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11626]={
['id'] = 11626,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bang phái <font color='#00FF00'>{1}</font> Chiếm lĩnh di tích thủ hộ, bang phái thành viên thu hoạch được thuộc tính tăng thêm.",
['link'] = "",
['pos'] = "3,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11627]={
['id'] = 11627,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Ngài bang phái đối bang phái <font color='#00FF00'>{1}</font> Chiếm lĩnh di tích pho tượng tuyên chiến thành công, hôm nay còn thừa tuyên chiến số lần: <font color='#00FF00'>{2}</font>",
['link'] = "",
['pos'] = "4",
['channel'] = 5,
['linkScript'] = "",
['linkParam'] = "",
},
[11628]={
['id'] = 11628,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bản phục người chơi <font color='#00FF00'>{1}</font> Thu hoạch được lần này vượt phục boss Tranh đoạt tư cách, xin mọi người chờ mong biểu hiện của bọn hắn đi!",
['link'] = "",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[11629]={
['id'] = 11629,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Chúng Titan boss Đã giáng lâm, tiến về mọi người nắm chặt tiến về đánh giết!",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11630]={
['id'] = 11630,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Chung cực boss Mang theo trọng bảo giáng lâm ở đây cảnh trung ương, muốn đoạt bảo dũng sĩ mời nắm chặt tiến về đánh giết!",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11631]={
['id'] = 11631,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Cấp cho boss{2} Một kích trí mạng, thu hoạch được hải lượng ban thưởng. Tất cả boss Đều bị đánh giết sau, cuối cùng boss Sẽ giáng lâm",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11632]={
['id'] = 11632,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Từ trong vạn quân chém giết chung cực boss, thu hoạch được hải lượng ban thưởng!",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11633]={
['id'] = 11633,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Tại chung cực boss Chiến đấu bên trong, tổn thương xếp hạng tối cao, thu hoạch được hải lượng ban thưởng",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11634]={
['id'] = 11634,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Mới một đợt bảo rương đã đổi mới!",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11635]={
['id'] = 11635,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "",
['link'] = "",
['pos'] = "1",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[11636]={
['id'] = 11636,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bản phục người chơi <font color='#00FF00'>{1}</font> Thu hoạch được lần này vượt phục lôi đài thi đấu tham dự tư cách, xin mọi người chờ mong biểu hiện của bọn hắn đi!",
['link'] = "",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[11637]={
['id'] = 11637,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bản phục người chơi <font color='#00FF00'>{1}</font> Thu hoạch được lần này vượt phục lôi đài thi đấu tư cách chiến hạng nhất, tiến vào 64 Mạnh, xin mọi người chờ mong biểu hiện của bọn hắn đi!",
['link'] = "",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[11638]={
['id'] = 11638,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bản phục người chơi <font color='#00FF00'>{1}</font> Thành công tấn cấp, tiến vào {2} Mạnh, xin mọi người chờ mong biểu hiện của hắn đi!",
['link'] = "",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[11639]={
['id'] = 11639,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Bản phục người chơi <font color='#00FF00'>{1}</font> Thu hoạch được năm nay vượt phục lôi đài thi đấu hạng nhất, tất cả người chơi thu hoạch được vinh quang ban thưởng!",
['link'] = "",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "",
['linkParam'] = "",
},
[11640]={
['id'] = 11640,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Một nhóm tiểu Tuyết người xuyên qua thời không giáng lâm tại Bắc Thương thành, mời các dũng sĩ nhanh đi bắt! Người tuyết nhưng tại ông già Noel chỗ hối đoái siêu giá trị đạo cụ!",
['link'] = "Lập tức tiến về",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openchristmasIntrusion",
['linkParam'] = "",
},
[11641]={
['id'] = 11641,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Chúc mừng người chơi <font color='#00FF00'>{1}</font> Kích hoạt thần võ, thu hoạch được thần võ {2}!",
['link'] = "Ta cũng muốn kích hoạt",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "87",
},
[11642]={
['id'] = 11642,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Chúc mừng người chơi <font color='#00FF00'>{1}</font> Thành công đột phá thần võ, thu hoạch được thần võ {2}!",
['link'] = "Ta cũng muốn đột phá",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "87",
},
[11643]={
['id'] = 11643,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Cùng {2} Vào khoảng {3}{4} Lúc -{5} Lúc tổ chức tân hôn khánh điển, kính thỉnh tham dự!",
['link'] = "Ta muốn kết hôn",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openMarry",
['linkParam'] = "",
},
[11644]={
['id'] = 11644,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Cùng {2} Xe hoa ngay tại tuần hành Bắc Thương thành, thân bằng hảo hữu nhóm nhưng tiến về xem lễ cùng đưa tặng chúc phúc.",
['link'] = "Ta muốn kết hôn",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openMarry",
['linkParam'] = "",
},
[11645]={
['id'] = 11645,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Cùng {2} Thành công kết làm phu thê, nguyện vợ chồng bọn họ ân ái, bạch đầu giai lão.",
['link'] = "Ta muốn kết hôn",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openMarry",
['linkParam'] = "",
},
[11646]={
['id'] = 11646,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Tiếp nhận {2} Cầu hôn, hai người đem kết làm cả đời bạn lữ, mọi người vì bọn họ chúc phúc đi!",
['link'] = "Ta muốn cầu hôn",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openMarry",
['linkParam'] = "",
},
[11647]={
['id'] = 11647,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Sử dụng <font color='#00FF00'>{2}</font> Đạo cụ, thu được <font color='#b324f6'>{3}</font>, thu được lộng lẫy vũ khí vẻ ngoài!",
['link'] = "Ta Thánh khí",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "62",
},
[11648]={
['id'] = 11648,
['prefix'] = "<img src='img://resfile/icon/chat_ch_2.png'/>",
['text'] = "{1} Sáng lập tổ đội khiêu chiến đội ngũ, đội ngũ nhu cầu <font color='#ffffff'> Chiến lực </font> Lớn hơn <font color='#ffffff'>{3}</font>, mau chạy tới người a, chậm liền không có địa.",
['link'] = "Ta muốn gia nhập",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openuzdtz",
['linkParam'] = "74",
},
[11649]={
['id'] = 11649,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Một nhóm tiểu Tuyết người xuyên qua thời không giáng lâm tại Bắc Thương thành, mời các dũng sĩ nhanh đi bắt! Người tuyết nhưng tại ông già Noel chỗ hối đoái siêu giá trị đạo cụ!",
['link'] = "Lập tức tiến về",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openchristmasIntrusion",
['linkParam'] = "",
},
[11650]={
['id'] = 11650,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Một nhóm tiểu Tuyết người xuyên qua thời không giáng lâm tại Bắc Thương thành, mời các dũng sĩ nhanh đi bắt! Người tuyết nhưng tại ông già Noel chỗ hối đoái siêu giá trị đạo cụ!",
['link'] = "Lập tức tiến về",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openchristmasIntrusion",
['linkParam'] = "",
},
[11651]={
['id'] = 11651,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Một nhóm tiểu Tuyết người xuyên qua thời không giáng lâm tại Bắc Thương thành, mời các dũng sĩ nhanh đi bắt! Người tuyết nhưng tại ông già Noel chỗ hối đoái siêu giá trị đạo cụ!",
['link'] = "Lập tức tiến về",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openchristmasIntrusion",
['linkParam'] = "",
},
[11652]={
['id'] = 11652,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Một nhóm tiểu Tuyết người xuyên qua thời không giáng lâm tại Bắc Thương thành, mời các dũng sĩ nhanh đi bắt! Người tuyết nhưng tại ông già Noel chỗ hối đoái siêu giá trị đạo cụ!",
['link'] = "Lập tức tiến về",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openchristmasIntrusion",
['linkParam'] = "",
},
[10653]={
['id'] = 10653,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Thành công thu thập {1}, điểm tích lũy {2}",
['link'] = "",
['pos'] = "3",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11654]={
['id'] = 11654,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công kích hoạt lên tâm pháp -{2}, thu hoạch được cao giai kỹ năng đặc thù, hủy thiên diệt địa đều ở một ý niệm!",
['link'] = "Ta muốn học tập",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openXinFa",
['linkParam'] = "114",
},
[11655]={
['id'] = 11655,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đạt tới {2} Cấp, thành công nhận lấy {3}, thu hoạch được hải lượng buộc nguyên ban thưởng!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11656]={
['id'] = 11656,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đạt tới {2} Cấp, thành công nhận lấy {3}, cầm trong tay thần binh đánh đâu thắng đó!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11657]={
['id'] = 11657,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đạt tới {2} Cấp, thành công nhận lấy {3}, chiến lực tiêu thăng, thăng cấp như bay cảm giác!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11658]={
['id'] = 11658,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đạt tới {2} Cấp, thành công nhận lấy {3}, ăn khỏa thăng cấp đan, lập tức bay vọt 100 Cấp!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11659]={
['id'] = 11659,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Đạt tới {2} Cấp, thành công nhận lấy {3}, lĩnh hội tuyệt học, từ đây một bước lên mây!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11660]={
['id'] = 11660,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Dũng mãnh phi thường vô cùng, đánh chết {2} Người mang dị bảo {3}, thu được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11661]={
['id'] = 11661,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Khoái mã dịch báo, người mang dị bảo rơi bảo quái hiện đã ở {1} Lộ ra tung tích, xin nhanh chóng tiến về đánh giết!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11662]={
['id'] = 11662,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Thành công kích hoạt thiên thần {2}, thiên thần phù hộ chiến lực tiêu thăng!",
['link'] = "Ông trời của ta thần",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "115",
},
[11663]={
['id'] = 11663,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Đồ ma điểm tích lũy đạt tới {2}, thành công nhận lấy {3} Kịch chiến BOSS Khiêu chiến phó bản không đáng kể!",
['link'] = "Ta muốn đồ ma",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "14",
},
[11664]={
['id'] = 11664,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Thành công đem thiên thần {2} Tăng lên đến {3} Tinh, thiên thần phù hộ chiến lực tăng vọt!",
['link'] = "Ông trời của ta thần",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "115",
},
[11665]={
['id'] = 11665,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Thành công đem thiên thần {2} Tăng lên đến {3} Tinh, thiên thần phù hộ chiến lực tăng vọt!",
['link'] = "Ông trời của ta thần",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "115",
},
[11666]={
['id'] = 11666,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Ngân lượng BOSS Đã xuất hiện, xin nhanh chóng tiến về đánh giết!",
['link'] = "Lập tức tiến về",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "16",
},
[11667]={
['id'] = 11667,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Ngân lượng BOSS HP còn thừa lại 50%, còn thừa tiền tài không nhiều lắm, xin mau sớm tiến về cướp đoạt!",
['link'] = "Lập tức tiến về",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "16",
},
[11668]={
['id'] = 11668,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Ngân lượng BOSS HP còn thừa lại 30%, còn thừa tiền tài không nhiều lắm, xin mau sớm tiến về cướp đoạt!",
['link'] = "Lập tức tiến về",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "16",
},
[11669]={
['id'] = 11669,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Ngân lượng BOSS HP còn thừa lại 10%, còn thừa tiền tài không nhiều lắm, xin mau sớm tiến về cướp đoạt!",
['link'] = "Lập tức tiến về",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "16",
},
[11670]={
['id'] = 11670,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ nhất phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11671]={
['id'] = 11671,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ hai phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11672]={
['id'] = 11672,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ ba phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11673]={
['id'] = 11673,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ tư phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11674]={
['id'] = 11674,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ năm phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11675]={
['id'] = 11675,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ sáu phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11676]={
['id'] = 11676,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ bảy phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11677]={
['id'] = 11677,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho giai đoạn thứ tám phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11678]={
['id'] = 11678,
['prefix'] = "<img src='img://resfile/icon/chat_ch_hd.png'/>",
['text'] = "Ngân lượng BOSS Cấp cho đệ cửu giai đoạn phúc lợi, tất cả mọi người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "3,4",
['channel'] = 3,
['linkScript'] = "",
['linkParam'] = "",
},
[11679]={
['id'] = 11679,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Ngân lượng BOSS Đã bị đánh giết, tham dự đánh giết người thu hoạch được đại lượng ban thưởng!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11680]={
['id'] = 11680,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem pháp bảo lên tới {2} Giai, thu được {3}!",
['link'] = "Pháp bảo của ta",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "120",
},
[11681]={
['id'] = 11681,
['prefix'] = "<img src='img://resfile/icon/chat_ch_2.png'/>",
['text'] = "{1} Sáng lập Mục Dã chi chiến đội ngũ, đội ngũ nhu cầu <font color='#ffffff'> Chiến lực </font> Lớn hơn <font color='#ffffff'>{3}</font>, mau chạy tới người a, chậm liền không có địa.",
['link'] = "Ta muốn gia nhập",
['pos'] = "4",
['channel'] = 2,
['linkScript'] = "openmuyewar",
['linkParam'] = "123",
},
[11682]={
['id'] = 11682,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "Người chơi {1} Góp nhặt {2} Kiện {3} Giai thần đúc trang bị, chiến lực tăng lên trên diện rộng!",
['link'] = "Ta muốn thu tập",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "60",
},
[11683]={
['id'] = 11683,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem ngọc bội lên tới {2} Giai, thu được {3}!",
['link'] = "Ngọc bội của ta",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "122",
},
[11684]={
['id'] = 11684,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Thành công đem bảo giáp lên tới {2} Giai, thu được {3}!",
['link'] = "Ta bảo giáp",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "openfunc",
['linkParam'] = "125",
},
[11685]={
['id'] = 11685,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Cho BOSS{2} Một kích cuối cùng, đại lượng bảo vật rơi đầy đất, nhanh đoạt a!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11686]={
['id'] = 11686,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Nhặt {2} Rơi xuống cực phẩm trang bị {3}!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
[11687]={
['id'] = 11687,
['prefix'] = "<img src='img://resfile/icon/chat_ch_bb.png'/>",
['text'] = "{1} Nhặt {2} Rơi xuống tử sắc trang bị {3}!",
['link'] = "",
['pos'] = "2,4",
['channel'] = 1,
['linkScript'] = "",
['linkParam'] = "",
},
};
