_G.t_qiyutiku={
[1]={
['id'] = 1,
['desc'] = "Trong trò chơi ai đẹp trai nhất?",
['options1'] = "A. Mục Trần",
['options2'] = "B. GM",
['options3'] = "C. Ta đẹp trai nhất",
['key'] = 3,
['rightWord'] = "Tiểu gia hỏa chính là muốn tự tin như vậy. Tiếp tục tiếp theo đề: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[2]={
['id'] = 2,
['desc'] = "Trong trò chơi ai xấu nhất?",
['options1'] = "A. Mục Trần",
['options2'] = "B. GM",
['options3'] = "C. Ngoại trừ ta những người khác xấu",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[3]={
['id'] = 3,
['desc'] = "Trang bị chế tạo có thể chế tạo cái gì trang bị",
['options1'] = "A. Màu trắng trang bị",
['options2'] = "B. Lam sắc trang bị",
['options3'] = "C. Trác tuyệt trang bị",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[4]={
['id'] = 4,
['desc'] = "Kỳ ngộ chủ yếu ban thưởng cái gì?",
['options1'] = "A. Kinh nghiệm",
['options2'] = "B. Tàng bảo đồ",
['options3'] = "C. Nguyên bảo",
['key'] = 1,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[5]={
['id'] = 5,
['desc'] = "Tông môn có thể thu hoạch cái gì?",
['options1'] = "A. Đại lượng linh lực",
['options2'] = "B. Nguyên bảo",
['options3'] = "C. Kinh nghiệm",
['key'] = 1,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[6]={
['id'] = 6,
['desc'] = "Trong trò chơi chỗ đó rơi trác tuyệt vũ khí?",
['options1'] = "A. Phó bản",
['options2'] = "B. Thế giới boss",
['options3'] = "C. Đều rơi",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[7]={
['id'] = 7,
['desc'] = "Ngày vòng mỗi ngày có thể làm nhiều ít vòng?",
['options1'] = "A. 20",
['options2'] = "B. 30",
['options3'] = "C. 50",
['key'] = 1,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[8]={
['id'] = 8,
['desc'] = "Thế giới boss Rơi xuống cái gì?",
['options1'] = "A. Vũ khí cực phẩm",
['options2'] = "B. Thương thành đạo cụ",
['options3'] = "C. Cái gì đều rơi",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[9]={
['id'] = 9,
['desc'] = "Đấu Phá Thương Khung sản xuất mấy trác tuyệt trang bị?",
['options1'] = "A. 1",
['options2'] = "B. 2",
['options3'] = "C. 3",
['key'] = 2,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[10]={
['id'] = 10,
['desc'] = "Thay đổi trang bị sau, cường hóa đẳng cấp giữ lại a?",
['options1'] = "A. Giữ lại",
['options2'] = "B. Không bảo lưu",
['options3'] = "C. Ta là đánh xì dầu",
['key'] = 1,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[11]={
['id'] = 11,
['desc'] = "Cái nào địa đồ có thể thời gian dài treo máy cày quái?",
['options1'] = "A. Cày đồ bí cảnh",
['options2'] = "B. Chủ thành",
['options3'] = "C. Đều có thể",
['key'] = 1,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[12]={
['id'] = 12,
['desc'] = "Cái nào địa đồ treo máy rơi bảo nhiều nhất?",
['options1'] = "A. Cày đồ bí cảnh",
['options2'] = "B. Chủ thành",
['options3'] = "C. Tân Thủ thôn",
['key'] = 1,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[13]={
['id'] = 13,
['desc'] = "Kinh nghiệm phó bản bên trong kinh nghiệm cỡ nào?",
['options1'] = "A. Xào gà nhiều",
['options2'] = "B. Nơi đó có kinh nghiệm?",
['options3'] = "C. Rất ít",
['key'] = 1,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[14]={
['id'] = 14,
['desc'] = "Làm sao thăng cấp nhanh nhất?",
['options1'] = "A. Ngồi xuống",
['options2'] = "B. Treo máy cày quái",
['options3'] = "C. Làm thanh nhiệm vụ bên trong các loại nhiệm vụ",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[15]={
['id'] = 15,
['desc'] = "Như thế nào mới có thể kiếm tiền biếu?",
['options1'] = "A. Tham gia trận doanh chiến trường hoạt động",
['options2'] = "B. Đánh boss",
['options3'] = "C. Đều được",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[16]={
['id'] = 16,
['desc'] = "Tầm bảo có thể đào ra cái gì?",
['options1'] = "A. Đạo cụ bảo rương",
['options2'] = "B. Thế giới boss",
['options3'] = "C. Giống như đều có thể",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
[17]={
['id'] = 17,
['desc'] = "Như thế nào mới có thể đại lượng thu hoạch được linh lực?",
['options1'] = "A. Tông môn thu hoạch",
['options2'] = "B. Đánh giết boss",
['options3'] = "C. Giống như đều có thể",
['key'] = 3,
['rightWord'] = "Tính ngươi lợi hại, đáp đúng. Tiếp tục: ",
['wrongWord'] = "Thực ngốc, cho ngươi thêm một cơ hội tốt",
},
};
