_G.t_questChapter={
[1]={
['id'] = 1,
['index'] = 1,
['name'] = "Biển mây chuyện cũ",
['des'] = "Vân Phá Thiên mở càng hư không.<br/> Sóng biển vỗ bờ đấu ác linh.<br/> Vãng sinh anh phách nay ở đâu?<br/> Chuyện phất y giấu công danh.",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,20",
},
[2]={
['id'] = 2,
['index'] = 2,
['name'] = "Mê thành phong vân",
['des'] = "Mê vụ mông lung che đậy hành tung.<br/> Thành tàn bích đoạn giấu gió lạnh.<br/> Mưa gió đầy lâu hỗn không sợ!<br/> Mây không có biến mất vạn sự không.",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,21",
},
[3]={
['id'] = 3,
['index'] = 3,
['name'] = "Máu nhuộm bí cảnh",
['des'] = "Huyết hải thâm cừu cuối cùng được báo.<br/> Nhiễm tóc mai hơi sương hận khó tiêu!<br/> Bí thuật sao đến thông thiên địa.<br/> Cảnh tịch tâm thà từ tiêu dao.",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,22",
},
[4]={
['id'] = 4,
['index'] = 4,
['name'] = "Tung hoành Hoang Hải",
['des'] = "Ta là một con cá u",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,23",
},
[5]={
['id'] = 5,
['index'] = 5,
['name'] = "Sơn cùng thủy tận",
['des'] = "Ta là một con cá u",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,24",
},
[6]={
['id'] = 6,
['index'] = 6,
['name'] = "Liễu ám hoa minh",
['des'] = "Ta là một con cá u",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,25",
},
[7]={
['id'] = 7,
['index'] = 7,
['name'] = "Yêu đêm bi ca",
['des'] = "Ta là một con cá u",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,26",
},
[8]={
['id'] = 8,
['index'] = 8,
['name'] = "Ma chiểu cự yêu",
['des'] = "Ta là một con cá u",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,27",
},
[9]={
['id'] = 9,
['index'] = 9,
['name'] = "Thần mộc chi huy",
['des'] = "Ta là một con cá u",
['icon'] = "chapter_i1",
['titleImg'] = "chapter_t1",
['reward'] = "att,100#def,28",
},
};
