_G.t_ranking={
[1]={
['id'] = 1,
['name'] = "Đẳng cấp",
['rank'] = 2,
['condition'] = 1,
['content'] = 70,
['funid'] = 1100,
},
[2]={
['id'] = 2,
['name'] = "Chiến lực",
['rank'] = 1,
['condition'] = 2,
['content'] = 10000,
['funid'] = 1100,
},
[3]={
['id'] = 3,
['name'] = "Tọa kỵ",
['rank'] = 3,
['condition'] = 3,
['content'] = 2,
['funid'] = 5,
},
[4]={
['id'] = 4,
['name'] = "Cảnh giới",
['rank'] = 6,
['condition'] = 3,
['content'] = 2,
['funid'] = 25,
},
[5]={
['id'] = 5,
['name'] = "Linh thú ( Vứt bỏ )",
['rank'] = 0,
['condition'] = 0,
['content'] = 0,
['funid'] = 0,
},
[6]={
['id'] = 6,
['name'] = "Linh trận ( Vứt bỏ )",
['rank'] = 0,
['condition'] = 0,
['content'] = 0,
['funid'] = 0,
},
[7]={
['id'] = 7,
['name'] = "Cực hạn BOSS( Vứt bỏ )",
['rank'] = 0,
['condition'] = 0,
['content'] = 0,
['funid'] = 0,
},
[8]={
['id'] = 8,
['name'] = "Cực hạn tiểu quái ( Vứt bỏ )",
['rank'] = 0,
['condition'] = 0,
['content'] = 0,
['funid'] = 0,
},
[9]={
['id'] = 9,
['name'] = "Thần binh",
['rank'] = 7,
['condition'] = 3,
['content'] = 2,
['funid'] = 21,
},
[10]={
['id'] = 10,
['name'] = "Pháp bảo",
['rank'] = 5,
['condition'] = 3,
['content'] = 2,
['funid'] = 120,
},
[11]={
['id'] = 11,
['name'] = "Bảo giáp",
['rank'] = 8,
['condition'] = 3,
['content'] = 2,
['funid'] = 125,
},
[12]={
['id'] = 12,
['name'] = "Ngọc bội",
['rank'] = 9,
['condition'] = 3,
['content'] = 2,
['funid'] = 122,
},
[13]={
['id'] = 13,
['name'] = "Thiên thần",
['rank'] = 4,
['condition'] = 3,
['content'] = 2,
['funid'] = 115,
},
};
