_G.t_vitality={
[1]={
['id'] = 1,
['name'] = "Hoàn thành toàn bộ ngày vòng nhiệm vụ",
['level'] = 35,
['num'] = 1,
['count'] = 20,
},
[2]={
['id'] = 2,
['name'] = "Hoàn thành 3 Lần kịch bản phó bản",
['level'] = 66,
['num'] = 5,
['count'] = 15,
},
[3]={
['id'] = 3,
['name'] = "Tham gia hoa quả nhạc viên hoạt động",
['level'] = 40,
['num'] = 10,
['count'] = 10,
},
[4]={
['id'] = 4,
['name'] = "Tham gia Tiên Ma chiến trường hoạt động",
['level'] = 40,
['num'] = 10,
['count'] = 10,
},
[5]={
['id'] = 5,
['name'] = "Bang phái cầu phúc 1 Lần",
['level'] = 40,
['num'] = 5,
['count'] = 5,
},
[6]={
['id'] = 6,
['name'] = "Tham gia 5 Lần linh quang phong ma",
['level'] = 65,
['num'] = 5,
['count'] = 25,
},
[7]={
['id'] = 7,
['name'] = "Tham dự thế giới boss Chiến đấu",
['level'] = 40,
['num'] = 5,
['count'] = 5,
},
[8]={
['id'] = 8,
['name'] = "Tham gia huyết chiến Bắc Thương giới hoạt động",
['level'] = 45,
['num'] = 10,
['count'] = 10,
},
[9]={
['id'] = 9,
['name'] = "Tham gia cực hạn khiêu chiến hoạt động",
['level'] = 120,
['num'] = 10,
['count'] = 10,
},
[10]={
['id'] = 10,
['name'] = "Tiến hành 10 Lần tầm bảo",
['level'] = 70,
['num'] = 5,
['count'] = 50,
},
[11]={
['id'] = 11,
['name'] = "Hoàn thành 3 Lần kỳ ngộ",
['level'] = 45,
['num'] = 10,
['count'] = 30,
},
[12]={
['id'] = 12,
['name'] = "Tham gia 1 Lần kinh nghiệm phó bản",
['level'] = 58,
['num'] = 20,
['count'] = 20,
},
[13]={
['id'] = 13,
['name'] = "Hoàn thành 5 Lần treo thưởng",
['level'] = 42,
['num'] = 5,
['count'] = 25,
},
};
