_G.t_vipmodel={
[10010001]={
['lookid'] = 10010001,
['name'] = "Nhị giai binh hồn",
['skl'] = "bh_luoli_flmhc.skl",
['skn'] = "bh_luoli_flmhc.skn",
['follow_idle'] = "bh_luoli_flmhc_daiji.san",
},
[10020001]={
['lookid'] = 10020001,
['name'] = "Nhị giai binh hồn",
['skl'] = "bh_mozu_dyhld.skl",
['skn'] = "bh_mozu_dyhld.skn",
['follow_idle'] = "bh_mozu_dyhld_daiji.san",
},
[10030001]={
['lookid'] = 10030001,
['name'] = "Nhị giai binh hồn",
['skl'] = "bh_renzu_syhtj.skl",
['skn'] = "bh_renzu_syhtj.skn",
['follow_idle'] = "bh_renzu_syhtj_daiji.san",
},
[10040001]={
['lookid'] = 10040001,
['name'] = "Nhị giai binh hồn",
['skl'] = "bh_yujie_cyml.skl",
['skn'] = "bh_yujie_cyml.skn",
['follow_idle'] = "bh_yujie_cyml_daiji.san",
},
[10000002]={
['lookid'] = 10000002,
['name'] = "Công kích đan",
['skl'] = "vip_gongjidan.skl",
['skn'] = "vip_gongjidan.skn",
['follow_idle'] = "vip_gongjidan.san",
},
[10000003]={
['lookid'] = 10000003,
['name'] = "Siêu cấp thăng cấp đan",
['skl'] = "vip_chaojishengjidan.skl",
['skn'] = "vip_chaojishengjidan.skn",
['follow_idle'] = "vip_chaojishengjidan.san",
},
[10000004]={
['lookid'] = 10000004,
['name'] = "Chí tôn VIP Vĩnh cửu kích hoạt khoán",
['skl'] = "vip_jihuoquan.skl",
['skn'] = "vip_jihuoquan.skn",
['follow_idle'] = "vip_jihuoquan.san",
},
[10000005]={
['lookid'] = 10000005,
['name'] = "Tọa kỵ tư chất đan",
['skl'] = "vip_zuoqishengjidan.skl",
['skn'] = "vip_zuoqishengjidan.skn",
['follow_idle'] = "vip_zuoqishengjidan.san",
},
[10000006]={
['lookid'] = 10000006,
['name'] = "Chúa tể chi ấn",
['skl'] = "",
['skn'] = "",
['follow_idle'] = "",
},
[10000007]={
['lookid'] = 10000007,
['name'] = "Linh thú làn da - Huyền băng tinh thú",
['skl'] = "ls_bingjingshou.skl",
['skn'] = "ls_bingjingshou.skn",
['follow_idle'] = "ls_lingjingshou_daiji.san",
},
[10000008]={
['lookid'] = 10000008,
['name'] = "7 Cấp bảo thạch",
['skl'] = "vip_baoshi.skl",
['skn'] = "vip_baoshi.skn",
['follow_idle'] = "vip_baoshi.san",
},
[10000009]={
['lookid'] = 10000009,
['name'] = "4 Giai cánh",
['skl'] = "cb_moyanziyi.skl",
['skn'] = "cb_moyanziyi.skn",
['follow_idle'] = "cb_moyanziyi_daiji.san",
},
[10100010]={
['lookid'] = 10100010,
['name'] = "Tam giai binh hồn",
['skl'] = "bh_luoli_qianyingsuimengfu.skl",
['skn'] = "bh_luoli_qianyingsuimengfu.skn",
['follow_idle'] = "bh_luoli_qianyingsuimengfu_daiji.san",
},
[10200010]={
['lookid'] = 10200010,
['name'] = "Tam giai binh hồn",
['skl'] = "bh_mozu_dyhld.skl",
['skn'] = "bh_mozu_dyhld.skn",
['follow_idle'] = "bh_mozu_dyhld_daiji.san",
},
[10300010]={
['lookid'] = 10300010,
['name'] = "Tam giai binh hồn",
['skl'] = "bh_renzu_slmhd.skl",
['skn'] = "bh_renzu_slmhd.skn",
['follow_idle'] = "bh_renzu_slmhd_daiji.san",
},
[10400010]={
['lookid'] = 10400010,
['name'] = "Tam giai binh hồn",
['skl'] = "bh_yujie_xhmw.skl",
['skn'] = "bh_yujie_xhmw.skn",
['follow_idle'] = "bh_yujie_xhmw_daiji.san",
},
[10100011]={
['lookid'] = 10100011,
['name'] = "4 Giai 3 Trác tuyệt vũ khí",
['skl'] = "zhujue_luoli_wuqi60_vipzhanshi.skl",
['skn'] = "zhujue_luoli_wuqi60_vipzhanshi.skn",
['follow_idle'] = "zhujue_luoli_wuqi60_vipzhanshi.san",
},
[10200011]={
['lookid'] = 10200011,
['name'] = "4 Giai 3 Trác tuyệt vũ khí",
['skl'] = "zhujue_mozu_wuqi60_vipzhanshi.skl",
['skn'] = "zhujue_mozu_wuqi60_vipzhanshi.skn",
['follow_idle'] = "zhujue_mozu_wuqi60_vipzhanshi.san",
},
[10300011]={
['lookid'] = 10300011,
['name'] = "4 Giai 3 Trác tuyệt vũ khí",
['skl'] = "zhujue_renzu_wuqi60_vipzhanshi.skl",
['skn'] = "zhujue_renzu_wuqi60_vipzhanshi.skn",
['follow_idle'] = "zhujue_renzu_wuqi60_vipzhanshi.san",
},
[10400011]={
['lookid'] = 10400011,
['name'] = "4 Giai 3 Trác tuyệt vũ khí",
['skl'] = "zhujue_yujie_wuqi60_vipzhanshi.skl",
['skn'] = "zhujue_yujie_wuqi60_vipzhanshi.skn",
['follow_idle'] = "zhujue_yujie_wuqi60_vipzhanshi.san",
},
[10000012]={
['lookid'] = 10000012,
['name'] = "Ác linh tử vong chiến xa",
['skl'] = "zq_motuoche.skl",
['skn'] = "zq_motuoche.skn",
['follow_idle'] = "zq_motuoche_chujidaiji.san",
},
[20010001]={
['lookid'] = 20010001,
['name'] = "Bạch ngân vip",
['skl'] = "zq_dujiaoshou.skl",
['skn'] = "zq_dujiaoshou.skn",
['follow_idle'] = "zq_dujiaoshou_chujidaiji.san",
},
[20010002]={
['lookid'] = 20010002,
['name'] = "Hoàng kim vip",
['skl'] = "cb_tianhuolongyi.skl",
['skn'] = "cb_tianhuolongyi.skn",
['follow_idle'] = "cb_tianhuolongyi_zhujue_daiji.san",
},
[20010003]={
['lookid'] = 20010003,
['name'] = "Kim cương vip",
['skl'] = "ls_yingmo.skl",
['skn'] = "ls_yingmo.skn",
['follow_idle'] = "ls_yingmo_daiji.san",
},
};
