_G.t_xuyuan={
[1]={
['id'] = 1,
['name'] = "Cấp thấp trứng",
['modelId'] = "mc_gangtiexia.sen",
['modelId2'] = "mc_gangtiexia.sen",
['showTip'] = "Ngẫu nhiên thu hoạch được linh lực cùng ngân lượng ban thưởng",
['egginfo'] = "Ngẫu nhiên thu hoạch được linh lực cùng ngân lượng ban thưởng",
['time'] = 24,
},
[2]={
['id'] = 2,
['name'] = "Trung cấp trứng",
['modelId'] = "mc_xiaohuangren.sen",
['modelId2'] = "mc_xiaohuangren.sen",
['showTip'] = "Ngẫu nhiên thu hoạch được đại lượng linh lực, ngân lượng, tiền biếu ban thưởng",
['egginfo'] = "Ngẫu nhiên thu hoạch được đại lượng linh lực, ngân lượng, tiền biếu ban thưởng",
['time'] = 48,
},
[3]={
['id'] = 3,
['name'] = "Cao cấp trứng",
['modelId'] = "mc_zhizhuxia.sen",
['modelId2'] = "mc_zhizhuxia.sen",
['showTip'] = "Ngẫu nhiên thu hoạch được bảo thạch mảnh vỡ, thăng tinh thạch, tọa kỵ, Linh thú tiến giai thạch ban thưởng",
['egginfo'] = "Ngẫu nhiên thu hoạch được bảo thạch mảnh vỡ, thăng tinh thạch, tọa kỵ, Linh thú tiến giai thạch ban thưởng",
['time'] = 72,
},
[4]={
['id'] = 4,
['name'] = "Siêu cấp trứng",
['modelId'] = "mc_anzai.sen",
['modelId2'] = "mc_anzai.sen",
['showTip'] = "Ngẫu nhiên thu hoạch được đại lượng thần linh, nguyên linh, kỵ chiến chờ hậu kỳ hệ thống tiến giai thạch ban thưởng",
['egginfo'] = "Ngẫu nhiên thu hoạch được đại lượng thần linh, nguyên linh, kỵ chiến chờ hậu kỳ hệ thống tiến giai thạch ban thưởng",
['time'] = 108,
},
[5]={
['id'] = 5,
['name'] = "Thần cấp trứng",
['modelId'] = "mc_bianfuxia.sen",
['modelId2'] = "mc_bianfuxia.sen",
['showTip'] = "Ngẫu nhiên một cái hệ thống thăng 1 Giai ban thưởng",
['egginfo'] = "Ngẫu nhiên một cái hệ thống thăng 2 Giai ban thưởng",
['time'] = 144,
},
};
