UIStrConfig:Add(
{
['makinoBattle1'] = '%s Cấp trở lên',
['makinoBattle10'] = 'Thoát',
['makinoBattle11'] = 'Lựa chọn đạo cụ:',
['makinoBattle12'] = '<u> Đổi mới </u>',
['makinoBattle13'] = '<u> Gọi kênh thế giới </u>',
['makinoBattle151'] = 'Lập đội ngũ',
['makinoBattle152'] = 'Một mình tiến vào',
['makinoBattle153'] = 'Tiến vào',
['makinoBattle154'] = 'Bắt đầu',
['makinoBattle155'] = 'Chuẩn bị',
['makinoBattle156'] = 'Rời đội',
['makinoBattle157'] = 'Nhập đội nhanh',
['makinoBattle158'] = 'Xin điền vào số lượng',
['makinoBattle159'] = 'Xác nhận',
['makinoBattle160'] = 'Hủy bỏ',
['makinoBattle161'] = 'Thoát',
['makinoBattle165'] = 'Đổi tuyến',
['makinoBattle166'] = 'Từ chối',
['makinoBattle205'] = '<u> Tiến về </u>',
['makinoBattle1001'] = 'Tiến vào tiêu hao: ',
['makinoBattle1003'] = 'Đội ngũ tên: ',
['makinoBattle1004'] = 'Điền mật mã vào: ',
['makinoBattle1005'] = 'Chiến lực yêu cầu: ',
['makinoBattle1006'] = 'Xin điền vào số lượng',
['makinoBattle1007'] = 'Người chơi gia nhập',
['makinoBattle1008'] = 'Lực chiến:',
['makinoBattle1009'] = 'Đội ngũ đủ sẽ tự động bắt đầu',
['makinoBattle1010'] = 'Không hạn chế',
['makinoBattle1011'] = 'Chỉ biểu hiện nhưng gia nhập đội ngũ',
['makinoBattle2000'] = '<u> Thông quan xếp hạng </u>',
['makinoBattle2001'] = '<u> Thu hồi </u>',
}
)
