StrConfig:Add(
{
['dominateRoute002'] = '<font color="#ff0000">%s</font>',
['dominateRoute003'] = 'Số lần khiêu chiến: <font color="%s">%s</font>',
['dominateRoute004'] = '<font color="#ff0000">%s</font>',
['dominateRoute005'] = '<font> số lần khiêu chiến còn: <font color = "#00ff00">%s</font></font>',
['dominateRoute006'] = '<font color="#ff0000"> Cần chờ cấp %s Cấp </font>',
['dominateRoute010'] = 'Số lần: %s',
['dominateRoute019'] = 'Thông quan thời gian sử dụng: <font color="#00ff00">%s</font>',
['dominateRoute020'] = 'Hiện tại thời gian: <font color="#00ff00">%s:%s</font>',
['dominateRoute021'] = '<u> Kích hoạt %s</u>',
['dominateRoute050'] = 'Hiện tại ngay tại khiêu chiến bên trong, phải chăng rời khỏi?',
['dominateRoute060'] = '<font color="#ff0000" size = "18" >%s Giây </font> Sau tự động lĩnh thưởng rời khỏi!',
['dominateRoute061'] = '<font color="#ff0000" size = "18" >%s Giây </font> Sau tự động rời khỏi',
['dominateRoute0100'] = 'Tinh lực khôi phục: <font color="#00ff00">%s Điểm /%s Phút </font>',
['dominateRoute0101'] = '( Kim cương VIP Có thể đạt được  khôi phục tăng thêm %s%%)',
['dominateRoute0105'] = '<font color="#ff0000">(%s Cấp )</font>',
['dominateRoute0106'] = '<font color="#00ff00">(%s Cấp )</font>',
['dominateRoute0150'] = 'Phải chăng tiêu hao <font color="#00ff00">%s Nguyên bảo </font> Lập tức hoàn thành?',
['dominateRoute0200'] = 'Hiện tại chương tiết tất cả cửa ải toàn bộ tam tinh nhưng nhận lấy!',
['dominateRoute0201'] = 'Tinh lực đã đủ',
['dominateRoute0202'] = 'Mua thành công',
['dominateRoute0203'] = 'Cấp vip chưa đủ',
['dominateRoute0204'] = 'Số lần không đủ',
['dominateRoute0205'] = 'Càn quét thất bại', -- Nguyên bảo không đủ
['dominateRoute0206'] = 'Mua sắm thất bại',
['dominateRoute0207'] = 'Hôm nay số lần khiêu chiến không đủ',
['dominateRoute0208'] = 'Tam tinh khiêu chiến số lần không đủ',
['dominateRoute0210'] = 'Tinh lực không đủ, không cách nào khiêu chiến',
['dominateRoute0211'] = 'Tổ đội không thể tiến vào',
['dominateRoute0212'] = 'Tiến vào thất bại',
['dominateRoute0213'] = 'Số lần tiến vào không đủ',
['dominateRoute0300'] = 'Sau khi hoàn thành mới có thể càn quét',
['dominateRoute0400'] = 'Thưởng qua ải',
['dominateRoute0401'] = 'Thưởng thủ thông ',
['dominateRoute0500'] = 'Còn thừa %s Phút %s Giây',
-- Mua sắm tinh lực
['dominateRoute0700'] = 'Ngươi tốn hao <font color="#00ff00">%s Nguyên bảo </font> Mua sắm %s Điểm tinh lực a?',
['dominateRoute0701'] = 'Số lần mua không đủ',
-- Mua sắm tinh lực tips
['dominateRoute0801'] = 'Hôm nay còn số lần mua: <font color="#00ff00">%s</font>',
['dominateRoute0802'] = 'Hiện tại mua sắm tiêu hao: <font color="#00ff00">%s</font> Nguyên bảo',
['dominateRoute0803'] = 'Đơn lần mua sắm gia tăng <font color="#00ff00">%s</font> Tinh lực',
['dominateRoute0804'] = '',
['dominateRoute0805'] = '<font color="#ff0000"> Hôm nay mua sắm đã đạt hạn mức cao nhất </font>',
['dominateRoute0900'] = 'Chúa tể con đường',
}
)
