StrConfig:Add(
{
["fumoatt"] = 'Công Kích: ',
["fumodef"] = 'Phòng Ngự: ',
["fumohp"] = 'Sinh Mệnh: ',
["fumohit"] = 'Chính Xác: ',
["fumododge"] = 'Né Tránh: ',
["fumocri"] = 'Bạo Kích: ',
["fumodefcri"] = 'Sức Bền: ',
["fumogress"] = "%s/%s",
["fumo111"] = 'Đạo cụ không đủ',
['fumo106'] = 'Chờ Cấp',
['fumo107'] = 'Chưa kích hoạt',
['fumo108'] = 'Cấp',
['fumo1000'] = "<font size='14' color='#ffffff'>%s</font>",
['fumo1001'] = "Hiện tại chưa kích hoạt toàn địa đồ thu thập tăng thêm",
['fumo1002'] = "Hiện tại chưa kích hoạt <font size='14' color='#00ff00'>[%s]</font> Thu thập tăng thêm",
['fumo1003'] = "<font size='14' color='#e6ad5c'> Tiếp theo đẳng cấp: </font>",
['fumo1004'] = "Đến tiếp sau đẳng cấp tạm chưa mở ra",
['fumo1005'] = "<font color = '#808080'> Chưa kích hoạt </font>",
['fumo1006'] = "<font color = '#00ff00'> Đã kích hoạt </font>",
['fumo1007'] = "<font color = '#d68637'>%s</font>  <font color = '#ffffff'>%s</font>",
['fumo1008'] = "Toàn địa đồ kích hoạt tăng thêm LV%s",
['fumo1009'] = "Tổng tiến độ đạt tới %s",
['fumo1010'] = "Thu thập tăng thêm LV%s",
['fumo1011'] = "<font size='14' color='#00ff00'>[%s]</font>",
})
