StrConfig:Add(
{
['timeDungeon001'] = 'Lực chiến yếu cầu: %s',
['timeDungeon002'] = 'Hôm nay có thể vào số lần: <font color="%s">%s/%s</font>',
['timeDungeon005'] = '<font color="#ff0000">(%s/%s)</font>',
['timeDungeon006'] = '<font color="#00ff00">(%s/%s)</font>',
['timeDungeon010'] = '<font color="#00ff00"><br/>( Đề nghị 4 Người tổ đội tiến vào, có thể đạt được  càng nhiều ích lợi )</font>',
['timeDungeon015'] = 'Mở ra hoạt động cần tiêu hao đạo cụ <u>%s</u>,  xác nhận?',
['timeDungeon016'] = 'Mở ra hoạt động cần tiêu hao đạo cụ <u>%s</u>, nên đạo cụ không đủ, phải chăng tiến đến mua sắm?',
['timeDungeon017'] = 'Ngươi thao tác quá nhanh , thử lại sau',
['timeDungeon030'] = 'Độ hoàn thành:',
['timeDungeon031'] = '%s%%',
['timeDungeon032'] = 'Cày quái ban thưởng theo đợt quái tăng lên, cày quái càng nhiều, ban thưởng càng lớn.',
['timeDungeon033'] = 'Thứ %s/%s Đợt',
['timeDungeon034'] = '%s: <font color="#00ff00">%s/%s</font>',
['timeDungeon035'] = 'Gộp lại thu hoạch được kinh nghiệm:',
['timeDungeon036'] = '%s',
['timeDungeon040'] = 'Phó bản chưa kết thúc, xác nhận rời khỏi?',
['timeDungeon049'] = 'Tin tức sai lầm',
['timeDungeon050'] = 'Hôm nay số lần không đủ',
['timeDungeon051'] = 'Cấp bậc chưa đủ',
['timeDungeon052'] = 'Ngài không phải đội trưởng',
['timeDungeon053'] = 'Vật phẩm không đủ',
['timeDungeon054'] = 'Nên hoạt động tạm chưa mở ra',
['timeDungeon055'] = 'Trước mắt tràng cảnh không thể truyền tống',
['timeDungeon056'] = 'Công năng chưa mở ra',
['timeDungeon057'] = 'Không biết sai lầm loại hình',
['timeDungeon058'] = 'Đạo cụ không đủ, không cách nào đổi độ khó',
['timeDungeon080'] = 'Thông quan ban thưởng kinh nghiệm: ',
['timeDungeon081'] = '<font color="#ff0000" size="18">%s Giây </font> Sau tự động rời khỏi phó bản!',
['timeDungeon082'] = '%s%%',
['timeDungeon083'] = 'Kết thúc phó bản: ',
['timeDungeon084'] = 'Phải chăng muốn  đổi lựa chọn độ khó',
['timeDungeon085'] = 'Đã ở trong đội ngũ',
['timeDungeon086'] = 'Mỗi 10 Phút gửi đi một lần!',
['timeDungeon087'] = 'Tiến độ phó bản trước mắt: ',
['timeDungeon088'] = 'Ban Thưởng qua ải: ',
['timeDungeon090'] = 'Quái vật đổi mới',
['timeDungeon091'] = 'Kết thúc phó bản',
['timeDungeon092'] = 'Độ hoàn thành đầy sau đem ra BOSS',
['timeDungeon093'] = 'Trước mắt đội ngũ nhân số:<font color="#00ff00">%s</font>  Mỗi đợt có thể quét ra:<font color="#00ff00">%s Chỉ </font>',
['timeDungeon0100'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thiên thần chiến trường phó bản toàn bộ ngày mở ra.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi ngày nhiều nhất có thể tham gia 2 Lần.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Sản xuất thiên thần thăng cấp cùng thiên thần đột phá tương quan đạo cụ.<img height='10'/></textformat>]],
['timeDungeon200'] = 'Chuẩn bị',
['timeDungeon201'] = 'Hủy bỏ chuẩn bị',
['timeDungeon202'] = 'Bắt đầu chiến đấu',
['timeDungeon1001'] = 'Đội ngũ: <font>%s</font>',
['timeDungeon1002'] = 'Hôm nay có thể vào số lần: <font color="#29cc00">%s/%s</font>',
['timeDungeon1003'] = '<u>%s1 Cái </u>',
['timeDungeon1004'] = '<font color="#ff0000">%s</font>',
['timeDungeon1005'] = '<font color="#00ff00">%s</font>',
['timeDungeon1006'] = 'Sáng tạo <font color="%s">(%s)</font> Phó bản',
['timeDungeon1011'] = 'Phổ thông',
['timeDungeon1012'] = 'Khó khăn',
['timeDungeon1013'] = 'Ác mộng',
['timeDungeon1014'] = 'Thần thoại',
['timeDungeon1015'] = 'Truyền thuyết',
['timeDungeon1016'] = 'Chiến lực nhu cầu: <font color="#00ff00">%s</font>',
['timeDungeon1017'] = 'Đội ngũ nhân số: <font color="#00ff00">%s/4</font>',
['timeDungeon1018'] = '<font color="%s">(%s)</font>',
['timeDungeon1019'] = 'Tổ đội trạng thái dưới không thể một mình tiến vào',
['timeDungeon1020'] = 'Ngài đã ở đội ngũ ở trong',
['timeDungeon1021'] = 'Đội viên không có quyền hạn',
['timeDungeon1022'] = 'Lực chiến: <font color="#00ff00">%s</font>',
['timeDungeon1023'] = '%s Tuyến',
['timeDungeon1024'] = 'Phó bản kết toán đếm ngược: ',
['timeDungeon1025'] = 'Quân địch sắp đột kích, xin chuẩn bị kỹ lưỡng!',
['timeDungeon1026'] = 'Quái vật đổi mới đếm ngược:',
-- Kinh nghiệm bội suất
['timeDungeon1050'] = 'Nhiều lần kinh nghiệm đan: <font color="#00ff00">%s%%</font>',
['timeDungeon1051'] = '( Trước mắt thăng cấp kinh nghiệm <font color="#00ff00">%s%%</font>)',
['timeDungeon1100'] = 'Đội trưởng đang chuẩn bị tiến vào <font color="%s">[ Thiên thần chiến trường phó bản ]</font>, ngài chưa chuẩn bị / Ngài cùng đội trưởng không còn cùng một cái tuyến.',
['timeDungeon1101'] = 'Phải chăng hoán đổi đến đội trưởng cùng tuyến đồng tiến nhập chuẩn bị trạng thái',
['timeDungeon1102'] = 'Đội trưởng đang chuẩn bị tiến vào <font color="%s"> Phó bản </font>, ngài chưa chuẩn bị / Ngài cùng đội trưởng không còn cùng một cái tuyến.',
-- Hò hét
['timeDungeon1900'] = '<font color="#ffffff">( Mã hóa )</font>',
['timeDungeon1901'] = '<font color="#ffffff">( Chưa mã hóa )</font>',
['timeDungeon2000'] = "Sáng lập <font color='%s'>[ Tổ đội kinh nghiệm phó bản ·%s</font>] Đội ngũ <font color='#00ff00'>( Kinh nghiệm bội suất: %s Lần )</font>, đội ngũ nhu cầu <font color='#ffffff'> Chiến lực </font> Lớn hơn <font color='#ffffff'>%s</font>, mau chạy tới người a, chậm liền không có địa.{6,script=openfunc,text= Ta muốn gia nhập,t_param=20}",
-- Kinh nghiệm đan sử dụng
['timeDungeon3000'] = 'Nhắc nhở',
['timeDungeon3001'] = 'Sử dụng 1.5 Lần kinh nghiệm đan có thể thu hoạch được kinh nghiệm càng nhiều, phải chăng lập tức sử dụng?',
['timeDungeon3002'] = 'Xác nhận sử dụng',
['timeDungeon3003'] = 'Ngài đã có bao nhiêu lần kinh nghiệm đan tại sử dụng',
['timeDungeon3004'] = '1.5 Lần kinh nghiệm đan không đủ sử dụng',
['timeDungeon3005'] = '<font color = "#00ff00"> Chúc mừng ngài, sử dụng kinh nghiệm đan thành công!</font>',
}
)
