UIStrConfig:Add(
{
['timeDungeon1'] = '%s Cấp trở lên người chơi',
['timeDungeon2'] = '<u> Chi tiết quy tắc </u>',
['timeDungeon4'] = '<u> Phổ thông bằng chứng </u>',
['timeDungeon5'] = '<u> Khó bằng chứng </u>',
['timeDungeon6'] = '<u> Ác mộng bằng chứng </u>',
['timeDungeon7'] = '<u> Thần thoại bằng chứng </u>',
['timeDungeon8'] = '<u> Truyền thuyết bằng chứng </u>',
['timeDungeon9'] = '<u> Hợp thành bằng chứng </u>',
['timeDungeon10'] = 'Thoát phó bản',
['timeDungeon11'] = 'Lựa chọn vào đạo cụ:',
['timeDungeon12'] = '<u> Đổi mới BHX </u>',
['timeDungeon13'] = '<u> Thế giới </u>',
['timeDungeon50'] = 'Mở ra thời gian:',
['timeDungeon51'] = 'Điều kiện:',
['timeDungeon100'] = '<font color="#9ddaf9">%s</font>',
['timeDungeon151'] = 'Tạo đội ngũ',
['timeDungeon152'] = 'Một mình vào',
['timeDungeon153'] = 'Tiến vào',
['timeDungeon154'] = 'Bắt đầu trò chơi',
['timeDungeon155'] = 'Chuẩn bị',
['timeDungeon156'] = 'Thoát đội ngũ',
['timeDungeon157'] = 'Nhanh chóng gia nhập',
['timeDungeon158'] = 'Xin điền vào 6 người',
['timeDungeon159'] = 'Xác nhận',
['timeDungeon160'] = 'Hủy bỏ',
['timeDungeon161'] = 'Thoát',
['timeDungeon165'] = 'Đổi tuyến cũng chuẩn bị',
['timeDungeon166'] = 'Cự Tuyệt',
--tips Văn bản
['timeDungeon201'] = 'Tổ đội kinh nghiệm phó bản',
['timeDungeon202'] = 'Đánh tan ma vương, hấp thu linh khí nhập thể, gia tốc ngươi chúa tể con đường!',
['timeDungeon203'] = 'Lượng lớn kinh nghiệm, thương thành đạo cụ',
['timeDungeon204'] = 'Rơi bảo vật',
['timeDungeon205'] = '<u> Đi tới </u>',
['timeDungeon251'] = 'Lượng kinh nghiệm, chủ yếu thăng cấp đường tắt',-- Nhắc nhở UI Bên trong
['timeDungeon300'] = 'Sản xuất lượng lớn kinh nghiệm, chủ yếu thăng cấp đường tắt',-- Chủ giao diện
['timeDungeon1001'] = 'Tiến tới tiêu hao: ',
['timeDungeon1002'] = '( Vẻn vẹn đội trưởng tiêu hao )',
['timeDungeon1003'] = 'Đội ngũ tên: ',
['timeDungeon1004'] = 'Điền mật mã vào: ',
['timeDungeon1005'] = 'Chiến lực yêu cầu: ',
['timeDungeon1006'] = 'Xin điền vào 6 người',
['timeDungeon1007'] = 'Trở lên người chơi gia nhập',
['timeDungeon1008'] = 'Lực chiến hạn chế:',
['timeDungeon1009'] = 'Đội ngũ người đầy tự động bắt đầu',
['timeDungeon1010'] = 'Không hạn chế',
['timeDungeon1011'] = 'Chỉ biểu hiện nhưng gia nhập đội ngũ',
['timeDungeon1012'] = 'Kinh nghiệm rất lớn: ',
['timeDungeon1013'] = '<u> Mở ra túi đồ </u>',
}
)
