StrConfig:Add(
{
['login1'] = 'Tên nhân vật quá dài',
['login2'] = 'Tên nhân vật có ký tự không hợp lệ',
['login3'] = 'Danh tự không thể vì không',
['login4'] = 'Tên nhân vật đã tồn tại',
['login5'] = 'Tạo nhân vật thất bại',
['login6'] = 'Đăng ký thất bại: Thời gian đâm sai lầm',
['login7'] = 'Đăng ký thất bại: Kí tên không xứng đôi',
['login8'] = 'Đăng ký thất bại',
['login9'] = 'Đăng ký thất bại: Tài khoản bị block.<br/> Còn thừa thời gian: %s Ngày %s Giờ %s Phút',
['login10'] = '%s Cấp',
['login21'] = 'Tài khoản của ngươi tại cái khác địa phương đăng ký!',
['login22'] = 'Tài khoản của ngươi bị block!<br/> Thời gian: %s Ngày %s Giờ %s Phút',
['login23'] = 'Tài khoản ngắt kết nối tới Server',
['login24'] = 'Tài khoản của ngươi block!<br/> Thời gian: %s Ngày %s Giờ %s Phút',
['login25'] = 'Số liệu đồng bộ sai',
['login26'] = 'Tràng cảnh Server cắt ra',
['login27'] = 'Ngươi bị GM Đá khỏi kênh',
['login31'] = "",
['login32'] = "Xin tắt trò chơi sau đó chọn [ Thử lại ] Nút bấm đổi mới",
['login41'] = "Kết nối quá thời hạn, hãy kết nối!",
['login42'] = "Ngắt kết nối <br/> Mời đăng nhập lại",
['login43'] = "Server địa chỉ phân tích sai lầm, mời thử lại",
['login44'] = "Server nhận địa chỉ thất bại",
['login45'] = "Yêu cầu phi pháp",
['login46'] = "Đăng ký thất bại <br/>Error: Hiệp nghị không nhất trí",
['login47'] = "Đăng ký thất bại <br/>MAC Phong cấm",
['login48'] = "Địa chỉ máy chủ sai, mời thử lại",
['login49'] = "Đăng nhập thất bại: Server chưa khởi động",
['login50'] = "Đăng nhập thất bại: Người chơi đang trong game",
['login51'] = "Đăng nhập thất bại:ErrorCode,",
['login52'] = "Đường truyền có vấn đề, ngắt kết nối khỏi Server, mời đăng nhập lại",
['login53'] = "Hiện tại Server đã đầy, đề nghị lựa chọn những server khác",
['login54'] = "Hiện tại Server đã đầy, đề nghị refesh trang web thử lại",
['login55'] = "Hệ thống báo ngươi sử dụng chương trình phi pháp",
['login56'] = "Hệ thống báo ngươi sử dụng chương trình phi pháp <br/> Ngươi bị block: %s Ngày %s Giờ %s Phút",
['login57'] = "Kết nối dữ liệu thất bại",
['login58'] = "%s Giây sau tự động sáng tạo đồng tiến nhập trò chơi",
}
)
