StrConfig:Add(
{
['setsys0100'] = 'Phím khóa này đã sử dụng , sử dụng phím khóa khác !',
['setsys0105'] = 'Ngài sửa chữa thiết trí chưa bảo tồn, phải chăng không bảo tồn quan bế?',
['setsys0120'] = 'Hệ thống là ngài đề cử một bộ kỹ năng khóa vị thiết trí, Đồng ý ?',
['setsys0125'] = 'Ngài rời đi trò chơi thời gian quá dài, GM Tiểu muội đã giúp ngài hoán đổi đến thấp phối trạng thái giảm bớt máy vi tính hao tổn lượng điện a!',
['setsys0200'] = "<font color='#29cc00'> Bảo tồn thành công </font>",
['setsys0300'] = 'Kỹ năng %s',
['setsys0350'] = 'Kỹ năng %s',
['setsys0400'] = 'Nên khóa không thể dùng',
-- Kỹ năng giới thiệu ký tự xuyên
['setsys1'] = 'Kỹ năng 1',
['setsys2'] = 'Kỹ năng 2',
['setsys3'] = 'Kỹ năng 3',
['setsys4'] = 'Kỹ năng 4',
['setsys5'] = 'Kỹ năng 5',
['setsys6'] = 'Kỹ năng 6',
['setsys7'] = 'Kỹ năng 7',
['setsys8'] = 'Kỹ năng 8',
['setsys9'] = 'Kỹ năng 9',
['setsys10'] = 'Kỹ năng 10',
['setsys11'] = 'Kỹ năng 11',
['setsys12'] = 'Kỹ năng 12',
['setsys13'] = 'Kỹ năng 13',
['setsys14'] = 'Kỹ năng 14',
['setsys15'] = 'Linh thú kỹ năng 1',
['setsys16'] = 'Linh thú kỹ năng 2',
['setsys17'] = 'Linh trận kỹ năng',
['setsys18'] = 'Thánh khí kỹ năng',
['setsys50'] = 'Khoảng trắng',
['setsys51'] = 'Trái',
['setsys52'] = 'Phải',
['setsys61'] = 'Kỹ năng',
['setsys62'] = 'Phím tắt',
['setsys71'] = 'Hiệu quả thiết trí',
['setsys72'] = 'Biểu hiện thiết trí',
['setsys73'] = 'Lẫn nhau thiết trí',
['setsys74'] = 'Che đậy thiết trí',
['setsys75'] = 'Không bảo tồn',
['setsys76'] = 'Điểm sai',
['setsys77'] = 'Ta trở về',
}
)
