StrConfig:Add(
{
['personalboss1'] = 'Cấp khiêu chiến: <font color="#ffffff">%s</font>',
['personalboss2'] = 'Cấp khiêu chiến: <font color="#ff0000">%s</font>',
['personalboss3'] = 'Hôm nay còn: <font color="#00ff00">%s</font>',
['personalboss4'] = 'Hôm nay còn: <font color="#ff0000">%s</font>',
['personalboss5'] = '<font color="#00ff00">%s</font>',
['personalboss6'] = '<font color="#ff0000">%s</font>',
['personalboss7'] = 'Hôm nay còn: %s Lần',
['personalboss8'] = '%s*%s',
['personalboss9'] = 'Thưởng hàng ngày: ',
['personalboss10'] = 'Xác suất rơi: ',
['personalboss11'] = 'Tiêu hao',
['personalboss12'] = '<font color="#ff0000" size = "18" >%s Giây </font> Sau tự động rời khỏi',
['personalboss13'] = 'Thêm lần tiến vào 1.',
['personalboss14'] = 'Hôm nay miễn phí số lần còn: <font color="#00ff00">%s</font>',
['personalboss20'] = 'Xác nhận rời khỏi?',
['personalboss101'] = 'Cấp bậc chưa đủ',
['personalboss102'] = 'Số lần không đủ',
['personalboss103'] = 'Không phải VIP',
['personalboss104'] = 'Tổ đội không thể tiến vào',
['personalboss105'] = 'Tiến vào dị thường',
['personalboss106'] = 'Tiến vào thất bại',
['personalboss107'] = 'Đạo cụ không đủ',
['personalboss108'] = 'Phó bản đang tiến hành',
['personalboss200'] = 'Xin hãy chờ',
['personalboss201'] = 'Hiện tại chưa diễn ra',
['personalboss202'] = 'Bấm vào đây tự động theo thứ tự khiêu chiến có được miễn phí khiêu chiến',
['personalboss203'] = 'Căn cứ chọn số lần, tự động khiêu chiến!',
['personalboss204'] = [[<textformat> Có thể lựa chọn số lần đối trước mắt BOSS Tiến hành khiêu chiến, ngoài định mức số lần tiêu hao <font color="%s"><u>%s</u></font>.</textformat>]],
}
)
