StrConfig:Add(
{
['skill1'] = 'Loại Kỹ Năng',
['skill2'] = 'Giãn cách',
['skill3'] = 'Tầm xa',
['skill4'] = 'Nội lực',
['skill5'] = 'Chủ động',
['skill6'] = 'Hiệu quả',
['skill7'] = 'Đánh đơn',
['skill8'] = 'Phạm vi',
['skill9'] = "%s/%s Cấp",
['skill10'] = '%0.1f Giây',-- Thời gian cooldown
['skill11'] = 'Hiệu quả',
['skill12'] = "Hạ cấp hiệu quả",
['skill13'] = "Max cấp hiệu quả",
['skill14'] = 'Bị động hiệu quả',
['skill15'] = 'Bị động hiệu quả',
['skill16'] = 'Quang hoàn hiệu quả',
['skill50'] = "Hiện tại có kỹ năng có thể thăng cấp <br/><font color='#29cc00'> Nhấp chuột thăng cấp </font>",
['skill51'] = "Hiện tại có tuyệt học có thể thăng cấp <br/><font color='#29cc00'> Nhấp chuột thăng cấp </font>",
-- Kỹ năng bảng
['skill101'] = "<font color='#DC2F2F'> Chưa học được </font>",
['skill102'] = "<font color='#00ff00'>%s/%s Cấp </font>",
['skill103'] = "<font color='#f4e036' size='16'> Điều kiện học tập: </font><br/>",
['skill104'] = "<font color='#f4e036' size='16'> Thăng cấp điều kiện: </font><br/>",
['skill105'] = "%s: <font color='#2fe00d'>%s( Đã đạt thành )</font>",
['skill106'] = "%s: <font color='#ff0000'>%s( Không đủ )</font>",
['skill107'] = "%s Cấp",
['skill108'] = "<font color='#65c47e'> Đã đạt tới cao cấp nhất </font>",
['skill109'] = "<font color='#65c47e'> Chúc mừng bạn, kỹ năng thăng cấp thành công!</font>",
['skill110'] = "Điều kiện không đủ, không cách nào thăng cấp",
['skill111'] = "Tọa kỵ cấp bậc",
['skill112'] = "Thu hoạch được tổng thuộc tính:",
['skill113'] = "Thu hoạch được hạ cấp tổng thuộc tính:",
['skill114'] = "<font color='#2fe00d'><u>%s(%s)</u>( Đã đạt thành )</font>",
['skill115'] = "<font color='#ff0000'><u>%s(%s)</u>( Không đủ )</font>",
['skill116'] = "Hiện tại tu vi: <font color='#2fe00d'>%s</font>",
-- Tuyệt học bảng  adder:hoxudong date:2015/5/19:14:49
['magicskill001'] = "<font color='#00ff00'>%s Cấp %s Nặng </font>",
['skill1001'] = "Kỹ năng đang hồi!",
['skill1002'] = "Kỹ năng đang thi triển!",
['skill1003'] = "Kỹ năng cần có mục tiêu thi triển",
['skill1004'] = "Khoảng cách không đủ",
['skill1005'] = "Thể lực không đủ",
['skill1006'] = "Sinh lực không đủ",
['skill1007'] = "Nội lực không đủ",
['skill1008'] = "Hồn linh không đủ",
['skill1009'] = "Trạng thái không thể thi triển kỹ năng",
['skill1010'] = "Bản đồ không thể thi triển linh trận kỹ năng",
['skill1011'] = "Mục tiêu không thể thi triển kỹ năng này",
['skill1012'] = "Kỹ năng cần cưỡi ngựa",
['skill1013'] = "Trong hoạt động không thể thi triển kỹ năng",
['skill1014'] = "Trong hoạt động thiên thần không thể đổi thân",
['skill1015'] = "Năng lượng không đủ không cách nào thi triển",
['skill1101'] = "Hiện tại khu vực không thể công kích người chơi khác",
['skill1102'] = "Mục tiêu trong trạng thái bảo hộ",
['skill1103'] = "Hình thức PK đang chọn không thể công kích nên người chơi",
['skill1104'] = "NPC Không thể công kích",
['skill10001'] = "Tiến vào trạng thái chiến đấu",
['skill10002'] = "Rời khỏi trạng thái chiến đấu",
['skill100001'] = "Tiến vào khu vực an toàn",
['skill100002'] = "Rời khu vực an toàn",
-- Kỹ năng mau lẹ thiết trí bảng
['skill201'] = "Kỹ năng cơ bản",
['skill202'] = "Phổ thông kỹ năng",
['skill203'] = "Kỹ năng đặc thù",
['skill1000001'] = " < Bảo Hộ Tân Thủ >",
['skill1000002'] = " < Trong trang thái bảo hộ tân thủ >",
['skill1000003'] = " < Trang trai bảo hộ cày đêm >",
['skill10000001'] = "Bảo rương không thuộc về bạn, không cách nào nhặt",
['skill5001'] = 'Nguyên linh thuẫn số lượng không đủ',
['skill5002'] = 'Kích hoạt nguyên linh sau mở ra kỹ năng',
['skill00011'] = "Tiến độ:%s/%s",
-- Tuyệt học đột phá bảng
['skill8000'] = '<font>%s</font> Đã đủ cấp có thể đột phá đến <font color= "#00ff00">%s</font> Cấp',
['skill8001'] = '<font>%s Cấp </font>',
['skill8002'] = '<font color="#E7D6B5"> Đột phá tiêu hao:</font><u><font color="#2fe00D">%sX%s</font></u>',
['skill8003'] = 'Có được:<font color="%s">%s</font>',
['skill8004'] = 'Max cấp',
['skill8005'] = 'Tuyệt học',
['skill8006'] = 'Tâm pháp',
['skill8007'] = 'Tuyệt học đột phá',
}
)
