StrConfig:Add(
{
['interServiceDungeon1'] = 'Tham dự điều kiện: ',
['interServiceDungeon2'] = 'Giới thiệu người số: ',
['interServiceDungeon3'] = 'Hôm nay còn thừa số lần: ',
['interServiceDungeon4'] = "<font color='%s'><font color='#c8c8c8'> Điểm tích lũy: </font>%s</font>",
['interServiceDungeon5'] = "<font color='%s'><font color='#c8c8c8'> Công huân: </font>%s</font>",
['interServiceDungeon6'] = 'Nửa đường rời khỏi điểm tích lũy giảm phân nửa, phải chăng xác định rời khỏi?',
['interServiceDungeon7'] = 'Hôm nay xứng đôi số lần đã dùng hết',
['interServiceDungeon8'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Vượt phục PVP Quy tắc:</font>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục PVP Thời gian hoạt động bên trong mở ra, mỗi ngày nhưng khiêu chiến 10 Lần.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi ngày trước 5 Trận khiêu chiến có thể đạt được  gấp đôi điểm tích lũy, điểm tích lũy nhiều ít đem ảnh hưởng đến kết toán lúc người đẳng cấp lên xuống.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục PVP Mỗi ngày 22:00 Đổi mới bảng xếp hạng, căn cứ người chơi đẳng cấp xếp hạng nhận lấy ban thưởng.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Công huân nhưng tại công huân cửa hàng hối đoái hi hữu đạo cụ.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Căn cứ bản phục người chơi tại bạch kim, kim cương đẳng cấp nhân số, toàn bộ server người chơi mỗi ngày đồng đều nhưng nhận lấy vinh quang ban thưởng, nhân số càng nhiều, ban thưởng càng cao.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục PVP Mỗi tháng 15 Hào 24:00 Cùng ngày cuối cùng 24:00 Tiến hành trận đấu mùa giải kết toán, kết toán lúc xếp hạng trước ba người chơi có thể đạt được  độc hữu xưng hào.<img height='10'/></textformat>]],
['interServiceDungeon9'] = 'Vượt phục PVP Thể nghiệm phiên bản tạm chưa mở ra bảng xếp hạng',
['interServiceDungeon10'] = 'Vượt phục PVP Thể nghiệm phiên bản tạm chưa mở ra đẳng cấp ban thưởng',
['interServiceDungeon11'] = 'Hiện tại tạm thời chưa có xếp hạng <br/> Vượt phục PVP Bảng xếp hạng 22:00 Đổi mới',
['interServiceDungeon12'] = 'Đã ở vượt phục xứng đôi bên trong, không thể xứng đôi',
['interServiceDungeon13'] = 'Tổ đội trạng thái không thể xứng đôi',
['interServiceDungeon14'] = 'Xứng đôi chưa mở ra',
['interServiceDungeon15'] = 'Chưa tới xứng đôi thời gian',
['interServiceDungeon16'] = 'Đã đạt mỗi ngày xứng đôi hạn mức cao nhất',
['interServiceDungeon17'] = 'Tại trong sân đấu không thể xứng đôi',
['interServiceDungeon18'] = 'Tại phó bản hoặc là trong hoạt động không thể xứng đôi',
['interServiceDungeon19'] = 'Chưa mở ra vượt phục công năng',
['interServiceDungeon20'] = 'Không thể xứng đôi',
['interServiceDungeon21'] = 'Hiện tại ngay tại vượt phục xứng đôi bên trong, phải chăng rời khỏi xứng đôi?',
['interServiceDungeon22'] = 'Thoát',
['interServiceDungeon23'] = 'Điểm kích mở ra xứng đôi giao diện',
['interServiceDungeon24'] = '<font color="%s">(%s/%s)',
['interServiceDungeon25'] = '1. Căn cứ bản phục người chơi tại bạch kim, kim cương đẳng cấp nhân số, toàn bộ server người chơi mỗi ngày đồng đều nhưng nhận lấy vinh quang ban thưởng.<br/>2. Tiến vào đẳng cấp nhân số càng nhiều, ban thưởng càng cao.<br/>3. Mỗi ngày vượt phục kết toán kết thúc sau nhưng lĩnh thưởng',
['interServiceDungeon26'] = 'Trở về',
['interServiceDungeon27'] = '<u> Tiếp theo giai đoạn </u>',
['interServiceDungeon28'] = 'Thoát',
['interServiceDungeon29'] = 'Bản phục chiến lực bảng xếp hạng trước 10 Lại ≥125 Cấp người chơi',
['interServiceDungeon30'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Vượt phục boss Quy tắc:</font>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục boss Mỗi tuần 2, tuần 6 Muộn 21: 00-22: 00 Mở ra.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục boss Mở ra trước 10 Phút lúc, chiến lực bảng xếp hạng trước 10 Tên người chơi lại ≥125 Cấp người chơi tự động thu hoạch được tham chiến tư cách.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vẻn vẹn khai phục 3 Thiên hậu Server có thể tham dự vượt phục boss Tranh đoạt.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Dựa theo khai phục thời gian, khác biệt Server đem chia làm nhiều cái vượt phục boss Chiến khu, mỗi cái chiến khu tham dự cùng một xoải dài phục boss Tranh đoạt.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục boss Chia làm nhỏ boss, lớn boss, bảo rương tranh đoạt 3 Cái giai đoạn, cũng có phong phú ban thưởng.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/>boss Ban thưởng chia làm tổn thương xếp hạng ban thưởng cùng đánh giết ban thưởng 2 Loại.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Bảo rương tranh đoạt lúc, mỗi cách một đoạn thời gian trên trận đem ngẫu nhiên đổi mới bảo rương, nhưng thu thập thu hoạch được bảo rương. Đánh giết người khác nhưng cướp đoạt người khác bộ phận bảo rương, ít nhất cướp đoạt 1 Cái.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục boss Tất cả ban thưởng tại vượt phục boss Hoạt động kết thúc sau thống nhất cấp cho <img height='10'/></textformat>]],
['interServiceDungeon31'] = 'Mỗi tuần hai, sáu muộn %s~%s',
['interServiceDungeon32'] = 'Tháng này ngày cuối cùng 24:00',
['interServiceDungeon33'] = 'Tháng này 15 Ngày 24:00',
['interServiceDungeon34'] = 'Vượt phục BOSS Hoạt động đã mở khải, phải chăng tiến vào?',
['interServiceDungeon35'] = 'Giây sau tự động lĩnh thưởng rời khỏi',
['interServiceDungeon36'] = 'Đếm ngược kết thúc sau, đem đổi mới BOSS./r Không phải bản phục người chơi có thể tự do PK, làm tốt tìm đều chuẩn bị đi!',
['interServiceDungeon37'] = 'Tổn thương xếp hạng',
['interServiceDungeon38'] = 'Người chơi tính danh',
['interServiceDungeon39'] = 'Tổn thương lượng',
['interServiceDungeon40'] = 'Ban thưởng',
['interServiceDungeon41'] = 'Tổng thưởng: ',
['interServiceDungeon42'] = '( Ban thưởng sẽ tại hoạt động kết thúc đi sau thả )',
['interServiceDungeon43'] = '%s Phút',
['interServiceDungeon44'] = 'Đánh giết người khác nhưng cướp đoạt bảo rương, kết thúc lúc theo bảo rương số kết toán ban thưởng',
['interServiceDungeon45'] = 'Không lên bảng',
['interServiceDungeon46'] = 'Đánh giết',
['interServiceDungeon47'] = 'Không đánh giết ban thưởng',
['interServiceDungeon48'] = 'Chưa đổi mới',
['interServiceDungeon49'] = 'Đã đổi mới',
['interServiceDungeon50'] = 'Tử vong',
['interServiceDungeon51'] = 'Công kích thủ hộ',
['interServiceDungeon52'] = 'Phòng ngự thủ hộ',
['interServiceDungeon53'] = 'Sinh mệnh thủ hộ',
['interServiceDungeon54'] = 'Khôi phục thủ hộ',
['interServiceDungeon55'] = 'Chúc mừng ngài thu hoạch được năm nay vượt phục boss Tranh đoạt tư cách, mời cùng 21: 00 Đúng giờ tham dự.',
['interServiceDungeon56'] = "%s:%s Phút sau bắt đầu",
['interServiceDungeon57'] = "Hoạt động kết thúc sau, điểm tích lũy xếp hạng thứ nhất người chơi đem thu hoạch được ngày mai đấu vòng loại tư cách.",
['interServiceDungeon58'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Vượt phục lôi đài thi dự tuyển quy tắc:</font>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thời gian hoạt động bên trong đánh giết không thua kém 500 phút người chơi nhưng cướp đoạt đối phương điểm tích lũy.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Người chơi điểm tích lũy càng cao, đem nó đánh giết sau cướp đoạt điểm tích lũy càng nhiều, tràng cảnh bên trong đánh giết người chơi khác có thể đạt được  quân công dùng cho quân hàm thăng cấp.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Nửa đường rời khỏi người chơi điểm tích lũy giảm phân nửa.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Hoạt động kết thúc lúc điểm tích lũy đệ nhất người chơi có thể đạt được  bản thi đấu khu lôi đài thi đấu xuất chiến tư cách.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Hoạt động kết thúc sau, căn cứ người chơi điểm tích lũy có thể đạt được  đại lượng ban thưởng, ban thưởng tại trở lại bản phục sau bưu kiện cấp cho.<img height='10'/></textformat>]],
['interServiceDungeon59'] = "Điểm tích lũy %s-%s Ở giữa người chơi có thể đạt được ",
['interServiceDungeon60'] = "Điểm tích lũy %s Trở lên người chơi có thể đạt được ",
['interServiceDungeon61'] = "Chúc mừng ngài thành công tấn cấp <font color='#2FE00D' size='24'>%s Mạnh </font>, làm sơ chỉnh đốn sau, xin chú ý tham gia trận tiếp theo tranh tài",
['interServiceDungeon62'] = "Tấn cấp thất bại, mời tại lần sau hoạt động lúc không ngừng cố gắng, tranh thủ thu hoạch được tốt hơn chiến tích.",
['interServiceDungeon63'] = "Thứ %s Giới vượt phục lôi đài thi đấu",
['interServiceDungeon64'] = "Nên thứ tự có thể đạt được : <br/>",
['interServiceDungeon65'] = "Vượt phục lôi đài thi đấu tư cách",
['interServiceDungeon66'] = "Vượt phục lôi đài thi đấu tư cách chiến đã mở khải, phải chăng tiến vào",
['interServiceDungeon67'] = "Trận tiếp theo tranh tài vào khoảng một phút sau bắt đầu, mời sớm làm tốt dự thi chuẩn bị.",
['interServiceDungeon68'] = "Chiến lực",
['interServiceDungeon69'] = "Đặt cược tổng kim ngạch: <font color='#C8C8C8'>%s</font>",
['interServiceDungeon70'] = "Cổ vũ số lần: <font color='#C8C8C8'>%s</font>",
['interServiceDungeon71'] = "Vạn",
['interServiceDungeon72'] = "Chúc mừng ngài thu hoạch được quán quân",
['interServiceDungeon73'] = 'Đêm nay %s Xin chú ý kịp thời tham dự, làm gốc phục người chơi làm vẻ vang!',
['interServiceDungeon74'] = 'Tư cách người chơi tin tức',
['interServiceDungeon75'] = '( Hôm qua bản phục chiến lực bảng trước mười tạm chờ cấp lớn hơn 150 Cấp )',
['interServiceDungeon76'] = 'Thể nghiệm phiên bản tạm chưa mở ra',
['interServiceDungeon77'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Vượt phục lôi đài thi đấu quy tắc:</font>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi tuần thứ ba, thứ bảy 00:00 Chiến lực bảng kết toán trước mười người chơi có được vượt phục lôi đài thi dự tuyển tư cách.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi tuần thứ ba, thứ bảy 20:30-21:00 Vì vượt phục lôi đài thi dự tuyển thời gian, thi dự tuyển thi đấu khu điểm tích lũy hạng nhất người chơi nhưng có được ngày thứ hai lôi đài thi đấu tư cách.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi tuần thứ tư, chủ nhật 21:30-22:15 Vì vượt phục lôi đài thi đấu thời gian, tranh tài khai thác đơn trận đào thải tấn cấp phương thức.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thứ tư 8:00-18:00 Có thể tiến hành đặt cược, đặt cược chỉ có thể sử dụng ngân lượng đối một dự thi người chơi đặt cược một lần, đặt cược người chơi thu hoạch được quán quân sau, đối đặt cược người chơi đem theo người tập trung kim ngạch tỉ lệ chia sẻ tất cả ban thưởng.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Thứ tư 18:00-20:00 Có được lôi đài thi đấu tư cách người chơi có thể đối tự mình tiến hành cổ vũ, cổ vũ tiêu hao Nguyên bảo, có thể đạt được  tấn cấp thi đấu công thủ máu 5% Tăng thêm.<img height='10'/></textformat>]],
['interServiceDungeon78'] = "Chúc mừng ngài thành công tấn cấp <font color='#2FE00D' size='24'> Trận chung kết </font>, làm sơ chỉnh đốn sau, xin chú ý tham gia trận tiếp theo tranh tài",
['interServiceDungeon79'] = 'Hiện tại cổ vũ số lần: ',
['interServiceDungeon80'] = 'Lần',
['interServiceDungeon81'] = 'Cổ vũ số lần càng nhiều, tiêu hao càng nhiều',
['interServiceDungeon82'] = 'Lần này tiêu hao: ',
['interServiceDungeon83'] = '%s Nguyên bảo',
['interServiceDungeon84'] = 'Cổ vũ số lần đã đạt hạn mức cao nhất',
['interServiceDungeon85'] = 'Nguyên bảo không đủ',
['interServiceDungeon86'] = 'Ngân lượng không đủ',
['interServiceDungeon87'] = 'Xin điền vào ngài muốn đặt cược kim ngạch',
['interServiceDungeon88'] = 'Vạn',
['interServiceDungeon89'] = 'Đặt cược kim ngạch thấp nhất vì 10 Vạn tối cao vì 1000 Vạn',
['interServiceDungeon90'] = 'Có được tấn cấp thi đấu tư cách người chơi nhưng tại hạn định thời gian bên trong tiêu hao Nguyên bảo vì chính mình cổ vũ, mỗi lần cổ vũ có thể đạt được  nhân vật thuộc tính công thủ máu 5% Ngoài định mức tăng thêm, cổ vũ số lần càng nhiều, tiêu hao càng nhiều.',
['interServiceDungeon201'] = 'Không có cổ vũ tư cách',
['interServiceDungeon202'] = 'Không tại cổ vũ thời gian bên trong',
['interServiceDungeon203'] = 'Xin điền vào kim ngạch',
['interServiceDungeon204'] = 'Ngài đã đặt cược',
['interServiceDungeon205'] = 'Đặt cược thành công',
['interServiceDungeon301'] = 'Bởi vì đối thủ vắng mặt, ngài tại lượt này trong trận đấu luân không, thu hoạch được tư cách thăng cấp, mời lặng chờ vòng tiếp theo tranh tài',
['interServiceDungeon302'] = "<font color='#ff0000' size='16'>%s</font> Giây sau tự động lĩnh thưởng rời khỏi",
['interServiceDungeon303'] = "<font color='#00ff00'> Thưởng ao tổng kim ngạch </font>: %s",
['interServiceDungeon401'] = "Phút",
['interServiceDungeon402'] = "Mỗi ngày %s-%s",
['interServiceDungeon403'] = "Đẳng cấp ≥%s Cấp",
['interServiceDungeon404'] = "( Bản phục người chơi nhưng tại tràng cảnh bên trong tổ đội )",
['interServiceDungeon405'] = [[<textformat leftmargin='5'><font color='#e59607' size='16'> Vượt phục tràng cảnh quy tắc:</font>
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục tràng cảnh mỗi ngày 13: 00-21:00 Mở ra.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi ngày có thể hoàn thành 5 Lần nhiệm vụ, nhiệm vụ Tinh cấp càng cao ban thưởng càng cao, cùng ngày chưa hoàn thành cùng chưa nhận lấy ban thưởng nhiệm vụ, ngày thứ hai đem thanh không, xin chú ý kịp thời nhận lấy.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Nhiệm vụ ban thưởng cần trở lại bản phục sau nhận lấy.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Hoàn thành mỗi ngày nhiệm vụ có thể đạt được  vượt phục điểm tích lũy, vượt phục điểm tích lũy dùng cho thương thành hối đoái.
<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Vượt phục tràng cảnh bên trong tổng cộng chia làm 5 Cái trận doanh, bản phục người chơi vì cùng một trận doanh, khác biệt trận doanh ở giữa nhưng PK, cùng phục người chơi nhưng tổ đội, tràng cảnh bên trong đánh giết người chơi khác có thể đạt được  quân công dùng cho quân hàm thăng cấp.<img height='10'/></textformat>]],
['interServiceDungeon406'] = "Đá ra",
['interServiceDungeon407'] = "Gia nhập",
['interServiceDungeon408'] = "Mời",
['interServiceDungeon409'] = "Đánh giết",
['interServiceDungeon410'] = "",
['interServiceDungeon411'] = " Người chơi tính danh        Đẳng cấp      Lực chiến      Thao tác",
['interServiceDungeon412'] = " Đội trưởng tính danh        Lực chiến     Đội ngũ nhân số      Thao tác",
['interServiceDungeon413'] = " Người chơi tính danh        Đẳng cấp      Lực chiến      Thao tác",
['interServiceDungeon414'] = "Sau phục sinh",
['interServiceDungeon415'] = "%s Thỉnh cầu gia nhập ngài đội ngũ! Có đồng ý hay không?",
['interServiceDungeon416'] = "%s Mời ngài gia nhập đội ngũ của hắn! Có đồng ý hay không?",
['interServiceDungeon417'] = "Không đủ thời gian",
['interServiceDungeon418'] = "Không tư cách",
['interServiceDungeon419'] = "Không tại hoạt động thời gian",
['interServiceDungeon420'] = "Hoạt động tràng cảnh số người đã đủ",
['interServiceDungeon421'] = "Nhiệm vụ tiếp đi thành công",
['interServiceDungeon422'] = "Hủy bỏ nhiệm vụ thành công!",
['interServiceDungeon423'] = "Lĩnh thưởng thành công",
['interServiceDungeon424'] = "Thoát khỏi đội thành công",
['interServiceDungeon425'] = "Sáng tạo đội ngũ thành công",
['interServiceDungeon426'] = "Thỉnh cầu gửi đi thành công",
['interServiceDungeon427'] = "Đội ngũ đã đủ",
['interServiceDungeon428'] = "Đội ngũ không tồn tại",
['interServiceDungeon429'] = "Thành công đá ra nên đội viên",
['interServiceDungeon430'] = "Mời thành công",
['interServiceDungeon431'] = "Nên người chơi không tại trước mắt tràng cảnh",
['interServiceDungeon432'] = "Người chơi không tồn tại",
['interServiceDungeon433'] = "Người chơi đã tổ đội",
['interServiceDungeon434'] = "Xin đã phát ra",
['interServiceDungeon435'] = "Người chơi",
['interServiceDungeon436'] = " Đã hoàn thành",
['interServiceDungeon437'] = "Ngài xác định từ bỏ nên nhiệm vụ sao?",
['interServiceDungeon438'] = "Thất bại",
['interServiceDungeon439'] = "Cấp bậc chưa đủ",
['interServiceDungeon440'] = "Số lần không đủ",
['interServiceDungeon441'] = "Không thể xác nhận",
['interServiceDungeon442'] = "Công năng chưa mở ra",
['interServiceDungeon443'] = "Thất bại",
['interServiceDungeon444'] = "Ngài đã có đội ngũ",
['interServiceDungeon445'] = "Không có đội ngũ",
['interServiceDungeon446'] = "Ngài không phải đội trưởng",
['interServiceDungeon447'] = "Thành viên không tại",
['interServiceDungeon448'] = "Đã hoàn thành nhiệm vụ, không cách nào từ bỏ!",
['interServiceDungeon449'] = "Nhiệm vụ không tồn tại",
['interServiceDungeon450'] = "Không cách nào tổ đội tiến vào vượt phục tràng cảnh",
['interServiceDungeon451'] = "Tiến vào thất bại",
['interServiceDungeon452'] = "Hiện tại tràng cảnh không cách nào tiến vào",
['interServiceDungeon453'] = "Đánh giết số",
['interServiceDungeon454'] = "Bị giết số",
['interServiceDungeon455'] = "Hôm nay nhiệm vụ đã toàn bộ hoàn thành",
['interServiceDungeon456'] = "Nhiệm vụ ban thưởng: Hoàn thành nhiệm vụ sau ban thưởng, cần trở về bản phục lĩnh thưởng.",
['interServiceDungeon457'] = "Hối đoái cửa hàng: Hoàn thành mỗi ngày nhiệm vụ có thể đạt được  điểm tích lũy tiến hành siêu giá trị hối đoái.",
['interServiceDungeon458'] = "Nhiệm vụ liệt biểu: Mỗi ngày có thể hoàn thành 5 Lần vượt phục nhiệm vụ, thu hoạch được siêu giá trị ban thưởng.",
['interServiceDungeon459'] = "Lập tức đổi mới một đợt nhiệm vụ, còn thừa đổi mới số lần tùy thời ở giữa hồi phục, mỗi %s Phút khôi phục 1 Lần.",
['interServiceDungeon460'] = "Đồng thời nhưng xác nhận / Hoàn thành %s Cái nhiệm vụ",
['interServiceDungeon461'] = "Tử vong trạng thái, không cách nào tiến về!",
['interServiceDungeon462'] = "Đội ngũ nhân viên đã đủ",
['interServiceDungeon463'] = "Hiện tại hoạt động chưa mở ra",
['interServiceDungeon464'] = "Khảo thí phiên bản, tạm không mở ra",
['interServiceDungeon465'] = "",
['interServiceDungeon466'] = "",
['interServiceDungeon467'] = "",
['interServiceDungeon468'] = "",
['interServiceDungeon469'] = "",
['interServiceDungeon46'] = "",
['interServiceDungeon91'] = "Nửa đường rời khỏi theo thất bại tính toán, phải chăng xác định rời khỏi?",
['interServiceDungeon92'] = "Lần này vượt phục lôi đài thi đấu tư cách thi đấu bên trong ngài biểu hiện xuất chúng, thu hoạch được điểm tích lũy thứ nhất, thu hoạch được ngày mai đấu vòng loại tư cách dự thi, xin chú ý kịp thời tham dự!",
['interServiceDungeon93'] = "Ban thưởng trở lại bản phục sau sẽ lấy bưu kiện phương thức gửi đi, xin chú ý kiểm tra và nhận.",
['interServiceDungeon94'] = "Điểm tích lũy",
}
)
