StrConfig:Add(
{
['lovelypet1'] = "Manh sủng công năng chưa mở ra",
['lovelypet2'] = "Manh sủng công năng đã mở khải",
['lovelypet3'] = "%s Giờ %s Phút %s Giây",
['lovelypet4'] = "<u>%s</u>",
['lovelypet5'] = "%s",
['lovelypet6'] = "%s Ngày %s Giờ %s Phút %s Giây",
['lovelypet7'] = "%s Ngày",
['lovelypet8'] = "Đạo cụ không đủ, không thể tục phí",
['lovelypet9'] = "Nguyên bảo không đủ, không thể tục phí",
['lovelypet10'] = "%s Cấp thu hoạch được thủ hộ nhỏ cùng sủng",
['lovelypet11'] = "<font color='#a0a0a0'> Giết quái kinh nghiệm đề cao 20%</font><br/><font color='#a0a0a0'> Tự động nhặt rơi xuống vật phẩm </font>",
['lovelypet12'] = "<font color='#ffcc33'> Manh sủng </font><br/><font color='#dcdcdc'> Manh sủng xuất chiến nhưng trên diện rộng đề cao giết quái kinh nghiệm cùng tự động nhặt đạo cụ </font><br/><font color='#00ff00'> Điểm kích lựa chọn manh sủng xuất chiến </font>",
['lovelypet13'] = "<font color='%s'>%s</font><br/>%s<br/><font color='#00ff00'> Điểm kích hoán đổi manh sủng xuất chiến </font>",
['lovelypet14'] = "<font color='#00ff00'><u>%s</u></font>",
['lovelypet15'] = "<font color='#cc0000'><u>%s</u></font>",
['lovelypet16'] = "Ngài nhỏ cùng sủng đã qua kỳ <br/><font color='#29cc00'> Điểm kích xem xét </font>",
['lovelypet17'] = "Tục phí ( <font color='#ffcd7e'>%s</font> Nguyên bảo )",
['lovelypet18'] = "<font color='#29cc00'> Tục phí thành công </font>",
['lovelypet19'] = "<font color='#32961e'>%s Cấp </font>",
['lovelypet20'] = "<font color='#cc0000'>%s Cấp </font>",
['lovelypet21'] = "Cấp bậc chưa đủ, không thể kích hoạt",
['lovelypet22'] = "<font color='#00ff00'> Nguyên bảo: <u>%s</u>( Tục phí 30 Ngày )</font>",
['lovelypet23'] = "<font color='#cc0000'> Nguyên bảo: <u>%s</u>( Tục phí 30 Ngày )</font>",
['lovelypet24'] = "%s Ngày %s Giờ %s Phút",
['lovelypet25'] = "Đạo cụ không đủ, không thể kích hoạt",
['lovelypet26'] = "Kích hoạt vĩnh viễn",
['lovelypet27'] = "Kích hoạt vĩnh viễn, không mất phí",
['lovelypet28'] = "Ngài nhỏ cùng sủng không có xuất chiến <br/><font color='#29cc00'> Điểm kích xem xét </font>",
['lovelypet1000'] = "<font color='#ffffff'>%s</font>",
['lovelypet1001'] = "<font color='#00b7ef'>%s</font>",
['lovelypet1002'] = "<font color='#b324f6'>%s</font>",
['lovelypet1003'] = "<font color='#ff6600'>%s</font>",
['lovelypet1004'] = "<font color='#dc1d03'>%s</font>",
}
);
