UIStrConfig:Add(
{
['lovelypet1'] = "Kích  Sống",
['lovelypet2'] = "Ra  Chiến",
['lovelypet3'] = "Thu  Về",
['lovelypet4'] = "Tục  Phí",
['lovelypet5'] = "Tục Phí",
['lovelypet6'] = "Lấy Tiêu",
['lovelypet7'] = "Nguyên bảo",
['lovelypet8'] = "Tục phí",
['lovelypet9'] = "<u> Tiến về thương thành </u>",
['lovelypet1001'] = "Công  Kích:",
['lovelypet1002'] = "Phòng  Ngự:",
['lovelypet1003'] = "Sinh  Mệnh:",
['lovelypet1004'] = "Đối Boss Tổn thương:",
['lovelypet1005'] = "Đối tiểu quái tổn thương:",
['lovelypet1006'] = "Tốc độ di chuyển:",
['gongji'] ="Công kích",
['fangyu'] ="Phòng ngự",
['hunli'] = "Hồn lực",
['tipo'] = "Thể phách",
['mingzhon'] ="Chính xác",
['baoji'] ="Bạo kích",
['xueliang'] ="HP",
['rengxin'] ="Sức bền",
['baojishanghai'] ="Bạo kích tổn thương",
['baojifangyu'] ="Bạo kích phòng ngự",
['chuangcishanghai'] ="Đâm xuyên tổn thương",
['gedangdengji'] ="Đón đỡ đẳng cấp",
['gedangdeng'] ="Đón đỡ",
['shanghaizengjia'] ="Tổn thương gia tăng",
['shanghaijianshao'] ="Tổn thương giảm bớt",
}
)
