UIStrConfig:Add(
{
['gem01'] = 'Gia tăng sức chiến đấu',
['gem02'] = 'Hủy bỏ',
['gem03'] = 'Bảo thạch thuộc tính tăng thêm: ',
['gem04'] = 'Lực chiến tăng thêm: ',
['gem05'] = 'Mời lựa chọn bảo thạch',
['gem06'] = 'Bảo thạch thăng cấp danh sách',
['gem07'] = 'Tiêu hao: ',
['gem08'] = 'Xác định',
['gem09'] = 'Hủy bỏ',
['gem010'] = 'Thăng cấp',
['gem011'] = 'Thay đổi',
['gem012'] = 'Dỡ bỏ',
['gem013'] = 'Khảm nạm',
['gem014'] = 'Kích hoạt thuộc tính: ',
['gem015'] = 'Gia tăng sức chiến đấu',
['gem016'] = 'Trang bị liệt biểu',
['gem017'] = 'Bảo thạch mắt xích',
['gem018'] = 'Cường hóa',
['gem019'] = 'Thăng tinh',
['gem020'] = 'Bảo thạch',
['gem021'] = 'Kèm theo',
['gem022'] = 'Dung hợp',
['gem023'] = 'Tẩy luyện',
['gem026'] = 'Kỹ năng',
['gem027'] = 'Tuyệt học',
['gem028'] = 'Tâm pháp',
['gem029'] = 'Một mình phó bản',
['gem030'] = 'Kinh nghiệm phó bản',
['gem031'] = 'Tổ đội phó bản',
['gem032'] = 'Tổ đội kinh nghiệm',
}
)
