StrConfig:Add(
{
-- Pháp bảo bảng
['lingQi001'] = 'Pháp bảo cấp bậc',
['lingQi002'] = '<font color="#e59607"> Hiện tại pháp bảo độ thuần thục đẳng cấp: %s<br>%s<br><font color="#e56a10"> Mỗi lần phát động <font color="#00b7ef">%s</font> Lúc, độ thuần thục đều sẽ tăng lên </font>',
['lingQi003'] = "Đã thăng đến cao giai nhất",
['lingQi004'] = "Công  Kích: %s",
['lingQi005'] = "Phòng  Ngự: %s",
['lingQi006'] = "Bạo  Kích: %s",
['lingQi007'] = "Sinh  Mệnh: %s",
['lingQi008'] = "Bạo  Tổn thương: %s",
['lingQiplus008'] = "Chính Xác: %s",
['lingQiplus009'] = "Né  Tránh: %s",
['lingQiplus010'] = "Xuyên  Đâm: %s",
['lingQi009'] = "<font color='#29cc00'> Đã đạt tới trước mắt cấp bậc tối cao độ thuần thục đẳng cấp </font>",
-- Pháp bảo tiến giai bảng
['lingQi010'] = "Tiến giai tiêu hao: ",
['lingQi011'] = "Ngân lượng: ",
['lingQi012'] = "<u><font color='%s'>%s%s Khỏa </font></u>",
-- Pháp bảo kỹ năng thăng cấp bảng
['lingQi013'] = "%s:<br><font color='#c8c8c8'>1, giai vị:<font color='%s'>%s Giai %s</font><br>2, cần tiêu hao đạo cụ:</font>",
['lingQi014'] = "Đạo cụ không đủ",
['lingQi015'] = "Pháp bảo cấp bậc không đủ",
['lingQi016'] = "Đã tập được",
['lingQi017'] = "Chưa tập được",
['lingQi018'] = "( Đã đạt thành )",
['lingQi019'] = "( Chưa đạt thành )",
-- Nhắc nhở tin tức
['lingQi020'] = "Độ thuần thục không đủ",
['lingQi021'] = "Ngân lượng không đủ",
['lingQi022'] = "Đạo cụ số lượng không đủ",
['lingQi023'] = "Độ thuần thục đầy sau mới có thể thăng giai",
['lingQi024'] = "<font color='#e59607'> Hiện tại chúc phúc giá trị: <font color='#dcdcdc'>%s</font></font><br/><font color='#e59607'> Chúc phúc giá trị thanh không tình trạng: </font><font color='#e56a10'> Chúc phúc giá trị tại mỗi ngày rạng sáng <font color='#00ff00'>6 Điểm </font> Về không </font><br/><font color='#e59607'> Chúc phúc giá trị nói rõ: </font><br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Mỗi lần chưa thể thành công tiến giai, đều đem tăng lên chúc phúc giá trị.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị càng cao, lần sau thao tác xác suất thành công càng cao.<br/><img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Chúc phúc giá trị thăng đầy sau, thì lần sau thăng giai thao tác nhất định thành công </font>",
['lingQi025'] = "Hiện tại kỹ năng đã thăng đến đẳng cấp cao nhất",
['lingQi026'] = "Độ thuần thục: ",
['lingQi027'] = "Thắp sáng hạ khỏa tinh có thể gia tăng như sau thuộc tính: \n%s",
['lingQi028'] = "Pháp bảo kỹ năng",
['lingQi029'] = "Thăng cấp điều kiện",
['lingQi030'] = "Điều kiện học tập",
['lingQi031'] = "Thăng cấp kỹ năng",
['lingQi032'] = "Học tập kỹ năng",
['lingQi033'] = "Độ thuần thục đầy sau có thể thăng giai",
['lingQi034'] = "Đạo cụ không đủ, không cách nào tiến giai",
['lingQi035'] = "Ngân lượng không đủ, không cách nào tiến giai",
['lingQi036'] = "Công Kích",
['lingQi037'] = "Phòng Ngự",
['lingQi038'] = "Sinh Mệnh",
['lingQi039'] = "Bạo Kích",
['lingQi040'] = "Chính Xác",
['lingQi041'] = "Bạo Tổn thương",
['lingQi042'] = "Phá Phòng",
['lingQi043'] = "Xuyên Đâm",
['lingQi044'] = "Kim linh <font color='%s'>%s</font>",
['lingQi045'] = "Mộc linh <font color='%s'>%s</font>",
['lingQi046'] = "Thủy linh <font color='%s'>%s</font>",
['lingQi047'] = "Hỏa linh <font color='%s'>%s</font>",
['lingQi048'] = "Thổ Linh <font color='%s'>%s</font>",
['lingQi049'] = "Chưa kích hoạt",
['lingQi050'] = "<font color='#E59607' size='16'> Thuộc tính tổng tăng thêm </font><br/>%s",
['lingQi051'] = "<font color='#D5B772'>%s</font>  <font color='#00ff00'>%s</font>",
['lingQi052'] = "Pháp bảo cấp bậc không đủ, không cách nào kích hoạt",
['lingQi053'] = "Binh Linh cấp bậc",
['lingQi054'] = "<font color='#e59607' size='16'> Quy tắc nói rõ:</font><img height='10'/>%s</textformat>",
['lingQi055'] = "<font color='%s'> Pháp bảo đạt tới %s Giai có thể tùy ý kích hoạt Binh Linh: %s</font>",
['lingQi056'] = "<font color='%s'> Hiện tại pháp bảo %s Giai, còn có thể tùy ý kích hoạt Binh Linh số lượng: %s</font>",
['lingQi057'] = "<font color='%s'> Pháp bảo đạt tới %s Giai, nhưng lần nữa kích hoạt Binh Linh: %s</font>",
['lingQi058'] = "<img width='15' height='15' vspace='-2' src='img://resfile/icon/rulePoint.png'/> Pháp bảo <font color='#00ff00'>%s Giai </font> Nhưng kích hoạt <font color='#00ff00'>%s Cái </font> Binh Linh",
['lingQi059'] = "( Có được:%s)";
['lingQi060'] = "%s/%s";
}
)
