UIStrConfig:Add(
{
['uiMarriage001'] = 'Ngày   Một  Hai  Ba  Bốn  Năm   Sáu',
['uiMarriage002'] = 'Đơn giản hôn lễ',
['uiMarriage003'] = 'Xa hoa hôn lễ',
['uiMarriage004'] = 'Hôn lễ tốn hao',
['uiMarriage005'] = 'Xác nhận hôn lễ',
['uiMarriage006'] = 'Xác định',
['uiMarriage010'] = 'Ngươi là có hay không nguyện ý tiếp nhận           Trở thành bạn lữ của ngươi?',
['uiMarriage011'] = 'Song phương sau khi đồng ý, các ngươi đem chính thức trở thành vợ chồng!',
['uiMarriage012'] = 'Tham gia',
['uiMarriage013'] = 'Không tham gia',
['uiMarriage014'] = 'Tình cảm được không dễ, khư khư cố chấp cần cẩn thận',
['uiMarriage015'] = 'Phải chăng xác nhận giải trừ hôn ước?',
['uiMarriage016'] = '1. Không còn có được vợ chồng chuyên môn xưng hào',
['uiMarriage017'] = '2. Mất đi vốn có vợ chồng kỹ năng',
['uiMarriage018'] = 'Ly hôn cần giao nạp: ',
['uiMarriage019'] = 'Ly hôn hậu quả: ',
['uiMarriage020'] = 'Tục ngữ nói làm sao tính được số trời',
['uiMarriage021'] = 'Vợ chồng vốn là tình vợ chồng, làm sao cũng hữu duyên tận lúc',
['uiMarriage022'] = 'Nếu như đã suy nghĩ kỹ càng, sau đó các ngươi liền không còn là vợ chồng',
['uiMarriage023'] = 'Hủy bỏ',
['uiMarriage024'] = 'Người chơi danh tự',
['uiMarriage025'] = 'Hồng bao kim ngạch',
['uiMarriage026'] = 'Lời khen tặng',
['uiMarriage027'] = 'Hệ thống đem nhận được hồng bao chia đều đến người mới song phương tài khoản bên trong',
['uiMarriage028'] = 'Xin điền vào ngài muốn đưa tặng hồng bao kim ngạch',
['uiMarriage029'] = 'Lời khen tặng',
['uiMarriage030'] = 'Hai người tình đầu ý hợp, lẫn nhau ngưỡng mộ đã lâu, bọn hắn muốn đi vào hôn nhân điện đường, cũng chân thành mời ngài có mặt hôn lễ của bọn hắn, chứng kiến đôi này người mới lãng mạn thời khắc!',
['uiMarriage031'] = 'Thu được thiệp cưới người chơi, có thể vào hôn lễ nghi thức hiện trường.',
['uiMarriage032'] = '',
['uiMarriage033'] = 'Thoát',
['uiMarriage034'] = 'Xin điền vào ngài muốn đưa tặng hồng bao tổng phân số',
['uiMarriage035'] = 'Hôn lễ điển lễ thời gian: ',
['uiMarriage036'] = 'Mời đúng giờ tiến về <font color="#00ff00"> Bắc Thương thành - Hồng Nương </font> Chỗ mở ra hôn lễ nghi thức',
['uiMarriage037'] = 'Tiến về hẹn trước hôn lễ',
['uiMarriage038'] = 'Lập tức tiến về',
['uiMarriage039'] = 'Nhưng tại <font color="#00ff00"> Bắc Thương thành - Hồng Nương </font> Cầu hôn cùng với hắn kết hôn thao tác!',
['uiMarriage040'] = 'Hôn lễ tiếp tục thời gian hẹn 30 Phút, mời hợp lý an bài thời gian!' ,
['uiMarriage041'] = 'Quan bế',
['uiMarriage042'] = 'Hồng bao kim ngạch lớn hơn 50w, có thể đạt được  kẹo mừng bao!',
['uiMarriage043'] = 'Nhẫn cưới cường hóa',
['uiMarriage044'] = 'Cường hóa tiêu hao:',
['uiMarriage045'] = 'Mạnh  Hóa',
['uiMarriage046'] = '',
['uiMarriage047'] = '',
['uiMarriage048'] = '',
['uiMarriage049'] = '',
}
)
