StrConfig:Add(
{
['lianti1'] = "%sX%s(%s/%s) Đã đạt thành",
['lianti2'] = "%sX%s(%s/%s) Chưa đạt thành",
['lianti3'] = "Đẳng cấp đạt tới (%s/%s)",
['lianti4'] = "Đẳng cấp đạt tới <font color='#cc0000'>(%s/%s)</font>",
['lianti5'] = "Thứ %s Cấp",
['lianti6'] = "<font color='#2fe00D'>%s Cấp </font>",
['lianti7'] = "<font color='#cc0000'>%s Cấp </font>",
['lianti8'] = "<font color='#2fe00D'><u>%s</u></font>",
['lianti9'] = "<font color='#cc0000'><u>%s</u></font>",
['lianti10'] = "Cấp bậc chưa đủ, không thể tu luyện",
['lianti11'] = "Đạo cụ không đủ, không thể tu luyện",
['lianti12'] = "Linh lực không đủ, không thể tu luyện",
['lianti13'] = "Cấp bậc chưa đủ, không thể kích hoạt",
['lianti14'] = "Đạo cụ không đủ, không thể kích hoạt",
['lianti15'] = "Vận khí không tốt, tu luyện thất bại rồi!",
['lianti16'] = "<font color='#F4E036'> Sử dụng </font>%s<font color='#F4E036'> Thay thế tiêu hao </font>",
['lianti1000'] = "Công Kích",
['lianti1001'] = "Phòng Ngự",
['lianti1002'] = "Sinh Mệnh",
['lianti1003'] = "Bạo Kích",
['lianti1004'] = "Sức Bền",
['lianti1005'] = "Né Tránh",
['lianti1006'] = "Chính Xác",
['lianti1007'] = "Xuyên Đâm",
['lianti1008'] = "Đón Đỡ",
['lianti1009'] = "Đón đỡ giá trị",
['lianti1010'] = "Phá Phòng",
}
);
