UIStrConfig:Add(
{
-- Trận doanh chiến trường giao diện
['zhanchang001'] = "Trận doanh chiến trường",
['zhanchang002'] = "<font color='#29cc00'><u> Xem xét tổng bảng đơn </u></font>",
['zhanchang003'] = "Chiến trường tin tức",
['zhanchang004'] = "Khát máu bảng",
['zhanchang005'] = "Bảng cống hiến",
['zhanchang006'] = "Đạt được phương thức: Cướp đoạt Quân địch chiến kỳ",
['zhanchang007'] = "Đại thiên thế giới",
['zhanchang008'] = "Vực ngoại Tà Tộc",
['zhanchang009'] = "( Phe mình trận doanh mỗi đánh bại 5 Tên cờ làm, đặc thù điểm tướng đổi mới một cái nhưng cướp đoạt Quân địch chiến kỳ )",
['zhanchang010'] = "Phe mình trận doanh đánh bại cờ làm số: ",
['zhanchang011'] = "Đám tiếp theo chiến kỳ đổi mới thời gian: ",
['zhanchang012'] = "Thoát khỏi chiến trường",
['zhanchang013'] = "Danh tính người chơi",
['zhanchang014'] = "Gộp lại đánh tan",
['zhanchang015'] = "Liên tục đánh tan:",
['zhanchang016'] = "Chiến tích của ta:",
['zhanchang017'] = "Người cống hiến",
['zhanchang018'] = "Lập tức tham gia",
['zhanchang019'] = "Quan sát",
['zhanchang020'] = "Đại thiên thế giới",
['zhanchang021'] = "Vực ngoại Tà Tộc",
['zhanchang022'] = "Đánh tan",
['zhanchang023'] = "Lớn nhất liên tục đánh tan",
['zhanchang024'] = "<font color='#00ff00'><u> Chi tiết quy tắc </u></font>",
['zhanchang025'] = "<font color='#00ff00'><u> Xem xét ban thưởng </u></font>",
['zhanchang026'] = "Ban thưởng",
['zhanchang027'] = "Quân địch bắc bộ chiến kỳ: ",
['zhanchang028'] = "Quân địch nam bộ chiến kỳ: ",
['zhanchang029'] = "Trung lập chiến kỳ điểm: ",
['zhanchang030'] = "Chiến đấu sắp bắt đầu, phải chăng xác nhận tiến vào?",
['zhanchang031'] = "Tiến vào chiến đấu",
['zhanchang032'] = "<font color='#c2793e'> Đạt được phương thức: </font><font color='#00ff00'> Cướp đoạt Quân địch chiến kỳ </font>",
['zhanchang033'] = "<u> Tiến về </u>",
['zhanchang034'] = "Ngài nâng lên Quân địch cờ xí, xin mau sớm giao cờ!",
['zhanchang035'] = "<u> Tiến về giao cờ </u>",
['zhanchang036'] = "Người cống hiến:",
['zhanchang037'] = "Tổng đánh tan:",
-- Ban thưởng giao diện
['zcReward001'] = "Chiến trường kết toán",
['zcReward006'] = "Tổng đánh tan hạng nhất",
['zcReward007'] = "Liên tục đánh tan hạng nhất",
['zcReward008'] = "Cống hiến hạng nhất",
['zcReward009'] = "Tổng đánh tan",
['zcReward011'] = "Liên tục đánh tan",
['zcReward012'] = "Cống hiến",
['zcReward013'] = "Chiến tích của ta",
['zcReward014'] = "Người cống hiến:",
['zcReward015'] = "Đánh tan ban thưởng",
['zcReward016'] = "Cống hiến ban thưởng",
['zcReward017'] = "Thắng lợi ban thưởng",
['zcReward018'] = "Tham dự ban thưởng",
['zcReward019'] = "Lĩnh thưởng rời khỏi",
-- Chiến trường ban thưởng nói rõ
['zhchRewardS001'] = "Chiến trường thắng lợi gói quà",
['zhchRewardS002'] = "Chiến trường phe thắng lợi tất cả kiên trì đến sau cùng người chơi đồng đều có thể đạt được ",
['zhchRewardS003'] = "Chiến trường dũng sĩ gói quà",
['zhchRewardS004'] = "Thất bại một phương cũng kiên trì đến sau cùng người chơi đồng đều có thể đạt được ",
['zhchRewardS005'] = "Chiến trường lớn nhất cống hiến gói quà",
['zhchRewardS006'] = "Chiến trường cống hiến bảng xếp hạng thứ 1 Tên người chơi đồng đều có thể đạt được ",
['zhchRewardS007'] = "Chiến trường đột xuất cống hiến gói quà",
['zhchRewardS008'] = "Chiến trường cống hiến bảng xếp hạng thứ 2-5 Tên người chơi đồng đều có thể đạt được ",
['zhchRewardS009'] = "Chiến trường sát thần gói quà",
['zhchRewardS010'] = "Bên trong chiến trường tính gộp lại đánh giết thứ 1 Tên người chơi có thể đạt được ",
['zhchRewardS011'] = "Chiến trường giết chóc gói quà",
['zhchRewardS012'] = "Bên trong chiến trường tính gộp lại đánh giết thứ 2-5 Tên người chơi đồng đều có thể đạt được ",
['zhchRewardS013'] = "",
['zhchRewardS014'] = "",
['zhchRewardS015'] = "",
['zhchRewardS016'] = "",
['zhchRewardS017'] = "",
['zhchRewardS018'] = "",
['zhchRewardS019'] = "",
['zhchRewardS020'] = "",
}
)
