StrConfig:Add(
{
['chat100'] = '%s Tuyến,%s(X:%s,Y:%s)',
['chat101'] = '【%s】',
['chat102'] = 'Điểm kích khóa chặt trước mắt màn hình',
['chat103'] = 'Thu hồi',
['chat104'] = 'Mở ra',
['chat105'] = 'Chọn mở thiết lập nói chuyện phiếm',
['chat106'] = 'Gửi đi vị trí của ta <br/> Mỗi %s Giây sử dụng một lần',
['chat107'] = 'Loa',
['chat108'] = '[ Vị trí của ta ]',
['chat109'] = "Lần này loa phát biểu sẽ tiêu hao <font color='#00FF00'>1</font> Cái %s",
['chat110'] = "Đạo cụ không đủ lúc, tự động tốn hao <font color='#ffcc33'>%s</font> Nguyên bảo",
['chat111'] = "Biểu Cảm",
['chat112'] = "Không tại cùng một cái tuyến, không cách nào đến",
['chat113'] = "Nội dung gửi không thể vì không",
['chat114'] = "Số lượng Loa không đủ",
['chat115'] = "Nguyên bảo không đủ",
['chat116'] = "Khu vực hiện tại không thể gửi tọa độ",
['chat117'] = "Hiện tại địa đồ không thể đến",
['chat118'] = "Ngươi nói chuyện quá nhanh!",
['chat119'] = "<font color='#00FF00'> Báo cáo thành công </font>",
['chat120'] = "<font color='#FF0000'> Hiện tại đẳng cấp công năng chưa mở ra </font>",
-- Kênh tên
['chat200'] = 'Tổng hợp',
['chat201'] = 'Thế giới',
['chat202'] = 'Khu vực',
['chat203'] = 'Trận doanh',
['chat204'] = 'Bang phái',
['chat205'] = 'Tổ đội',
['chat206'] = 'Loa',
['chat207'] = 'Vượt phục',
['chat208'] = 'Ích lợi',
-- Nói chuyện riêng
['chat300'] = 'Đẳng cấp: %s Cấp',
['chat301'] = 'Mời tổ đội',
['chat302'] = 'Thêm hảo hữu',
['chat303'] = 'Phục chế danh tự',
['chat304'] = 'Thêm sổ đen',
['chat305'] = 'Nhập tối đa %s ký tự',
['chat306'] = 'Cùng %s nói chuyện mật',
-- Menu
['chat400'] = 'Nói chuyện',
['chat401'] = 'Xem',
['chat402'] = 'Thêm hảo hữu',
['chat403'] = 'Thêm sổ đen',
['chat404'] = 'Mời nhập bang',
['chat405'] = 'Xin nhập bang',
['chat406'] = 'Tạo đội ngũ',
['chat407'] = 'Xin về chỗ',
['chat408'] = 'Mời về chỗ',
['chat409'] = 'Phục chế tên',
['chat410'] = 'Báo cáo người chơi',
-- Thành chủ chức vị
['chat500'] = 'Chúng thần chi vương',
['chat501'] = 'Thiên địa Tôn giả',
['chat502'] = 'Hộ pháp',
['chat503'] = 'Chí tôn thiên minh',
['chat601'] = 'Nói chuyện',
['chat602'] = 'Bản phục',
['chat603'] = 'Khu vực',
['chat604'] = "%s Năm %s tháng %s Ngày",
}
);
