UIStrConfig:Add(
{
['union1'] = 'Bang phái',
['union2'] = 'Tin tức',
['union3'] = 'Danh sách thành viên',
['union4'] = 'Kỹ năng',
['union5'] = 'Hoạt động',
['union6'] = 'Liệt biểu',
['union7'] = 'Xếp hạng: ',
['union8'] = 'Cấp: ',
['union9'] = 'Lực chiến: ',
['union10'] = 'Tên bang: ',
['union11'] = 'Bang chủ: ',
['union12'] = 'Nhân số: ',
['union13'] = 'Chức vị: ',
['union14'] = 'Cống hiến: ',
['union15'] = 'Tổng hiến: ',
['union16'] = 'Bang phái sinh động: ',
['union17'] = 'Tài nguyên: ',
['union18'] = 'Thăng cấp',
['union19'] = 'Sửa đổi',
['union20'] = 'Cống hiến',
['union21'] = 'Sự kiện',
['union22'] = 'Danh sách xin vào',
['union23'] = 'Tên',
['union24'] = 'Cấp',
['union25'] = 'Chức vị',
['union26'] = 'Lực chiến',
['union27'] = 'Địa đồ',
['union28'] = 'Cống hiến',
['union29'] = 'Online',
['union30'] = 'Hiện thành viên online',
['union31'] = 'Giải tán',
['union32'] = 'Thoát',
['union33'] = 'Bang phái sự kiện',
['union34'] = 'Phát sinh thời gian',
['union35'] = 'Tên',
['union36'] = 'Cấp',
['union37'] = 'Lực chiến',
['union38'] = 'Xin thời gian',
['union39'] = 'Thao tác',
['union40'] = 'Trở lên người chơi xin',
['union42'] = 'Đồng ý',
['union43'] = 'Cự tuyệt',
['union44'] = 'Tự động đồng ý đẳng cấp',
['union45'] = 'Tìm',
['union46'] = 'Đổi mới',
['union47'] = '%s Cấp trở lên người chơi nhưng gia nhập hoặc sáng tạo bang phái',
['union48'] = 'Tạo bang phái',
['union49'] = 'Xin',
['union50'] = 'Xem xét',
['union51'] = 'Huỷ bỏ',
['union52'] = 'Xếp hạng',
['union53'] = 'Tên bang',
['union54'] = 'Bang chủ',
['union55'] = 'Cấp',
['union56'] = 'Lực chiến',
['union57'] = 'Nhân số',
['union58'] = 'Thao tác',
['union59'] = 'Bang phái tự động đồng ý gia nhập bang',
['union60'] = 'Đẳng cấp hiện tại đạt tối đa: ',
['union61'] = 'Hiệu quả hiện tại: ',
['union62'] = 'Hạ giai hiệu quả: ',
['union63'] = 'Tiêu hao cống hiến: ',
['union64'] = 'Tăng lên cần thiết điều kiện',
['union65'] = 'Đẳng cấp: ',
['union66'] = 'Tài chính: ',
['union67'] = 'Tài nguyên: ',
['union68'] = 'Bang phái đẳng cấp càng cao, nhưng mở ra bang phái kỹ \n Có thể càng nhiều, kỹ năng đẳng cấp hạn mức cao nhất càng cao.\n Rời khỏi bang phái lúc giữ lại bang phái kỹ năng hiệu quả, \n Một lần nữa gia nhập mới bang phái nhưng tiếp tục thăng cấp.\n Như tự thân kỹ năng đẳng cấp lớn hơn mới bang phái kỹ năng \n Hiệu quả hạn mức cao nhất, đem không cách nào thăng cấp.',
['union69'] = 'Sáng tạo bang phái',
['union70'] = 'Bang phái tên',
['union71'] = 'Bang phái thông cáo',
['union72'] = 'Xin điền vào bang phái tên',
['union73'] = 'Xin điền vào bang phái thông cáo, nhiều nhất không được vượt qua 40 Cái chữ.',
['union74'] = 'Sáng tạo bang phái cần điều kiện',
['union75'] = '1, nhân vật đẳng cấp: ',
['union76'] = '2, đạo cụ nhu cầu: ',
['union77'] = 'Ấm áp nhắc nhở: Nhân vật đẳng cấp đạt tới %s Cấp mới có thể sáng tạo hoặc gia nhập bang phái.',
['union78'] = 'Xem xét tin tức',
['union79'] = 'Viết mới thông cáo',
['union80'] = 'Quyên Hiến',
['union81'] = 'Hủy bỏ',
['union82'] = 'Bang phái tài chính: ',
['union83'] = 'Ta cống hiến: ',
['union84'] = 'Có được số lượng: ',
['union85'] = 'Quyên tặng số lượng: ',
['union86'] = 'Lệnh bài thu hoạch được đường tắt: Bang phái Boss, thế giới Boss Chờ',
['union87'] = 'Mời ở đây đưa vào lục soát nội dung',
['union88'] = 'Mời ở đây đưa vào bang phái thông cáo nhiều nhất không cao hơn 60 Cái chữ',
['union89'] = 'Đồng ý',
['union90'] = 'Cự tuyệt',
['union91'] = '0',
['union92'] = 'Đã xin',
['union93'] = 'Bang phái hiến cho',
['union94'] = 'Thăng cấp',
['union95'] = 'Thăng Cấp',
['union96'] = 'Học Tập',
['union97'] = 'Gia nhập bang phái',
['union98'] = 'Xác định',
['union99'] = 'VIP Cấp bậc chưa đủ',
['union100'] = 'Thế giới thu người',
['union101'] = 'Triệu  Tập',
['union102'] = 'Tổ chức hoạt động',
['union103'] = 'Triệu tập người: ',
['union104'] = 'Triệu tập thời gian: ',
['union105'] = 'Bãi miễn',
['union106'] = 'Bang chủ liên tục 5 Ngày chưa đăng lục, Phó bang chủ nhưng Bãi miễn bang chủ \n Như Phó bang chủ cũng liền tục 3 Ngày chưa đăng ký, thì từ trưởng lão Bãi miễn \n Như trưởng lão liên tục 2 Ngày chưa đăng lục, từ tinh anh cùng bang chúng Bãi miễn \n Bãi miễn lập tức có hiệu lực',
['union107'] = 'Trở lên chức vị tự động phê chuẩn',
['union108'] = 'Phê chuẩn',
['union109'] = 'Cự tuyệt',
['union110'] = 'Huỷ bỏ',
['union111'] = 'Xác nhận Bãi miễn',
['union150'] = "Bang phái ngoại giao",
['union151'] = "Đồng minh bang phái",
['union152'] = "Thành lập đồng minh",
['union153'] = "Xin đồng minh",
['union154'] = '<font color="#cc0000"> Tạm thời chưa có </font>',
['union155'] = 'Hủy bỏ đồng minh',
['union156'] = 'Toàn bộ xem nhẹ',
['union190'] = 'Ngươi nhất định phải hướng bang phái <font color="#ff8f43">[%s]</font> Phát ra đồng minh xin a',
['union191'] = 'Ngươi xác định giải trừ cùng bang phái <font color="#ff8f43">[%s]</font> Đồng minh quan hệ a',
['union200'] = "<img width='15' height='15' vspace='3' src='img://resfile/icon/rulePoint.png'/><p> Tại PK Tràng cảnh bên trong, đồng minh bang phái người chơi tại đồng minh hình thức hạ không thể công kích lẫn nhau.</p>",
['union300'] = 'Hoạt động',
-----
['unionwar001'] = "Bang phái chiến",
['unionwar002'] = "Bảng điểm số",
['unionwar003'] = "Đánh tan bảng",
['unionwar004'] = "Bang phái tên",
['unionwar005'] = "Trước mắt điểm tích lũy",
['unionwar006'] = "Ban thưởng",
['unionwar007'] = "Bản bang điểm tích lũy",
['unionwar008'] = "Xếp hạng",
['unionwar009'] = "<font color='#00ff00'><u> Cỡ nhỏ di tích </u></font>",
['unionwar010'] = "<font color='#00ff00'><u> Cỡ trung di tích </u></font>",
['unionwar011'] = "<font color='#00ff00'><u> Chí tôn di tích </u></font>",
['unionwar012'] = "Chí tôn di tích chiếm lĩnh bang phái: ",
['unionwar013'] = "Lập tức tham gia",
['unionwar014'] = "GO",
['unionwar015'] = "<u> Tiến tới địa đồ </u>",
['unionwar016'] = "Trở về",
['unionwar017'] = "",
['unionwar018'] = "Ngài bang phái thành công đánh bại bang phái chiến trường thủ vệ, thu hoạch được tiến vào bang phái chiến tư cách.",
['unionwar019'] = "Hoạt động đếm ngược",
['unionwar020'] = "Xếp hạng",
['unionwar021'] = "Điểm tích lũy:",
['unionwar022'] = "Tư cách thu hoạch được",
['unionwar023'] = "Bang phái xếp hạng",
['unionwar024'] = "Thu hoạch được ban thưởng",
['unionwar025'] = "Lĩnh thưởng rời khỏi",
['unionwar026'] = "Bản bang xếp hạng:",
['unionwar027'] = "Công kích cấp thấp di tích có thể đạt được  chút ít điểm tích lũy",
['unionwar028'] = "Công kích trung cấp di tích có thể đạt được  trung lượng điểm tích lũy",
['unionwar029'] = "Chiếm lĩnh chí tôn di tích có thể đạt được  đại lượng điểm tích lũy",
['unionwar030'] = "Hoạt động đếm ngược:",
['unionwar031'] = "<font color='#ffcc33'><u> Tiến về chiếm lĩnh </u></font>",
['unionwar032'] = "Chỉ có đánh bại bang phái chiến thủ vệ bang phái, mới có tư cách tiến vào bang phái chiến trường!",
['unionwar033'] = "<u> Bang phái chiến thủ vệ </u>",
['unionwar034'] = "Bắt đầu công kích",
['unionwar036'] = "Ra khỏi chiến trường",
['unionwar037'] = "Tích lũy cá nhân",
['unionwar038'] = "Tích lũy bổn Bang: ",
['unionwar039'] = "Xếp hạng: ",
['unionwar040'] = "Cá nhân tích lũy: ",
['unionwar041'] = "Điểm tích lũy",
------------------------------ Địa cung Luyện Ngục -------------------------------------
['unionhell001'] = "Chọn  Chiến",
['unionhell002'] = "Thoát",
['unionhell003'] = "Lĩnh thưởng rời khỏi",
['unionhell004'] = "Trở lại  Về",
--------- Bang phái vương thành chiến
['unioncitywarUI801'] = 'Bang phái vương thành chiến';
['unioncitywarUI802'] = 'Bang phái vương thành chiến';
['unioncitywarUI803'] = 'Trở về';
['unioncitywarUI804'] = 'Lập tức tham gia';
['unioncitywarUI805'] = 'Cấu trúc Chiến Trường';
['unioncitywarUI806'] = 'Thuộc về bang phái';
['unioncitywarUI807'] = 'Thao tác';
['unioncitywarUI808'] = 'Rời khỏi';
['unioncitywarUI809'] = 'Thống kê Chiến Trường';
['unioncitywarUI810'] = 'Đánh bại';
['unioncitywarUI811'] = 'Tiến về';
['unioncitywarUI812'] = '<u> Chí tôn vương tọa </u>';
['unioncitywarUI813'] = '<u> Thanh Long tượng thần </u>';
['unioncitywarUI814'] = '<u> Bạch Hổ tượng thần </u>';
['unioncitywarUI815'] = '<u> Chu Tước tượng thần </u>';
['unioncitywarUI816'] = '<u> Huyền Vũ tượng thần </u>';
['unioncitywarUI817'] = 'Bảo hộ chí tôn vương thành không bị phá hủy!';
['unioncitywarUI818'] = 'Chiếm lĩnh Thần thú tượng thần nhưng kích hoạt phụ cận điểm phục sinh, đồng thời thu hoạch được buff Tăng thêm. Vẻn vẹn phe tấn công hữu hiệu.';
['unioncitywarUI819'] = 'Hoạt động đếm ngược:';
['unioncitywarUI820'] = '<u> Chiến trường địa đồ </u>';
['unioncitywarUI821'] = 'Ta chiến công:';
['unioncitywarUI822'] = 'Xếp hạng:';
['unioncitywarUI823'] = 'Lĩnh thưởng rời khỏi';
['unioncitywarUI824'] = 'Sau tự động lĩnh thưởng rời khỏi';
['unioncitywarUI825'] = '';
['unioncitywarUI826'] = '';
['unioncitywarUI827'] = '';
['unioncitywarUI828'] = '';
['unioncitywarUI829'] = '';
['unioncitywarUI830'] = '';
------------------------------------ Bang phái nhà kho
['unionWareHouseUI001'] = 'Nhà kho';
['unionWareHouseUI002'] = 'Ba lô trang bị';
['unionWareHouseUI003'] = 'Còn trống: ';
['unionWareHouseUI004'] = 'Điểm cống: ';
['unionWareHouseUI005'] = 'Đại lượng dung luyện';
['unionWareHouseUI006'] = 'Nhà kho chỉnh lý';
['unionWareHouseUI007'] = 'Toàn bộ';
['unionWareHouseUI008'] = 'Tồn nhân vật phẩm';
['unionWareHouseUI009'] = 'Lấy ra vật phẩm';
['unionWareHouseUI010'] = 'Nhà kho ghi chép';
['unionWareHouseUI011'] = 'Ok';
['unionWareHouseUI012'] = 'Hủy';
['unionWareHouseUI013'] = 'Dung luyện vật phẩm';
['unionWareHouseUI014'] = 'Số lần tồn nhập: ';
['unionWareHouseUI015'] = 'Phê duyệt liệt biểu';
------------------------------------ Bang phái cầu phúc
['unionPray001']= 'Người hiến:';
['unionPray002']= 'Bang phái sinh động:';
['unionPray003']= 'Tiêu hao:';
['unionPray004']= 'Tiêu hao:';
['unionPray005']= 'Phổ thông';
['unionPray006']= 'Cao cấp';
['unionPray007']= 'Chí tôn';
['unionPray008']= 'Bang phái cầu phúc:';
----------------------------------------- Bang phái boss
['UIunionBoss001']='Mở ra thời gian:';
['UIunionBoss002']='Hoạt động có thể đạt được : ';
['UIunionBoss003']='Triệu hoán tiêu hao: ';
['UIunionBoss004']='Ta xếp hạng: ';
['UIunionBoss005']='Tham dự nhân số: ';
['UIunionBoss006']='<u> Hoạt động truy tung </u>';
['UIunionBoss007']='Khiêu chiến thành công';
['UIunionBoss008']='Khiêu chiến thất bại';
['UIunionBoss009']='Tự động chiến đấu';
['UIunionBoss010']='Rời khỏi hoạt động';
['UIunionBoss011']='Xúc phạm cá nhân xếp hạng ban thưởng: ';
['UIunionBoss012']='Bang phái ban thưởng: ';
['UIunionBoss013']='Bang phái tất cả thành viên có thể đạt được  ban thưởng: ';
['UIunionBoss014']='Hạn định thời gian bên trong chưa thể thành công đánh giết BOSS, chỉ có thể thu hoạch được tổn thương xếp hạng ban thưởng!';
['UIunionBoss015']='Lĩnh thưởng rời khỏi';
['UIunionBoss016']='Bang phái tài chính: ';
['UIunionBoss017']='Hoạt động đếm ngược: ';
['UIunionBoss018']='';
['UIunionBoss019']='';
['UIunionBoss020']='';
----------------------------------------- Bang phái địa cung tranh đoạt chiến
['unionDiGong001']='Đấu giá';
['unionDiGong002']='<u> Nhỏ địa đồ </u>';
['unionDiGong003']='Thoát khỏi chiến trường';
['unionDiGong004']='Tiến vào chiến trường';
['unionDiGong005']='Xác thực Định';
['unionDiGong006']='Bản bang xếp hạng:';
['unionDiGong007']='Đấu thầu tài chính';
['unionDiGong008']= "Xếp hạng";
['unionDiGong009'] = "Tên bang";
['unionDiGong010'] = "Tài chính";
['unionDiGong011'] = "Đấu giá";
['unionDiGong012'] = "Điểm kích tiến về";
['unionDiGong013'] = "Tiến vào chiến đấu";
['unionDiGong014'] = "<u> Tiến về tranh đoạt </u>";
})
